chainguard-images/images

.github/actions/release-image/action.yml

Optimize order of vuln scanning attestations

---

images/alpine-base/README.md
images/apko/README.md
images/busybox/README.md
images/gcc-glibc/README.md
images/gcc-musl/README.md
images/git/README.md
images/glibc-dynamic/README.md
images/go/README.md
images/jdk/README.md
images/jenkins/README.md
images/jre/README.md
images/ko/README.md
images/kubectl/README.md
images/maven/README.md
images/melange/README.md
images/musl-dynamic/README.md
images/nginx/README.md
images/node/README.md
images/php/README.md
images/postgres/README.md
images/python/README.md
images/ruby/README.md
images/sdk/README.md
images/static/README.md
images/wolfi-base/README.md

Still need more work, but this is a start.
Signed-off-by: Adrian Mouat <adrian@chainguard.dev>

Fix READMEs for images.

---

images/bazel/README.md
images/jdk/README.md
images/jdk/configs/openjdk-11.apko.yaml
images/jdk/configs/openjdk-17.apko.yaml
images/jre/README.md
images/jre/configs/openjdk-jre-11.apko.yaml
images/jre/configs/openjdk-jre-17.apko.yaml

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>

add simple java docs

---

.github/actions/build-image/action.yml
.github/actions/generate-matrix/action.yml
.github/actions/release-image/action.yml
.github/actions/verify-readme/action.yml
.github/dependabot.yml
.github/workflows/presubmit-build-melange.yaml
.github/workflows/presubmit-build.yaml
.github/workflows/presubmit-readme.yaml
.github/workflows/release.yaml

- use git hashes and update to latest releases
- configure dependabot

Updates in CI jobs and dependabot config

---

images/postgres/configs/15.apko.yaml

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>

include postgres contrib package

---

.github/actions/release-image/action.yml

Tag the image only after all attestations attached

---

.github/actions/build-image/action.yml
.github/actions/release-image/action.yml
images/apko/image.yaml
images/melange/image.yaml
images/nginx/image.yaml
images/sdk/image.yaml
monopod/pkg/images/images.go

Add support for multiple melange configs per image

---

images/sdk/configs/latest.apko.yaml

Signed-off-by: Tuan Anh Tran <me@tuananh.org>

fix: add ca-certificates-bundle to sdk image

---

images/go/README.md
images/go/configs/latest-glibc.apko.yaml
images/go/configs/latest.apko.yaml
images/go/test.sh

Closes #143 
Signed-off-by: Patrick Flynn <patrick@chainguard.dev>

add git to golang image

---

images/bazel/configs/latest.apko.yaml
images/busybox/configs/latest-glibc.apko.yaml
images/envoy/configs/latest.apko.yaml
images/gcc-glibc/configs/latest.apko.yaml
images/git/configs/latest-glibc-root.apko.yaml
images/git/configs/latest-glibc.apko.yaml
images/glibc-dynamic/configs/latest.apko.yaml
images/go/configs/latest-glibc.apko.yaml
images/jdk/configs/openjdk-11.apko.yaml
images/jdk/configs/openjdk-17.apko.yaml
images/jenkins/configs/latest.apko.yaml
images/jre/configs/openjdk-jre-11.apko.yaml
images/jre/configs/openjdk-jre-17.apko.yaml
images/kubectl/configs/latest.apko.yaml
images/maven/configs/openjdk-11.apko.yaml
images/maven/configs/openjdk-17.apko.yaml
images/node/configs/latest.apko.yaml
images/php/configs/latest-glibc-dev.apko.yaml
images/php/configs/latest-glibc.apko.yaml
images/postgres/configs/15.apko.yaml
images/python/configs/latest-glibc.apko.yaml
images/ruby/configs/latest-3.0.apko.yaml
images/ruby/configs/latest-3.1.apko.yaml
images/sdk/configs/wolfi.apko.yaml
images/static/configs/latest-glibc.apko.yaml
images/wait-for-it/configs/latest.apko.yaml
images/wolfi-base/configs/latest.apko.yaml

build images for arm64

---

images/wait-for-it/README.md

Signed-off-by: Dan Lorenc <dlorenc@chainguard.dev>

Add docs for the wait-for-it image.

---

images/curl/configs/latest.apko.yaml

curl: only build for amd64 and arm64

---

images/bazel/README.md
images/bazel/configs/latest.apko.yaml
images/bazel/image.yaml

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>

bump to bazel version 6 + docs

---

images/cc-dynamic/configs/latest.apko.yaml
images/curl/configs/latest.apko.yaml
images/deno/configs/latest.apko.yaml
images/etcd/configs/latest.apko.yaml
images/gcc-glibc/configs/latest.apko.yaml
images/git/configs/latest-glibc-root.apko.yaml
images/git/configs/latest-glibc.apko.yaml
images/go/configs/1.20.apko.yaml
images/go/configs/latest.apko.yaml
images/kubectl/configs/latest.apko.yaml
images/node/configs/latest.apko.yaml
images/prometheus/configs/latest.apko.yaml
images/python/configs/latest-dev.apko.yaml
images/python/configs/latest.apko.yaml
images/rabbitmq/configs/latest.apko.yaml
images/redis/configs/latest.apko.yaml
images/sdk/configs/wolfi.apko.yaml
images/wait-for-it/configs/latest.apko.yaml
images/wolfi-base/configs/latest.apko.yaml

/cc @dlorenc re: https://github.com/chainguard-images/images/pull/181

Add wolfi-baselayout to all other Wolfi images

---

images/maven/README.md

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Thx, @tunix, for letting us know about that.

fix jdk, jre

---

images/ko/configs/latest.apko.yaml

ko: switch to wolfi

---

images/graalvm-native-image-base/README.md

Signed-off-by: Jason van Zyl <jason@vanzyl.ca>

Restore README.md for graalvm-native-image-base

---

.github/actions/build-image/action.yml
.github/actions/release-image/action.yml
monopod/pkg/images/images.go

also, hardcode x86_64 for faster CI

Allow specifying non empty workspace for melange builds

---

.github/actions/release-image/action.yml

Add ability to disable vuln scanners

---

.github/workflows/release.yaml

Allow workflow dispatch input to build a single image

---

images/php/README.md

Update README for the php image
Signed-off-by: Erika Heidi <erikaheidi@users.noreply.github.com>

Update PHP image README

---

images/melange/configs/latest.apko.yaml

add alpine-keys to melange image

---

.github/actions/build-image/action.yml
.github/actions/release-image/action.yml
images/apko/configs/latest.apko.yaml
images/melange/configs/latest.apko.yaml
images/nginx/configs/latest.apko.yaml
images/nginx/configs/stable.apko.yaml
monopod/pkg/constants/constants.go
monopod/pkg/images/images.go

Relies on https://github.com/chainguard-images/actions/pull/71

Add support for apko repository-append

---

images/static/examples/Dockerfile.c
images/static/examples/Dockerfile.golang
images/static/examples/Dockerfile.rust

~~Couldn't do rust as our image won't compile a static binary.~~

Migrate C and Go example to our images.

---

images/node/configs/16.apko.yaml
images/node/configs/19.apko.yaml

Signed-off-by: Patrick Flynn <patrick@chainguard.dev>

add the package update disable flag to more versions

---

images/python/README.md

This PR updates the python image example to properly install deps and copy them over.

Update python example

---

.github/actions/release-image/action.yml

less log output in actions for easier investigations (pt 2)

---

images/curl/configs/latest.apko.yaml
images/curl/tests/02-fetch-url.sh

Related to #302 
Expecting CI to fail here

Add test to curl, add ca-certificates-bundle

---

images/helm/configs/latest.apko.yaml

Fixes: 
Related: 
annotations:

Add kubectl to the helm image.

---

images/cosign/README.md

In collaboration with @jdolitsky!

Update Cosign image README

---

.github/pull-request-template.md

Update spacing on PR template to make PR descriptions smaller

Update spacing on PR template

---

images/cosign/README.md
images/python/image.yaml

update python dev names, and regen readmes.

fix names for best practice

---

images/busybox/README.md

Fixes:  https://github.com/chainguard-dev/internal/issues/1494
Related: 
annotations:
- [ x ]  Documentation. Let's make this excellent. Include usage example.

Update busybox README.

---

images/python/image.yaml

Add other dev tools needed for building python app/images

add other dev build tools needed for python dev

---

.github/actions/image-summary/action.yml
monopod/pkg/commands/matrix.go

Fix image summary to add subvariant suffix, respect excludes

---

images/python/image.yaml

add busybox to python dev images

add busybox

---

.github/actions/release-image/action.yml

This will need a change to `setup-chainctl` to correctly configure creds for `cgr.dev`, but once that's in we should be good to go.
cc @mattmoor

push to cgr.dev

---

images/redis/tests/02-server.sh

Add a test that redis starts up and listens and responds.

---

images/postgres/configs/latest.apko.yaml
images/postgres/tests/02-query.sh

Also add locales to silence a warning during startup.
Fixes:
Related:

Add a test that the postgres server is up and can be queried.

---

images/prometheus/README.md
images/prometheus/tests/02-healthy.sh

Add a test that prometheus starts up and is healthy.

---

images/nats/tests/02-healthy.sh
images/nats/tests/03-works.sh

Add nats tests that verify the server is healthy and works

---

images/traefik/README.md

Fixes:
Related: 
```
annotations:
```

Fix link error for traefik readme

---

images/jre/configs/openjdk-11.apko.yaml

related to https://github.com/wolfi-dev/os/pull/906

Update the JRE 11 JAVA_HOME to the latest location

---

images/kube-state-metrics/tests/02-runs.sh

Add a test that kube-state-metrics comes up and serves.

---

.github/ISSUE_TEMPLATE/new-image-request.yml

change PM assigned for new image requests

---

images/python/tests/01-version.sh

Add a test for python that verifies numpy and c extensions work.

---

images/jre/configs/latest.apko.yaml

Won't merge this until the package change is in the index.
Fixes:
https://github.com/chainguard-images/images/issues/297
Related: 
https://github.com/wolfi-dev/os/pull/1453

change java_home to reflect update to jre package

---

.github/actions/image-summary/action.yml

alternative to #490 in short term

Determine repo ID to use for tier updater

---

images/wolfi-base/README.md

Fix: Update readme to not refer to alpine-base

---

images/weaviate/configs/latest.apko.yaml

Fix the entrypoint of weaviate to correspond to the helm chart location.

---

images/node/example/package-lock.json
images/node/tests/01-version.sh

This adds a test to `docker build` the example using the image, run it, and check that the example server responds as expected.
This also updates the example's package dependencies to clear out some [dependabot](https://github.com/chainguard-images/images/security/dependabot/5) [security](https://github.com/chainguard-images/images/security/dependabot/2) [alerts](https://github.com/chainguard-images/images/security/dependabot/1).

node: add test to build and run example

---

.github/actions/build-image/action.yml
.github/actions/policy-check-image/action.yml
.github/actions/release-image/action.yml
.github/workflows/k8s-tests.yaml
.github/workflows/policy-check.yaml
.github/workflows/presubmit-build-melange.yaml
.github/workflows/presubmit-build.yaml
.github/workflows/presubmit-k8s-tests.yaml
.github/workflows/release.yaml

Use EXTRA_INPUTS etc for apko pinned image

---

CODEOWNERS

I'm not sure how to require 3+ approvals on these files only.

require additional review for certain images

---

images/mariadb/tests/02-runs.sh

Add test for mariadb.

---

images/vault/tests/02-runs.sh

Add test for the vault image

---

images/karpenter/README.md

URL is a bit problematic as version is embeded.

Fix: Update Karpenter URL.

---

.github/actions/release-image/action.yml

Fix double SLSA

---

.github/actions/build-image-terraform/action.yml
.github/workflows/presubmit-build.yaml
images/ko/configs/latest.apko.yaml
main.tf

follow-up to https://github.com/chainguard-images/images/pull/587#discussion_r1192771080
cc @imjasonh

Add Wolfi defaults to main.tf, remove from ko config

---

images/vertical-pod-autoscaler-updater/configs/latest.apko.yaml
images/vertical-pod-autoscaler-updater/image.yaml

This fixes the test after the package got fixed in wolfi.
Fixes:
Related:

Fix vertical-pod-autoscaler-udpater test.

---

images/vertical-pod-autoscaler-recommender/configs/latest.apko.yaml
images/vertical-pod-autoscaler-recommender/image.yaml

Finish fixing the vpa tests.

---

images/keda-adapter/configs/latest.apko.yaml
images/keda-admission-webhooks/configs/latest.apko.yaml
images/keda/configs/latest.apko.yaml
images/keda/tests/02-helm.sh

Also add tests.
Fixes:
Related:

Add keda compat package for compatibility with helm charts.

---

images/kubernetes-dashboard/tests/02-deploy.sh

And drop port-forward, it's too flaky and it's also redundant since the pod health check hits the same endpoint.
Fixes:
Related: 
This has passed now a few times on my fork.

Add debug logs to the dashboard test.

---

images/keda/tests/02-helm.sh

And fix the test by changing pullPolicy.
This has passed for me a few times now on my fork.

Add debug logging to keda tests.

---

images/telegraf/tests/02-helm.sh

Add telegraf test.

---

images/hugo/tests/02-quickstart.sh

Closes https://github.com/chainguard-images/images/issues/598

resolve TODO in hugo test

---

.github/workflows/k8s-tests.yaml
.github/workflows/policy-check.yaml
.github/workflows/presubmit-build-melange.yaml
.github/workflows/presubmit-build.yaml
.github/workflows/presubmit-k8s-tests.yaml
.github/workflows/release.yaml

Update images digests
```release-note
NONE
```

Update images digests

---

images/vertical-pod-autoscaler-admission-controller/tests/02-helm.sh

Fixes:
Related: Vertical Pod Autoscaler (for 3 components)

Add Helm Chart testing for VPA

---

images/metrics-server/tests/02-helm.sh

Add helm chart testing for metrics-server

---

images/jenkins/README.md

Fixes: #633 
A quick test of the commands would be good, just to be sure they work on someone else's system.

Fixes Jenkins README.md example commands

---

images/cluster-autoscaler/configs/latest.apko.yaml
images/cluster-autoscaler/tests/02-helm.sh

Fixes:
Related: https://github.com/wolfi-dev/os/pull/2214

Add compat package and helm chart test for cluster-autoscaler

---

images/argocd/README.md

Fixes:
Related: 
```
annotations:
```

Fix markdown link in argocd readme

---

main.tf

This will let us pass different values for these across contexts as we continue to evolve these workflows

Expose the "extra" settings as TF variables.

---

images/external-dns/tests/02-e2e.sh

Fix: fix broken yaml in the external-dns tests

fix broken yaml in the external-dns tests

---

.github/actions/build-image-terraform/action.yml
.github/actions/build-image/action.yml
.github/actions/release-image-terraform/action.yml
.github/actions/release-image/action.yml
.github/workflows/presubmit-build.yaml
.github/workflows/release.yaml

Right now only the TF provider is able to accept `extra_packages`, but Jason has a PR to add this to `apko` as a flag (and then the actions will need this).

Plumb through the `apkoFooAppend` variables as `TF_VAR`.

---

images/bazel/image.yaml
images/clang/image.yaml
images/consul/image.yaml
images/terraform/image.yaml

Switch some experimental images over to the terraform provider.

---

.github/actions/generate-matrix/action.yml
.github/workflows/image-summary.yaml
.github/workflows/k8s-tests.yaml
.github/workflows/policy-check.yaml
.github/workflows/presubmit-build-melange.yaml
.github/workflows/presubmit-build.yaml
.github/workflows/presubmit-k8s-tests.yaml
.github/workflows/release.yaml
monopod/pkg/commands/matrix.go
monopod/pkg/commands/options/matrix.go

This is trying to prepare us to workaround the 256-job limit in actions matrix fanout.

Plumb through sharding in `monopod generate-matrix`.

---

.github/workflows/release.yaml

Add back other 'needs'

---

.github/actions/image-summary/action.yml

see: https://github.com/jqlang/jq/issues/1017

Switch deduplication approach to avoid head exit code issue

---

main.tf
policies/04-has-slsa-attestation.yaml

Bump the module version to pick up a predicate type fix.

Fix: Allow the policy to accept v1 SLSA attestations

---

main.tf
policies/04-has-slsa-attestation.yaml

Reverts chainguard-images/images#722

Revert "Fix: Allow the policy to accept v1 SLSA attestations"

---

images/external-dns/tests/02-e2e.sh

It doesn't completely pass yet, but it gets further!
Fixes:
Related:

Fix ingress e2e test.

---

.github/workflows/k8s-tests.yaml
.github/workflows/policy-check.yaml
.github/workflows/presubmit-build-melange.yaml
.github/workflows/presubmit-build.yaml
.github/workflows/presubmit-k8s-tests.yaml
.github/workflows/release.yaml

Reverts chainguard-images/images#728
This might be breaking our arm64 builds, such that they include x86_64 packages erroneously

Revert "Update images digests"

---

.github/actions/build-image/action.yml
.github/actions/release-image/action.yml

Reverts chainguard-images/images#729
Needed after #741

Revert "Pass through extra packages."

---

images/google-cloud-sdk/configs/latest.apko.yaml

This is needed by Wolfi's build

add bash to google-cloud-sdk

---

images/haproxy-ingress/README.md
images/kubectl/tests/02-use.sh

Fix permission error running the kubectl test.

---

images/gatekeeper/configs/latest.apko.yaml
images/gatekeeper/tests/02-helm-install.sh

This was missing a compat package and some fun with the tagging in the chart.
Fixes:
Related:

Fix the helm test for gatekeeper.

---

images/newrelic-k8s-events-forwarder/tests/02-helm.sh

Fix k8s-event-forwarder test.

---

images/spire-agent/README.md
images/spire-agent/configs/latest.apko.yaml
images/spire-agent/tests/01-version.sh
images/spire-agent/tests/02-helm.sh

Add spire-agent test and fix spire image.

---

images/bazel/main.tf
images/clang/main.tf
images/consul/main.tf
images/crane/main.tf
images/ko/main.tf
images/terraform/main.tf
tflib/publisher/main.tf

:broom: This lets us define the version of the external module in a single place for the entire repo.
/kind cleanup

Cleanup: create a shim for the publisher

---

images/oidc-discovery-provider/configs/latest.apko.yaml
images/oidc-discovery-provider/tests/02-helm.sh

Add oidc provider test and fix image with new packaging scheme.

---

images/newrelic-prometheus-configurator/tests/02-helm.sh

Fix newrelic prometheus test.

---

images/envoy-ratelimit/tests/02-helm.sh

Fix envoy-ratelimit test.

---

images/kubernetes-csi-external-provisioner/tests/02-deploy.sh

This passes but there's a weird error in cleanup. Let it try to get logs but ignore errors.

Fix the csi test.

---

.github/readme-template.md

This PR introduces a new README template that should be used as reference when creating new images. 
Related: #766

Adding README template

---

images/vault/tests/03-helm.sh

Added a better vault test. Not sure why the last one was passing :/

Added more in-depth vault test.

---

images/vault-k8s/README.md
images/vault-k8s/tests/02-install.sh

As above, expanded docs & tests for this image.

Added docs and longer test for vault-k8s image.

---

.github/pull-request-template.md

adding agreed on quality requirements to the pr template

update to PR template with quality requirements

---

.github/actions/release-image/action.yml

WIP while I figure out how to test this.

use gcsfuse to mount the bucket instead of rsyncing

---

.github/actions/release-image/action.yml

can't create `/gcsfuse`, let's create `/tmp/gcsfuse`.

fix gcsfuse again again

---

withdrawn-images.txt

```
for r in `chainctl img repos ls -ojson | jq -r '.items[].name'`; do echo --- $r 1>&2; for t in `crane ls cgr.dev/chainguard/$r | grep dev-dev`; do echo --------- $r $t; done; done
```

withdraw more -dev-dev tags

---

.github/actions/release-image/action.yml

gcsfuse does not automatically recurse subdirectories, so help it out a bit with additional symlinks

release-image: fix up gcsfuse

---

.github/pull-request-template.md

Signed-off-by: Adam Dawson <adam@chainguard.dev>

add ca-certs check to PR checklist

---

.github/actions/release-image-terraform/action.yml

This won't have any effect unless the `gcsFetchAllPackages` is set to `false`

optionally fetch only needed packages

---

images/jdk/README.md
images/jre/README.md

Fixes https://github.com/chainguard-images/images/issues/733

fix java examples

---

monopod/pkg/lint/rules.go
monopod/pkg/lint/rules_test.go
monopod/pkg/lint/testdata/forbidden-repository-tagged.yaml

Based on https://github.com/wolfi-dev/wolfictl/pull/253

lint: add check for tagged repositories

---

.github/actions/build-image-terraform/action.yml

Depends on https://github.com/chainguard-dev/actions/pull/251

Install crane from tip

---

images/configmap-reload/tests/02-helm.sh

* Fix: fix helm test for confimap-reload

fix helm test for confimap-reload

---

.github/actions/build-image-terraform/action.yml
tflib/publisher/main.tf

I'm touching the actions so all the tests run

Bump our TF deps to go much much faster

---

.github/actions/build-image-terraform/action.yml
.github/actions/release-image-terraform/action.yml

This should be a nop for now, but I'm trying to use this to stage the mega-module in downstream (and eventually here 🤞)

Add preliminary support for building image modules through a mega module

---

images/secrets-store-csi-driver/configs/latest.apko.yaml

Moved out as a separate package in https://github.com/wolfi-dev/os/commit/fb3fbf1ad9de34a0e792ec978de887f67cab9aea

Add mount to secrets-store-csi-driver

---

.github/dependabot.yml

I thought this was the default 🤦

Add missing directory attribute

---

images/postgres/main.tf

Just adding a dev variant to the postgres image

Variant: Add postgres dev variant

---

images/nginx/README.md

Quick edit to fix-up the readme.

Fix: example docker run command in README

---

tflib/publisher/main.tf

When this lands we can expand it to include more simple checks.

add a simple structure test for all images

---

images/weaviate/configs/latest.apko.yaml

Fix permissions for weaviate data directory.

---

images/k3s/tests/smoke.sh

turns out CI can be slower when it feels like it 🤷

increase k3s readiness timeout

---

images/hugo/tests/02-quickstart.sh

Reverts chainguard-images/images#1072

Revert "Fix the Hugo tests until we can rebuild our git images"

---

.github/actions/build-image-terraform/action.yml
.github/actions/release-image-terraform/action.yml
tflib/publisher/main.tf

Fixes: https://github.com/chainguard-images/images/pull/846

Pull in the latest tf-apko, apko, tf-oci

---

images/php/configs/latest-fpm.apko.yaml
images/php/tests/main.tf

This PR fixes the php-fpm image entrypoint - _now **for real**_ - and adds a more robust test to check that the service is really up and running.

Fixing php-fpm image and test

---

images/external-dns/tests/e2e.sh

similar to: https://github.com/chainguard-images/images/pull/1117

Add another sleep after apply before wait

---

images/php/tests/01-fpm-server.sh
images/php/tests/02-shutdown.sh
images/php/tests/fpm-server.sh
images/php/tests/main.tf

This PR should fix the PHP-fpm test that is currently failing at build time.

Fix: fix php-fpm test

---

images/aws-ebs-csi-driver/configs/latest.apko.yaml

Update ebs csi driver with mount package

---

images/buck2/tests/main.tf

https://github.com/chainguard-images/images/issues/1054

disable flaky buck2 test

---

images/k3s/main.tf
tflib/publisher/check-reproducibility.sh
tflib/tagger/main.tf

Drop `APKO_IMAGE` echo to avoid local dev annoyance.  This was for bring-up to make sure it was coming through from the runner.

Add an assertion to catch k3s tagging woes

---

images/go/tests/base-image-custom-entrypoint.sh
images/go/tests/base-image.sh
images/python/tests/04-build.sh
images/ruby/tests/03-base-image.sh

https://github.com/chainguard-images/images/actions/runs/5812286542/job/15757371812?pr=1194#step:6:8516

Pre-pull image in base image tests

---

images/k8s-sidecar/configs/latest.apko.yaml

Notes: I've manually verified the behavior is the same as before.

Fix the entrypoint for k8s-sidecar to reflect the package update.

---

.github/workflows/release.yaml

should fix error
```
${matrix.imageName} : bad substitution
```

rework conditional if statment as original approach didnt work

---

images/cert-manager/main.tf

needs: https://github.com/wolfi-dev/os/pull/4702

Fetch the version tags from the version stream package.

---

images/stakater-reloader/tests/main.tf

This is ported from our downstream repo.

Allow for multiple versions of stakater to be tested concurrently.

---

images/gatekeeper/configs/latest.apko.yaml
images/gatekeeper/main.tf

This is the same APK but renamed. Will need to wait for https://github.com/wolfi-dev/os/pull/4886/files to land first.

Switch to use version streamed gatekeeper-3.13 package

---

images/argocd/configs/latest.argocd.apko.yaml
images/argocd/main.tf

These are currently the same packages, but version streamed in https://github.com/wolfi-dev/os/pull/4890

Use argo-cd-2.8 version stream packages

---

images/thanos/main.tf

This is the same version but switching to 0.32 version stream in https://github.com/wolfi-dev/os/pull/4928

Switch thanos to use version streamed package

---

BEST_PRACTICES.md
images/cadvisor/configs/latest.apko.yaml
images/slim-toolkit-debug/configs/latest.apko.yaml
main.tf
tflib/publisher/main.tf

These were left over from when annotations were set in TF.

Resolve TODOs about annotations

---

images/calico/tests/install.sh
images/crossplane-aws/tests/install.sh
images/crossplane-azure/tests/install.sh

increase timeouts to reduce flakes

---

images/node-problem-detector/main.tf

This is the same package converted to version stream in https://github.com/wolfi-dev/os/pull/5079

Use node-problem-detector 0.8 stream

---

images/aws-for-fluent-bit/configs/latest.apko.yaml
images/fluentd/configs/latest.apko.yaml
images/newrelic/configs/latest.fluent-bit-output.apko.yaml

also add to aws-for-fluent-bit, fluentd, newrelic fluent-bit-output

---

images/go/README.md

Fix bad link in go readme

---

images/TEMPLATE/README.md
images/TEMPLATE/config/main.tf
images/TEMPLATE/config/template.apko.yaml
images/TEMPLATE/image.yaml
images/TEMPLATE/main.tf
images/TEMPLATE/tests/EXAMPLE_TEST.sh
images/TEMPLATE/tests/main.tf
lint.sh
monopod/pkg/images/images.go

add template directory to be used for new image configs

---

images/cluster-autoscaler/config/main.tf
images/cluster-autoscaler/config/template.apko.yaml
images/cluster-autoscaler/main.tf

This is a percursor to switching this package to track version streams.

Refactor `cluster-autoscaler` to latest/virtual pattern

---

images/php/config/fpm/main.tf
images/php/config/fpm/template.apko.yaml
images/php/config/main.tf
images/php/config/template.apko.yaml
images/php/fpm.tf
images/php/main.tf

This drops the version tags module.

Refactor the PHP image to track the latest virtual package.

---

images/redis/configs/latest.apko.yaml

adds the missing cli dependency introduced with: https://github.com/wolfi-dev/os/pull/5589

update redis packages to be consistent

---

images/istio/main.tf
images/istio/tests/main.tf
images/istio/tests/test-gateway.sh
images/istio/tests/test-injection.sh
images/istio/tests/virtualservice.yaml

- Test that the Helm charts are working
- Test that the sidecar injector / init container (iptable) are working
- Test that a simple VirtualService works

Add tests to Istio images

---

images/gatekeeper/config/main.tf
images/gatekeeper/config/template.apko.yaml
images/gatekeeper/main.tf
images/gatekeeper/tests/main.tf

Start to make the tests support multiple installations :crossed_fingers:

Refactor `gatekeeper` to track the virtual

---

.github/actions/release-image-terraform/action.yml

fix postsubmit TF_VAR_ check 

---

.github/actions/build-image-terraform/action.yml
.github/actions/generate-matrix/action.yml
.github/workflows/presubmit-build.yaml
.github/workflows/release.yaml

Fix warnings in presubmit-build

---

images/ingress-nginx-controller/tests/curl.yaml
images/ingress-nginx-controller/tests/httpbin.sh
images/ingress-nginx-controller/tests/httpbin.yaml
images/ingress-nginx-controller/tests/main.tf

Allow this test to be run with multiple versions side-by-side

ingress-nginx-controller test: namespace param

---

images/redis/main.tf

Dropping the version-tags module call as part of a re-work of the image builds. Any custom version builds are covered by version streams in images-private.

Removing 'version-tags' module dependency

---

images/fluentd/config/main.tf
images/fluentd/config/template.apko.yaml
images/fluentd/main.tf

Simply updating the terraform to meet the emerging pattern for the latest tags.

Move fluentd to latest pattern

---

images/fluentd/tests/01-test.sh
images/fluentd/tests/configs/basic_docker.conf
images/fluentd/tests/configs/basic_splunk.conf
images/fluentd/tests/splunk/01-test.sh

Encapsulate the fluentd test configs in the tests directory so it's all one unit

move the test configs for fluentd

---

images/external-dns/tests/e2e.sh

This reduces the dependency on ingress, as the CI cluster has no ingress installed by default.
(currently this test is passing because both ingress IP and the digged IP from the test dns are empty)

external-dns: don't use ingress in test

---

images/wavefront-proxy/configs/latest.apko.yaml

Adjust package list for the name update in https://github.com/wolfi-dev/os/pull/6115

chore(wavefront-proxy): update subpackage name to -compat

---

images/configmap-reload/config/template.apko.yaml

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

remove the package from config

---

.github/actions/build-image-terraform/action.yml
.github/actions/release-image-terraform/action.yml
.github/workflows/release.yaml

This gives us more control over the apko image used when this is called.

actions take apko image as input

---

images/ingress-nginx-controller/tests/backend.sh
images/ingress-nginx-controller/tests/backend.yaml
images/ingress-nginx-controller/tests/curl.yaml
images/ingress-nginx-controller/tests/main.tf

- Replace httpbin by podinfo image, which is 8x smaller
- Bump some wait time

More tunings to ingress-nginx tests

---

.github/actions/build-image-terraform/action.yml
.github/actions/release-image-terraform/action.yml
main.tf

This works around the pathological tfstate serialization performance when building lots of images.

Use inmem backend

---

images/flux/main.tf

previously, https://github.com/chainguard-images/images/pull/1462 and others

flux: add v prefix to version tags

---

main.tf
tflib/helm-cleanup/main.tf
tflib/publisher/main.tf
tflib/tagger/main.tf
tflib/version-tags/main.tf

This gives us better/earlier error messages on malformed and wrong-typed inputs, and IDE tooltips with helpful descriptions.

add types and descriptions to inputs

---

images/node/example/package-lock.json
images/node/example/package.json

https://github.com/chainguard-images/images/security/dependabot/1
https://github.com/chainguard-images/images/security/dependabot/2
https://github.com/chainguard-images/images/security/dependabot/5
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

update jsonwebtoken in example to address with known vuln

---

.github/workflows/release.yaml

Reverts chainguard-images/images#1409

Revert "bump release runner fanout to 4c runners"

---

images/external-dns/config/template.apko.yaml
tflib/publisher/main.tf

Bump tf-apko to v0.10.7

---

images/sigstore-scaffolding/tests/cosign-test.tf
images/sigstore-scaffolding/tests/rekor-test.tf

Give sigstore more than the default 1m deadline.

---

BEST_PRACTICES.md
TERRAFORM.md

Include a blurb on how to use `monopod scaffold` to create a new image structure from scratch.

docs: add information on monopod scaffold

---

images/smarter-device-manager/README.md

Minor docs update in helm example - setting the approperiate cgr image url

correcting image link in helm example

---

images/vault/configs/vault-k8s/main.tf
images/vault/configs/vault-k8s/template.apko.yaml
images/vault/configs/vault/main.tf
images/vault/configs/vault/template.apko.yaml
images/vault/main.tf
images/vault/vault-k8s.tf
images/vault/vault.tf

Drop version tags for `vault` and `vault-k8s` images.

Drop version tags for vault and vault-k8s

---

images/dynamic-localpv-provisioner/config/main.tf

It seems the job doesn't become healthy without it

Add busybox to dynamic localpv provisioner

---

images/cilium/tests/cilium-install.sh
images/cilium/tests/main.tf

Run more tests for cilium to ensure better coverage

cilium: run `cilium connectivity test` suite

---

images/nvidia-device-plugin/README.md
images/nvidia-device-plugin/config/latest.apko.yaml
images/nvidia-device-plugin/config/main.tf
images/nvidia-device-plugin/tests/README.md

Thanks to @k4leung4 for the manual testing steps.

fix: nvidia-device-plugin + manual steps taken for testing

---

images/fluent-bit/tests/main.tf

- add randon-pet suffix for fluent-bit tests
/kind failing-test

add randon-pet suffix for fluent-bit tests

---

images/cassandra/tests/main.tf

slack thread: https://chainguard-dev.slack.com/archives/C047DK5BUNP/p1698235366512269

order resource creation and add random variable

---

images/coredns/tests/main.tf

slack thread: https://chainguard-dev.slack.com/archives/C047DK5BUNP/p1698235366512269

update coredns helm tests

---

images/spire/config/main.tf
images/spire/main.tf

just some minor nits as suggested by @stormqueen1990 in #1694

adds minor nit fixes in spire image

---

withdrawn-repos.txt

I somehow missed this repo from my list in #1633

Withdraw `source-controller` repo

---

images/k3s/tests/smoke.sh

the `sleep 30` is silly and flakey
depends on https://github.com/wolfi-dev/os/pull/7907

make k3s tests slightly more flake resistent

---

images/argo/tests/check-argo-workflow.sh

The main thing is the `sleep 3`.
The other part is about not writing files to the current directory as a side effect.

argo: try to deflake test

---

images/prometheus-redis-exporter/tests/redis-installs.sh

If multiple copies of this test run simultaneously, they conflict on creating the deployment.
```
+ cat
+ kubectl apply -f deploy.yaml -n redis
namespace/redis unchanged
Error from server (AlreadyExists): error when creating "deploy.yaml": deployments.apps "redis" already exists
```

deconflict prom-redis test

---

images/dynamic-localpv-provisioner/main.tf
images/gradle/main.tf
images/http-echo/main.tf
images/ingress-nginx-controller/main.tf
images/nfs-subdir-external-provisioner/main.tf

These have been migrated elsewhere

drop some version-tags invocations

---

images/spire/tests/helm.sh
images/spire/tests/main.tf

This was testing using the upstream images, and Helm helpfully didn't tell us that we were passing values it didn't expect/understand!

fix indentation on spire helm test

---

images/tigera-operator/tests/helm.sh
images/tigera-operator/tests/main.tf
main.tf

This uses the technique used in #1863 and #1858 
This passed
```
terraform apply -target=module.tigera-operator -target=module.tigera-operator-again-for-testing -auto-approve
``

deconflict tigera-operator tests

---

images/kubeflow-katib/tests/smoke-test.sh

Update the kubeflow-katib tests to work with the latest version of the image.

fix: update kubeflow-katib tests for latest version

---

images/aspnet-runtime/config/main.tf

Upgrade to .net 8
Fixes https://github.com/chainguard-images/images/issues/1894

Update asp.net runtime image

---

images/fluent-bit/config/main.tf

This is adding the compat package to make this image compatible with upstream charts
Notes:
Notes:
Notes:
Notes:

added fluent-bit-compat

---

images/fluent-bit/config/main.tf
images/fluent-bit/config/template.apko.yaml

added fluent-bit-compat package

Fluent bit compat

---

images/temporal-server/config/main.tf

adds some more binaries needed for temporal server

---

images/temporal-admin-tools/config/main.tf

add tctl-authorization-plugin subpackage

---

images/busybox/alpine.tf
images/busybox/wolfi.tf
images/git/alpine.tf
images/git/wolfi.tf
images/static/alpine.tf
images/static/wolfi.tf
tflib/publisher/main.tf

I expect this to fail some places, but let's see how bad it is...

Upgrade publisher to run NTIA conformance checker.

---

images/postgres/tests/tls.sh

ref: https://github.com/chainguard-images/images/pull/1959

deconflict postgres even harder x2

---

images/kubeflow-pipelines/main.tf

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

latest and latest-dev only

---

images/k8s-sidecar/tests/02-smoke.sh
images/k8s-sidecar/tests/main.tf

Just a basic smoke test so ignored the PR template here.

k8s-sidecar: add smoke test

---

images/k8s-sidecar/config/template.apko.yaml

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

refactor k8s-sidecar  for referential usage

---

withdrawn-repos.txt

Pull information to me indicates this image is only pulled by our vulnerability automation:
```
c	repository	d
80	chainguard/kyverno-policy-reporter-reporter	2023-12-28
80	chainguard/kyverno-policy-reporter-reporter	2023-12-27
80	chainguard/kyverno-policy-reporter-reporter	2023-12-26
80	chainguard/kyverno-policy-reporter-reporter	2023-12-25
80	chainguard/kyverno-policy-reporter-reporter	2023-12-24
80	chainguard/kyverno-policy-reporter-reporter	2023-12-23
98	chainguard/kyverno-policy-reporter-reporter	2023-12-22
49	chainguard/kyverno-policy-reporter-reporter	2023-12-21
68	chainguard/kyverno-policy-reporter-reporter	2023-12-20
62	chainguard/kyverno-policy-reporter-reporter	2023-12-19
70	chainguard/kyverno-policy-reporter-reporter	2023-12-18
62	chainguard/kyverno-policy-reporter-reporter …
```

Withdraw `kyverno-policy-reporter-reporter`

---

images/calico/main.tf

We aren't tagging public images with version tags, so just drop the version tags stuff entirely. Images will only be tagged with `:latest`, and users will have to figure out what version they actually are (from the SBOM, likely) to be able to tag them for use with operators.

calico: remove public version tags

---

images/aws-cli/config/latest.apko.yaml
images/aws-cli/config/main.tf
images/aws-cli/main.tf

Small tweaks to the aws-cli terraform module to bring it in line with the latest design for others.

Update AWS CLI terraform module

---

images/ruby/config/main.tf
images/ruby/main.tf

```
$ docker run gcr.io/my-project/ruby:latest --version
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [aarch64-linux-gnu]
```

ruby: build ruby-3.3

---

.github/workflows/release.yaml

Reverts chainguard-images/images#2005

Revert "shard release workflow"

---

images/argo/cli.tf
images/argo/exec.tf
images/argo/workflowcontroller.tf

Argo is my canary for `-dev` variants

Enable NTIA checking for Argo

---

images/curl/main.tf

Seems like a useful and frequent enough combo to include in at least the dev image.

curl: Add jq to dev image.

---

.github/workflows/release.yaml

Reverts chainguard-images/images#2038

Revert "Revert "shard release workflow""

---

images/external-dns/tests/e2e.sh

Check for the correct deployment and service names in the ExternalDNS end-to-end tests. It appears that the Helm chart for CoreDNS has changed to not append `coredns-` as a prefix anymore. As a result, because the shell script sets both `errexit` and `pipefail`, the whole test fails because the cluster objects are not found.
Failure reference: https://github.com/chainguard-images/images/actions/runs/7403832379/job/20144715099#step:12:107

fix: check for correct names in ExternalDNS tests

---

images/python/README.md

- [ x ] A README file has been provided and it follows the README template.

Latest is now 3.12

---

.github/actions/generate-matrix/action.yml
.github/actions/verify-readme/action.yml
.github/workflows/digestabot.yaml
.github/workflows/presubmit-build.yaml
.github/workflows/presubmit-readme.yaml
.github/workflows/release.yaml
.github/workflows/withdraw-images.yaml
.github/workflows/withdraw-repos.yaml

`s/tags/digests` for all actions and workflows

pin to shas for actions and workflows

---

main.tf
tflib/publisher/chainguard.tf
tflib/publisher/main.tf

A collab with the inimitable @jdolitsky

update Chainguard repo metadata with readme contents

---

images/redis-bitnami/tests/main.tf

https://github.com/bitnami/charts/pull/22223

add workaround for redis-bitnami helm chart bustage

---

images/gitlab/tests/main.tf

make this chart just a little less massive.
this won't pass until https://github.com/wolfi-dev/os/pull/11712

minify the gitlab charts just a bit more

---

images/kubernetes-event-exporter/tests/logs.sh

https://github.com/chainguard-images/images/actions/runs/7640386534/job/20815953387#step:11:1309

somebody uses vim!

---

BEST_PRACTICES.md

I had to find the content of this configuration file recently. I decided to add it here, but we can move it around!

Best practices: Add section showing how to configure grype

---

images/cassandra-reaper/tests/smoke-test.sh

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

remove stargate from CRD to prevent its being deployed

---

.chainguard/source.yaml
.github/workflows/digestabot.yaml

- udpate digestabot action to its new home and update chainguard source

udpate digestabot action to its new home and update chainguard source

---

images/kubeflow/README.md

Fixes an external link in kubeflow's README.

Fix: Kubeflow README repo link

---

images/aws-for-fluent-bit/config/main.tf
images/fluent-bit/config/template.apko.yaml
images/fluentd/config/main.tf
images/kube-logging-operator-fluentd/config/main.tf
images/newrelic-fluent-bit-output/config/template.apko.yaml

upgrade from libpq-11 -> libpq-15

---

images/http-echo/config/main.tf

https://github.com/wolfi-dev/os/commit/614ec8c6d677f356f9df57c415115cdda898e4d3#diff-472ad29c9849dd6524308ef03cfd1eb296a61c1eb0478cb0fbecacdff9dbf449

Fix http-echo entrypoint

---

images/temporal-server/tests/helm.sh

https://github.com/temporalio/helm-charts/commit/82c9dfa2af992f924164a3786683d82fde4c1708

Fix temporal helm charts location in tests

---

images/minio/config/main.tf

Set permissions for `/data/.minio.sys/*`.

minio: pass permissions for paths

---

images/spark-operator/README.md
images/spark-operator/config/main.tf
images/spark-operator/metadata.hcl
images/spark-operator/metadata.yaml
images/spark-operator/tests/main.tf
images/spark-operator/tests/test-spark-job.sh
images/spark-operator/tests/test-spark.sh

The Spark operator has a dependency on spark. This PR adds the apache spark package to spark-operator. Also extended some testing.

Add Apache spark (dependency), and adding tests

---

tflib/imagetest/helm/README.md
tflib/imagetest/helm/main.tf

The imagetest helm module doesn't have a way to reference local charts and values files. Just adding that capability here

Reference local values and chart with helm module

---

images/kafka/config/main.tf

Corrects access to subdirectories

fix(kafka): Make user permissions recursive

---

images/prometheus-logstash-exporter/tests/main.tf

Use the new retry capability for talking to the prometheus API!

Add retry to prometheus-logstash-exporter test

---

images/opensearch/config/main.tf
images/opensearch/config/template.apko.yaml

Some refactors to remove conflict of packages

refactors opensearch

---

tflib/publisher/check-reproducibility.sh

attempt to fix the reproducibility test errors occurring  in a handful of images

bump apko reproducibility image

---

images/opensearch/config/template.apko.yaml

Taking a crack at getting opensearch functional with the upstream chart

WIP: Make opensearch deployable with upstream chart

---

images/spire/config/main.tf

Update the description since the PR was already open.

chore: update description

---

images/cassandra/config/main.tf

Support passing in environment variables

Support passing in environment variables

---

images/temporal-server/tests/helm.sh
images/temporal-server/tests/main.tf

Fix the `temporal-server` tests so they don't timeout anymore.

fix(temporal-server): update tests

---

TERRAFORM.md

add usage docs for the `imagetest` provider.
also refresh the testing section to talk more about `oci_exec_test`

add docs for testing with imagetest

---

images/loki/tests/main.tf

the existing tests are flakey on cleanup, so migrate to `imagetest` where cleanup is guaranteed

migrate loki to imagetest

---

images/crossplane/tests/install/main.tf
images/crossplane/tests/main.tf

see #2224 .
I'm splitting this up into chunks to avoid the presubmit disk space

migrate crossplane to imagetest

---

images/crossplane-azure/tests/install.sh
images/crossplane-azure/tests/main.tf

follow on to #2225, split from #2224

migrate crossplane-azure to imagetest

---

.gitignore
.terraform.lock.hcl

https://developer.hashicorp.com/terraform/language/files/dependency-lock
Checking this in ensures that the providers/modules used don't change unexpectedly.

check in .terraform.lock.hcl

---

images/opensearch/config/main.tf
images/opensearch/config/template.apko.yaml

moves jdk 17 to extra package for easier referencing

moves jdk 17 to extra package in opensearch

---

images/opensearch/config/main.tf
images/opensearch/config/template.apko.yaml

moves these additional plugins to extra package for easier referencing

moves plugins to extra package in opensearch

---

.terraform.lock.hcl
images/opensearch-dashboards/README.md
images/opensearch-dashboards/config/main.tf
images/opensearch-dashboards/config/template.apko.yaml
images/opensearch-dashboards/main.tf
images/opensearch-dashboards/metadata.yaml
images/opensearch-dashboards/tests/main.tf
main.tf

Notes:
Notes:
Being investigated and advisories will be created.  @pdeslaur is taking a look.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes: 
Notes:
Notes:
Notes:

opensearch-dashboards: new image

---

images/pytorch/README.md
images/pytorch/metadata.yaml

Few minor README tweaks for pytorch

Few minor README tweaks 

---

images/spark-operator/tests/test-spark.sh
withdrawn-images.txt
withdrawn-repos.txt

Withdraw renamed repo. Also removing image versions added to withdrawn images, as we're removing the whole repo.

withdraw remamed repo

---

images/kubernetes-dns-node-cache/tests/main.tf

Convert k8s-dns-node-cache tests to use imagetest

---

images/nemo/metadata.yaml

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

Removing keywords from metadata.yaml

---

images/helm-operator/tests/main.tf

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

update chart path

---

images/k8ssandra-operator/tests/main.tf

k8ssandra-operator uses cert-manager which is causing test flakes

Migrate k8ssandra-operator tests to imagetest

---

images/docker-selenium/README.md

Adds a usage section to the README

docs(docker-selenium): Cover usage in README

---

.github/workflows/digestabot.yaml
.github/workflows/presubmit-build.yaml
.github/workflows/presubmit-readme.yaml
.github/workflows/release.yaml
.github/workflows/withdraw-images.yaml
.github/workflows/withdraw-repos.yaml

Adding Harden Runner audit configs for images workflows

Add Harden Runner audit configs

---

.github/workflows/presubmit-build.yaml

add the audit job to the actual build

---

images/helm-operator/tests/main.tf

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

replace imagetests with ref to package smoke test

---

images/dask-gateway/config/main.tf

Adds extra packages variable so that other images may install additional packages.

chore(dask-gateway): Allow passing extra packages to config

---

images/spark-operator/metadata.yaml
images/spark-operator/tests/main.tf

Migrate the tests to use imagetest and update the address for the upstream chart.

fix(spark-operator): use new address for upstream chart

---

images/memcached/tests/main.tf

Migrate `memcached` tests into imagetest.

chore(memcached): migrate to imagetest

---

withdrawn-repos.txt

https://github.com/chainguard-images/images/pull/2376

withdraw slim-toolkit-debug

---

images/confluent-kafka/config/main.tf

Moved these packages to runtime dep: https://github.com/wolfi-dev/os/pull/15749

confluent-kafka: remove busybox and openjdk-17

---

images/velero-plugin-for-aws/tests/docker-test.sh

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

correct the init container name for velero-plugin-for-aws

---

images/kube-webhook-certgen/README.md
images/kube-webhook-certgen/config/main.tf
images/kube-webhook-certgen/config/template.apko.yaml
images/kube-webhook-certgen/main.tf
images/kube-webhook-certgen/metadata.yaml
images/kube-webhook-certgen/tests/main.tf
main.tf

add new image: `kube-webhook-certgen`

add kube-webhook-certgen image

---

images/postgres-operator/tests/main.tf

Refactors postgres-operator tests to use imagetests

refactors postgres-operator tests to image tests

---

images/docker-cli/README.md
images/docker-cli/config/main.tf
images/docker-cli/config/template.apko.yaml
images/docker-cli/main.tf
images/docker-cli/metadata.yaml
images/docker-cli/tests/01-version.sh
images/docker-cli/tests/main.tf
main.tf

New image for Docker CLI based off Wolfi.

feat: new `docker-cli` image

---

images/squid-proxy/metadata.yaml

Small follow up to #2421 for fixing keyword validation

fixes squid-proxy keywords for string validation

---

.github/workflows/presubmit-build.yaml
images/crane/tests/main.tf

An attempt to fix https://github.com/chainguard-dev/actions/issues/416

WIP: don't use workflow-conclusion-action

---

images/pytorch-cuda12/README.md

Update to the pytorch-cuda image README for capitalization, spelling, repeated words.

Small edits for spelling, repeated word, capitalization in pytorch-cuda README

---

images/external-secrets/tests/main.tf

Migrate script tests to the new Docker harness

chore(external-secrets): migrate to Docker harness

---

images/rabbitmq/tests/02-perf.sh

Forgot to randomize the host port

Deflake rabbitmq test even more

---

images/melange/README.md

Fixes an issue with a link being unreachable in docs and directory.

Melange: Fix README link

---

images/sigstore-scaffolding/README.md

Fixes a broken link on edu and directory.

sigstore-scaffolding: Fix README link

---

images/weaviate/README.md

Add helm instructions to weaviate docs.

---

withdrawn-repos.txt

As discussed with @pdeslaur, we decided to withdraw this repo

withdrawn our sdk repo

---

images/kubernetes-csi-external-snapshot-validation-webhook/tests/deploy.sh
images/kubernetes-csi-external-snapshot-validation-webhook/tests/main.tf
images/minio/tests/main.tf
images/minio/tests/test.sh
images/nats/tests/healthy.sh
images/nats/tests/main.tf
images/nats/tests/works.sh

migrate more of the long timeout offenders to imagetest

migrate to imagetest

---

images/falco-no-driver/README.md

Update to helm installation instruction in README.md

Update helm installation instruction

---

images/pytorch-cuda12/TESTING.md

Fixed and updated instance creation command
Added step-by-step instructions
Added more test commands
Added links to resources
Resolves #2328
This is a documentation-only update.

Update and additions to pytorch-cuda12 testing instructions

---

images/cassandra-medusa/tests/medusa-install.sh

Related PR: https://github.com/wolfi-dev/os/pull/17569
Expand medua test coverage, and remove resource cleanup, which is not needed when using our new test harnes.

Expand medusa test coverage, remove resource cleanup

---

images/nemo/README.md
images/nemo/tests/nemo_quickstart.py
tts.py

Updates the image overview and test scripts for NVIDIA NeMo. Adds a new script, tts.py, that will be used as the example script for now. Refactored and added missing nemo_quickstart.py script, but issues may need to be resolved before it can be used as the example script for this image.
Added TTS example (tts.py) as current example script
Added missing nemo_quickstart.py code (requires more deps to run)
Added GPU testing section
Added test script command
Added resources
Changed description to a more technical description
This PR is related to docs and test scripts only.
References https://github.com/chainguard-dev/internal/issues/3393
References https://github.com/chainguard-dev/internal/issues/3749

Updated NeMo overview, test scripts

---

images/opensearch-dashboards/tests/main.tf

Same change as https://github.com/chainguard-images/images/pull/2394

opensearch-dashboards: Fix release

---

images/cassandra-medusa/tests/medusa-install.sh

We recently moved over to the k3d test harness. The k8ssandra-operator deploys stargate but it's not utilised in this particular test. 
However it was failing to launch due to pod anti-infinity rules, because our test harness runs everything on the master node (as of today). Small tweak to fix this, and also add a check to wait for stargate to be ready

Fix issue with stargate not running on single node cluster

---

images/cassandra-medusa/tests/medusa-install.sh

Print useful info whenever a failure occurs, fix namespace in cmd

Print useful info whenever a failure occurs, fix namespace

---

images/node-lts/generated.tf
images/node-lts/main.tf

Fix nodejs-lts using versions

---

images/argocd/tests/main.tf
images/k8ssandra-operator/tests/main.tf

Some of these test harness names don't match

update test harness names to match

---

images/rust/generated.tf
images/rust/main.tf

Make rust version stream aware.

Add version streams to rust.

---

images/keda/main.tf

Tried to be too clever here, it needs to be "keda"

Fix keda versions

---

images/jitsucom-bulker/main.tf
withdrawn-images.txt

* rename `jitsucom-bulker-{component}` to `jitsucom-{component}`
* withdraw `jitsucom-bulker-{component}`

rename jitsucom-bulker repo to jitsucom

---

images/kube-vip/tests/check-kube-vip.sh

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

use different namespace for each time

---

images/vertical-pod-autoscaler/tests/main.tf

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

use imagetest_harness to avoid conflicts

---

images/kube-vip/tests/check-kube-vip.sh

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

delete resources after tests passed

---

images/crane/main.tf
images/fluent-bit-plugin-loki/tests/main.tf
images/grafana-rollout-operator/tests/main.tf
images/ko/main.tf

Also set main_package for crane and ko.

remove some more uses of oci_string

---

images/keycloak-operator/tests/keycloak-test.sh

This PR covers end to end operation of keycloak operator ensuring further coverage of tests and also handles functionality of test of realm import which is a great addition to avoid issues in future where keycloak-realm import was missed

adds increased coverage test for keycloak-operator 

---

images/apache-nifi/TESTING.md
images/apache-nifi/tests/check-nifi.sh
images/apache-nifi/tests/main.tf

Adds a test that creates a processor in the root process group using NiFi's API

chore(apache-nifi): Add functional API test

---

images/postgres-helm-compat/main.tf

Previously, this was pinned to PostgreSQL 15. Build with the latest release from here on out

fix(postgres-helm-compat): Build with the latest version of PostgreSQL

---

images/kube-webhook-certgen/README.md
images/kube-webhook-certgen/metadata.yaml
images/kube-webhook-certgen/tests/main.tf
images/kube-webhook-certgen/tests/run-tests.sh

Improve docs and add some test coverage

Improve docs and add some test coverage

---

images/datadog-agent/config/agent/latest.apko.yaml

depends on https://github.com/wolfi-dev/os/pull/19608

reference the appropriate PYTHONPATH

---

images/cassandra/README.md
images/cassandra/tests/main.tf
images/cassandra/tests/run-tests.sh

Add functional Cassandra test, and expand README

Expand testing and docs

---

images/kyverno/tests/main.tf

Use the cgr busybox image for the kyverno helm test

Use cgr busybox for kyverno test

---

images/kubernetes-dashboard/tests/main.tf

Migrate kubernetes-dashboard to imagetest

---

images/thanos-operator/tests/main.tf

Help with some conflicting resources

Migrate thanos-operator to imagetest

---

images/memcached-exporter-bitnami/tests/main.tf

Migrate the memcached-exporter-bitnami tests to imagetest and fix the values

migrate and fix memcached-exporter-bitnami tests

---

images/calico/configs/latest.key-cert-provisioner.apko.yaml
images/calico/configs/main.tf
images/calico/main.tf
images/calico/tests/main.tf

depends on https://github.com/wolfi-dev/os/pull/20479

add key-cert-provisioner

---

images/TEMPLATE/tests/main.tf

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

replace console with TODO

---

images/dex/config/main.tf
images/dex/config/template.apko.yaml

this allows freedom to add another gomplate package.

dex: Move gomplate to extra_packages

---

images/prometheus-cloudwatch-exporter/tests/main.tf
images/prometheus-node-exporter/tests/main.tf

migrate node-exporters to imagetest

---

images/atlantis/config/main.tf

This should pull in git-lfs-fips where needed.

Add suffix to git-lfs for atlantis.

---

.github/workflows/release.yaml

#2784 works, do it for post-submit too

print per-image plan in postsubmit

---

.github/workflows/presubmit-build.yaml
.github/workflows/release.yaml

Planning for each image seems to take a _lot_ longer 😭

plan once before apply

---

images/nvidia-gpu-driver/config/main.tf
images/nvidia-gpu-driver/generated.tf
images/nvidia-gpu-driver/main.tf

fixes tags and disables sbom in nvidia-gpu-driver for now

fixes tags and disables sboms for now in nvidia-gpu-driver

---

images/postgres/tests/query.sh
images/postgres/tests/tls.sh

Some expansions to our postgres automated tests

Expanding postgres tests

---

images/kyverno/config/main.tf

kyverno: use extra-packages for kubectl

---

.github/workflows/digestabot.yaml

Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:

Update digestabot.yaml add commiter/author

---

.github/workflows/withdraw-images.yaml
.github/workflows/withdraw-repos.yaml

Erroneously removed in https://github.com/chainguard-images/images/pull/2816

reinstate public withdraw workflows

---

.github/workflows/release.yaml

stepping down a half size on the runners, and effectively 1.5x'ing the shards.

wider fanout on smaller runners

---

withdrawn-repos.txt

Unwithdraw pytorch

---

.github/workflows/presubmit-readme.yaml
.github/workflows/reinstate-images.yaml
.github/workflows/release.yaml

follow up to https://github.com/chainguard-images/images/pull/2933

Fix bug in reinstate-images.yaml, hand over ownership to automation

---

.github/workflows/release.yaml

45 images, so just pick 40 shards for now. also randomize the sharder so one bad image doesn't consistently block

barely less than n_images
