- .github/workflows/presubmit-readme.yaml
- .github/workflows/release.yaml
there is the job `https://github.com/chainguard-images/images/blob/main/.github/workflows/presubmit-readme.yaml` that runs on PRs and inject the secret, but that will not run on Forked PRs caused the job to fail because the secret will not be injected.
we have the bucket name public and there is not needed to have that in a secret.
We can delete the secret after this PR is merged
Slack 🧵 : https://chainguard-dev.slack.com/archives/C0322APD4LU/p1670235759571799
> dont use bucket name as secret

- images/php/README.md
- images/php/configs/latest-dev.apko.yaml
- images/php/configs/latest-glibc-dev.apko.yaml
- images/php/configs/latest-glibc.apko.yaml
- images/php/configs/latest.apko.yaml
This PR brings a few changes to make the PHP images more flexible for end users, facilitating the installation of userland dependencies via Composer both for development as well as for production runtimes.
**WIP**
> Improvements to PHP image

- .github/workflows/release.yaml
Right now we only do all images for scheduled jobs, but workflow dispatch needs that as well.
> Add 'workflow_dispatch' support to the generate matrix step.

- .github/workflows/release.yaml
> stagger release pushes up to 2 minutes, to avoid rate limits

- images/ruby/configs/latest-3.0.apko.yaml
- images/ruby/configs/latest-3.1.apko.yaml
- images/ruby/configs/latest-3.2.apko.yaml
This matches the `ruby` image on Dockerhub:
```
$ docker run --rm -it ruby
irb(main):001:0>
```
and now, with this change:
```
$ docker run --rm -it image.tar
irb(main):001:0>
```
> ruby: use irb as entrypoint

- images/apko/configs/latest.apko.yaml
- images/sdk/configs/latest.apko.yaml
These are needed in order to be able to pull alpine packages, like we do when bootstrapping wolfi.
> add alpine-keys to sdk+apko images

- images/rabbitmq/configs/latest.apko.yaml
Signed-off-by: Dan Lorenc <dlorenc@chainguard.dev>
> Fix enivronment variable and directory permissions for rabbitmq image.

- .github/workflows/release.yaml
Introduced bug in #225 , "generate-matrix-schedule" step name was duplicated, causing:
```
The workflow is not valid. .github/workflows/release.yaml (Line: 30, Col: 11): The identifier 'generate-matrix-schedule' may not be used more than once within the same scope.
```
> Fix duplicate release step name

- images/curl/configs/latest.apko.yaml
I think this is the right way to force curl to select the rustls backend.
Signed-off-by: Dan Lorenc <dlorenc@chainguard.dev>
> Rust-ify the curl image!

- images/python/README.md
Fixed documentation to include the correct name of the image tag for python dev. Tried to fix it in the edu repo in https://github.com/chainguard-dev/edu/pull/317. But it is generated from this README
The tag for the dev version of the python image is called `latest-dev` not `dev-latest`
If a user tries to pull `cgr.dev/chainguard/python:dev-latest` it will not work.
-
-
> Fixed typo in python image docs

- images/node/configs/latest.apko.yaml
This PR adds an ENV variable setting `NPM_CONFIG_UPDATE_NOTIFIER` to `false` to stop the update notifications that show up when running `npm install`.
Tested with a local apko build.
> Adding env var to suppress npm update notification

- images/mariadb/README.md
This PR adds information about ENV variables and how to use them to set up a database and user upon initialization. Relates to https://github.com/chainguard-dev/edu/issues/343
> Adding information about env variables to MariaDB Readme

- .github/actions/release-image/action.yml
This drops dependency on the upstream grype/trivy installer actions
> Switch from chainguard-images/actions/vul-scan to chainguard-dev/rumble

- images/traefik/tests/01-version.sh
Resolves #265
Actually the traefik image is now working after https://github.com/chainguard-dev/melange/issues/281 was fixed, the issue above should be closed too. This just adds a test to prevent further regression.
> Add real test for traefik image

- .github/ISSUE_TEMPLATE/external-bug-or-feedback.yml
for bugs so that we get the 'needs-triage' label applied to non image requests
> add issue template 

- images/traefik/README.md
:bug: It mixes `toml` and `yaml`.
/kind bug
> Fix: Typo in traefik configuration

- .github/actions/image-summary/action.yml
- use cosign-installer v3 instead of main
annotations:
> use cosign-installer v3 instead of main

- README.md
- images/bash/README.md
- images/bash/configs/latest.apko.yaml
- images/bash/image.yaml
- images/bash/tests/01-runs.sh
Fixes: 
Related: 
annotations:
> Add a bash image.

- policies/02-has-vuln-attestation.yaml
Fixes: Now that we are attesting vuln scans with cosign 2.0, the policy is invalid since predicate types must now be RFC3986-compliant (start with `https://`)
Related: https://github.com/sigstore/policy-controller/issues/608
annotations:
> Switch policy to use RFC3986-compliant predicate type

- .github/actions/policy-check-image/action.yml
Fixes: 
Related: https://github.com/wolfi-dev/os/pull/713
annotations:
> Fix policy-check to use latest apko

- images/jdk/README.md
- images/jre/README.md
- images/maven/README.md
Fixes: 
Related: 
annotations:
PTAL @rawlingsj
> fix jre tag

- images/postgres/configs/latest.apko.yaml
The permissions are read as uint32, so it needs to be an octal. Every other file has `0o777` or similar, but Postgres has just 777, which breaks things. This fixes it.
> fix permissions on postgres image

- images/php/README.md
- images/php/configs/latest-dev.apko.yaml
This PR updates the `latest-dev` variant of the PHP image to include `apk-tools`, as discussed in a few different occasions by the team. Instead of just including apk-tools directly, I used the wolfi-base package that already comes with apk-tools and busybox.
> Updating php dev variant to include apk-tools

- images/prometheus-alertmanager/configs/latest.apko.yaml
- images/prometheus-mysqld-exporter/configs/latest.apko.yaml
Fixes:
Related: 
```
annotations:
```
> Add aarch64 for prometheus-alertmanager, prometheus-mysqld-exporter

- images/nginx/tests/02-welcome-page.sh
Fixes:
Related: 
```
annotations:
```
> Add sleep to nginx test to wait for container to start

- images/haproxy/configs/latest.apko.yaml
Fixes: #308 
Related: 
```
annotations:
```
> Add dataplaneapi to haproxy image

- .github/actions/build-image/action.yml
- .github/actions/release-image/action.yml
Potential fix for the following issue if a config does not have a trailing newline:
```
Error: failed to load image configuration: failed to parse image configuration: yaml: unmarshal errors:
line 31: cannot unmarshal !!map into string
2023/03/15 10:32:41 error during command execution: failed to load image configuration: failed to parse image configuration: yaml: unmarshal errors:
```
Fixes: Bug introduced in #340
Related: #187
```
annotations: …
```
> Fix for configs missing trailing newline

- .github/actions/image-summary/action.yml
Fixes:
Related: 
```
annotations:
```
> Bad ending in for loop (fi vs done oof)

- .github/actions/release-image/action.yml
:gift: This change adds setup-chainctl to start authenticating with our registry.
A subsequent change will start to take advantage of this, but we want to try authenticating as the first baby step.
/kind feature
> Feature: Start to authenticate with Chainguard registry.

- .github/actions/policy-check-image/action.yml
Bug introduced in https://github.com/chainguard-images/images/pull/340 with the addition of `globals.yaml`:
```
$ echo find policies -name *.yaml
find policies -name globals.yaml
```
> Fix bad find command in policy-check-image action

- .github/actions/release-image/action.yml
Fixes errors like https://github.com/chainguard-images/images/actions/runs/4491737796/jobs/7900630278
> fix: set shell:bash for cgr login step

- .github/actions/release-image/action.yml
:broom: This cleans up the extra bit of config we had now that `cgr.dev` is the default domain in `chainctl`.
/kind cleanup
```
annotations:
```
> Cleanup: Drop the extra config, `cgr.dev` is not default

- .github/workflows/release.yaml
As we have more and more images with multiple architectures and with more and more attachments (SBOM attestations, etc.), we're seeing https://github.com/chainguard-images/images/issues/173 more and more. Basically regularly daily, requiring manual retries.
Bumping the 2-minute random sleep to 10-minutes should fix it. 🤞 
We can remove these sleeps when we only push to cgr.dev.
> randomly sleep up to 10 mins to avoid ghcr rate limits

- .github/actions/release-image/action.yml
relies on https://github.com/chainguard-images/actions/pull/98
> Pass generic credentials into apko publish

- images/nginx/configs/latest.apko.yaml
- images/nginx/tests/03-shutdown.sh
Our nginx image was doing a "fast" shutdown. By sending it the SIGQUIT signal instead of SIGTERM, it will do a graceful shutdown.
To achieve this:
- removed s6 entrypoint
- added stop-signal support to give nginx SIGQUIT signal
- added tests to ensure graceful exit
Fixes: #403 
Related: 
```
annotations:
```
> Configure graceful shutdown of NGINX image

- globals.yaml
- images/static/README.md
- images/static/image.yaml
- monopod/pkg/commands/readme.go
- monopod/pkg/images/images.go
- allow excluding Chainguard contact text in README (static) Replaces #412 
- enable top-level build options for variants
> Add chainguard global option, specify wolfi-baselayout where missing

- .github/workflows/presubmit-build-melange.yaml
- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
Resolves #204 (hopefully)
Should also help to prevent the following actions warnings:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
> Switch from jitterbit/get-changed-files to tj-actions/changed-files

- .github/workflows/presubmit-build-melange.yaml
- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
This was causing builds to build everything vs. just what changed. Issue introduced in https://github.com/chainguard-images/images/pull/425
> Fix to use correct changed files output name

- images/jdk/configs/latest.apko.yaml
- images/jdk/configs/openjdk-11.apko.yaml
- images/jre/configs/latest.apko.yaml
- images/jre/configs/openjdk-11.apko.yaml
Adds `libstdc++` to jvm based images to allow usage of libraries and profilers
which require it.
Fixes: #422
Related:
> Add libstdc++ to jvm based images (jre, jdk)

- .github/workflows/k8s-tests.yaml
- .github/workflows/presubmit-k8s-tests.yaml
Update k8s CI to expose registry/repository/tag variables for test scripts.
> Add environment variables to k8s CI

- images/ruby/configs/3.0.apko.yaml
- images/ruby/configs/3.1.apko.yaml
- images/ruby/configs/latest.apko.yaml
- images/ruby/tests/01-version.sh
This PR updates the entrypoint for Ruby images to use `/usr/bin/ruby` with the default command set to `--version`.
The current entry point is set to the interactive ruby tool `irb`, resulting in odd behavior when you try to run Ruby scripts directly via `docker run`. This change was discussed in an [internal Slack thread](https://chainguard-dev.slack.com/archives/C0322APD4LU/p1681480063454969).
With the update, it is possible to execute a Ruby script with:
```shell
docker run --rm -v ${PWD}:/work cgr.dev/chainguard/ruby:latest script.rb
```
> Updated ruby entrypoint and command

- images/node/image.yaml
I test a few popular node.js app and it seems `make` used quite a lot. so i'm replacing gcc with build-base.
these pkg will be used when node.sj falls back to installing native modules from source.
Fixes:
Related: 
```
annotations:
```
> node image: Replace gcc with build-base

- .github/actions/image-summary/action.yml
Currently when you see a red badge because a build fails, it will get cached and show up for an hour even if it passed on retry.
Badges are small and presumably don't contribute a lot to egress or page load time. If we decide we want to cache these we could at least make them cached for a shorter time like 5-10 minutes.
> configure GCS not to cache image summary badges+JSON

- images/opensearch/configs/latest.apko.yaml
the JAVA_HOME location for Java 11 JRE has moved to /usr/lib/jvm/openjdk.
> opensearch: fix JAVA_HOME location

- images/wait-for-it/configs/latest.apko.yaml
:broom: This changes the `wait-for-it` image to run as non-root by default for a better security posture.
There isn't a strong reason that this should need `root`.
/kind broom
> Cleanup: Have `wait-for-it` run as non-root

- images/graalvm-native/configs/latest.apko.yaml
Quarkus requires `libstdc++.so` at runtime.
eg: https://github.com/quarkusio/quarkus-images/issues/61
```
annotations:
```
> graalvm-native: add libstdc++-dev as runtime dep

- images/nginx/README.md
- images/nginx/configs/next.apko.yaml
This PR updates the nginx README to warn of the [upcoming change](https://github.com/chainguard-images/images/pull/478).
It also includes the new version as a variant so that people can test.
> Warning for upcoming breaking changes to NGINX image

- .github/actions/image-summary/action.yml
follow up to #492
Please do not merge until `--group` flag available!
> Use --group option for updating tier (vs. extracting id)

- images/gradle/configs/latest.apko.yaml
Fixes: https://github.com/chainguard-images/images/actions/runs/4835767823/jobs/8618374679
> Fix: add jdk and JAVA_HOME to gradle image

- images/nginx/configs/next.apko.yaml
We want to be able to run nginx with:
```
docker run --read-only --tmpfs /var/lib/nginx/tmp/ --tmpfs /var/run -p 8080:8080 cgr.dev/chainguard/nginx:next
```
But it currently fails with permission errors.
The problem seems to be that `--tmpfs` does not set permissions correctly even when run with the `tmpfs-mode` option e.g: `--mount type=tmpfs,destination=/var/lib/nginx/tmp/,tmpfs-mode=777`. Probably related to https://github.com/moby/moby/issues/40881.
Related: https://github.com/chainguard-images/images/issues/288
This is *not* a breaking change (permissions are being relaxed).
> Modified permissions on directories to support tmpfs.

- BEST_PRACTICES.md
- images/busybox/tests/01-runs.sh
- images/go/tests/01-version.sh
- images/static/examples/Dockerfile.c
- images/static/examples/Dockerfile.golang
- images/static/examples/Dockerfile.rust
- images/wolfi-base/tests/01-runs.sh
- document apko's default env behavior in BEST_PRACTICES.md (more on this in a future PR; for now just docs)
- add tests for the default user
- add tests for other ways of calling the executable in a container
- add tests that images can be used as base images (in a couple forms)
- update `static`'s dockerfile tests to match common practice
Related: #515
> add more tests for static,busybox,wolfi-base,go

- images/secrets-store-csi-driver-provider-gcp/configs/latest.apko.yaml
- images/secrets-store-csi-driver/configs/latest.apko.yaml
These images require root to be able to connect to CSI infrastructure over sockets.
Without it, `CrashLoopBackoff`:
```
"failed to listen" err="listen unix //csi/csi.sock: bind: permission denied" proto="unix" address="//csi/csi.sock"
```
and 
```
err: "listen unix /etc/kubernetes/secrets-store-csi-providers/gcp.sock: bind: permission denied"
```
The upstream images run as root:
```
$ docker run --entrypoint sh k8s.gcr.io/csi-secrets-store/driver:v1.3.2 -c whoami
root
```
```
$ crane config us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-gcp/plugin:v1.2.0 | jq .config.User
"0"
```
Configuring these images to run as root and using them in the build cluster caused the daemonsets to come up again.
This was discovered while trying to dogfood the images in our own arm64 …
> run secrets-store CSI driver images as root

- .github/workflows/presubmit-build-melange.yaml
- .github/workflows/presubmit-build.yaml
- .github/workflows/presubmit-k8s-tests.yaml
- .github/workflows/presubmit-readme.yaml
- update presubmt job to aggregate the result and be able to have one required check
same changes applied in the other repository and did a small format to match
Fixes: n/a
Related: 
```
annotations:
```
> update presubmt job to aggregate the result and be able to have one required check

- .github/actions/build-image/action.yml
- .github/actions/policy-check-image/action.yml
- .github/actions/release-image/action.yml
- .github/workflows/digestabot.yaml
- .github/workflows/k8s-tests.yaml
- .github/workflows/presubmit-k8s-tests.yaml
:gift: This change adds a digestabot workflow to update digests daily, and pins several image names to digests in support of this.
This is WIP until https://github.com/chainguard-images/actions/pull/102 merges and I update the workflows to point to their source of truth
/kind feature
> Feature: Add a digestabot workflow and pin digests

- images/nginx/README.md
- images/nginx/configs/latest.apko.yaml
- images/nginx/configs/next.apko.yaml
- images/nginx/tests/02-welcome-page.sh
*THIS INCLUDES BREAKING CHANGES*
Most notably default port is now 8080 rather than 80, but also other config changes including default html directory and auto determining how many worker processes to instantiate.
This is all referenced in the README, which also includes information on how to get the old version. Is this enough or do we need to handle this differently?
Fixes: #452 #382
> Bring nginx closer to Docker official image.

- images/dotnet-runtime/configs/latest.apko.yaml
Fixes: #540 
Previously targeting wrong image (dotnet-sdk)
Related: 
```
annotations:
```
> dotnet-runtime: add ca-certificates-bundle

- images/nginx/README.md
Related: #452 
This updates the nginx README.md to use `-p 8080:8080` published ports. Running the examples as they are results in errors like this:
```
docker run --rm -d -p 8080:80 cgr.dev/chainguard/nginx:latest && curl -I localhost:8080
a9567dde7c0296bcf5e6581784aeceef1d3d7599c1c482dbb35a5af238adc793
curl: (52) Empty reply from server
```
Whereas with these changes the following works:
```
docker run --rm -d -p 8080:8080 cgr.dev/chainguard/nginx:latest && curl -I localhost:8080
3cd44f2f42948ad0299fd333c29c6fd84877b594f829588d84c1ac838a35472f
HTTP/1.1 200 OK
. . .
```
> Update nginx README.md with -p 8080:8080 published port mappings

- images/weaviate/tests/01-help.sh
- images/weaviate/tests/02-install.sh
It was missing a values.yaml file, which among other things, specified the auth module that should be used.
> weaviate: tests: fix invocation of helm chart

- images/kubernetes-dashboard/tests/02-deploy.sh
Fixes a flaky test for `kubernetes-dashboard` image where the port forward was not initialized before we tried curling from it.
> kubernetes-dashboard: tests: wait for the port-forward to become ready before using it

- images/secrets-store-csi-driver/configs/latest.apko.yaml
- images/secrets-store-csi-driver/tests/01-runs.sh
As discovered in https://github.com/wolfi-dev/wolfictl/pull/203 this image needs `mount` to be usable.
`mount` is provided by `util-linux-misc`. This PR also adds a test that the image contains `mount` and that it can be called.
`mount` is installed in the upstream image here: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/45588e2b83698962037c47458922f4451cfcbfe7/docker/Dockerfile#L33
> secrets-store-csi-driver: add util-linux-misc to make mount available

- .github/workflows/digestabot.yaml
chore: use PAT for digestabot
Fixes:
Related: 
```
annotations:
```
> chore: use PAT for digestabot

- .github/actions/release-image-terraform/action.yml
- .github/workflows/release.yaml
- images/ko/image.yaml
- main.tf
- monopod/pkg/images/images.go
Also: generate the SLSA provenance ahead of time and cache it to prevent rate limiting
Plz wait to merge - waiting on tf-apko release to fix issue related to x86_64 vs. amd64
> Create alternate actions path for tf-apko, opt-in ko

- .github/actions/policy-check-image/action.yml
- .gitignore
- policies/README.md
- policies/main.tf
:broom: This change moves the way we invoke our policy checks to use terraform instead of the policy tester.
For now this simply applies the terraform directly over the manually supplied refs, but the way this is structured the same terraform may be invokes as a module from other terraform in the future.
/kind cleanup
Here is an example where I invoke this manually on the list of digests for `cgr.dev/chainguard/git:latest-glibc`:
```
terraform apply
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - chainguard-dev/apko in /Users/mattmoor/go/src/github.com/chainguard-dev/terraform-provider-apko
│  - chainguard/chainguard in /Users/mattmoor/go/src/github.com/chainguard-dev/mono/terraform-provider- …
```
> Cleanup: Move the policy checks to use terraform.

- images/kubernetes-dashboard/tests/02-deploy.sh
The url is https not http, and if we patch before we set the image we can avoid a pull failure.
Fixes:
Related:
> Fix the dashboard test.

- images/jdk/configs/openjdk-11.apko.yaml
- images/jre/configs/openjdk-11.apko.yaml
Brings 11 up to the new standard installation path for java, and uses the `-default-jvm` package.
Related: https://github.com/wolfi-dev/os/pull/2075
> use new JAVA_HOME path and *-default-jvm for jdk/jre-11

- images/maven/configs/openjdk-11.apko.yaml
related to https://github.com/chainguard-images/images/pull/617/files
> Update the JAVA_HOME to match the new openjdk and sets the default jvm

- images/nvidia-device-plugin/tests/02-helm.sh
Fixes:
Related: 
```
annotations:
```
> fix helm tests for nvdia-device-plugin

- .github/workflows/presubmit-k8s-tests.yaml
We forget this a lot and it leads to test failures.
> Add a step to make the test scripts executable.

- images/external-attacher/tests/02-deploy.sh
- images/external-resizer/tests/02-deploy.sh
- images/metrics-server/tests/02-helm.sh
- images/vertical-pod-autoscaler-admission-controller/tests/02-helm.sh
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes:
Related: 
```
annotations:
```
> fix csi-attacher, csi-resizer, vpa, metrics-server tests

- images/bazel/configs/latest.apko.yaml
- images/gradle/configs/latest.apko.yaml
- images/jdk/configs/latest.apko.yaml
- images/jenkins/configs/latest.apko.yaml
- images/jre/configs/latest.apko.yaml
- images/maven/configs/latest.apko.yaml
- images/pulumi/configs/latest.apko.yaml
- images/zookeeper/configs/latest.apko.yaml
Use `openjdk-17-default-jvm` where appropriate and update `JAVA_HOME`.
> chase openjdk 17 changes in wolfi

- images/prometheus-cloudwatch-exporter/configs/latest.apko.yaml
Fix : fix cloudwatch-exporter java paths and explicitly specify jre
> fix cloudwatch-exporter java paths and explicitly specify jre

- images/envoy-ratelimit/README.md
- images/envoy-ratelimit/configs/latest.apko.yaml
- images/envoy-ratelimit/image.yaml
Fixes:
Related: 
```
annotations:
```
> fix envoy-ratelimit package and symlink issue for upstream helm chart

- .github/workflows/digestabot.yaml
- enable signoff for digestbot job
the PRs from digestbot is failing the DCO check, this should fix that
> enable signoff for digestbot job

- images/external-dns/tests/02-e2e.sh
- images/kubernetes-csi-external-provisioner/tests/02-deploy.sh
Fixes:
Related: 
```
annotations:
```
> add e2e test for external-dns

- images/argocd/image.yaml
Fixes:
The argocd image only had the `latest` tags, no version tags were extracted and published
> Fix: Set the correct argo-cd package name

- .github/actions/build-image-terraform/action.yml
- .github/actions/release-image-terraform/action.yml
- main.tf
This cleans up legacy auth paths, mirror options, superfluous installations, unneeded `id:` fields, SLSA attestation, QEMU setup, and a bunch more.
This is intended to help get a complete picture of what's left wrt moving ~everything to terraform.
> Do a cleanup pass over the terraform release action.

- main.tf
- policies/04-has-slsa-attestation.yaml
This reverts #724 now that there is a new release of `tf-cosign` and switches the policy to use multiple authorities.
I was able to run this over one of the previously failing digests locally, which failed with the prior tf-cosign release:
```
TF_VAR_image_refs='["cgr.dev/chainguard/apko:latest","cgr.dev/chainguard/apko:latest@sha256:b843f830a353cb26fb8bd9e57d920a2d8e8f6b56190957a8c80ccaa6914e0a09","cgr.dev/chainguard/apko:latest@sha256:4f20fd165080e8169b8cc594216e1aa565d7e4e3496e97320a6c3a7ca88adc9f"]' terraform apply
```
> Revert #724 with multiple authorities

- monopod/pkg/images/images.go
I noticed `wolfi-dev/tools` was failing because of this new requirement, so relax it and allow the file to be missing.
> Allow monopod to tolerate missing `globals.yaml`.

- .github/actions/build-image/action.yml
- .github/actions/release-image/action.yml
With one exception this enables us to stop using build options.
> Pass through extra packages.

- images/kubectl/tests/02-use.sh
This adds a test that the kubectl image can be used to talk to a local kind cluster.
> kubectl: add k8s test

- images/rabbitmq/tests/02-perf.sh
Fixes: adds some e2e-lite tests to the rmq image in the form of `perf-test`. while not a real perf-test, it's a cheap and cheerful e2e alternative. this should at very least help us catch errors like [this](https://github.com/wolfi-dev/os/issues/2336) early
> add a rmq test using perf-test

- .github/actions/build-image/action.yml
- .github/actions/release-image/action.yml
We now plumb through `--package-append` or `TF_VAR_extra_packages` to our builds, so we no longer need to blend it into `apko.yaml`.
After `php-fpm` (thanks @erikaheidi 🙏 ) the only thing build options were used for was to add packages.
We still use `global.yaml` and `images.yaml` to seed the value passed to `--package-append`, but `apko` itself no longed needs this.
> Drop the build options blender

- images/kubernetes-csi-node-driver-registrar/configs/latest.apko.yaml
The [package](https://github.com/wolfi-dev/os/blob/main/kubernetes-csi-node-driver-registrar.yaml) puts the binary at `/usr/bin` and the image had been invoking it as if it was in `/`.
@ajayk found this
We need better kind tests for these images.
> csi-node-driver-registrar: fix command

- images/vault/README.md
- images/vault/configs/latest.apko.yaml
For compatibility with upstream and Helm chart, the image now starts as root and switches to the vault user in the script.
> Start container as root and switch user in entrypoint.

- images/external-attacher/tests/02-deploy.sh
- images/external-resizer/tests/02-deploy.sh
- images/external-secrets/tests/02-helm.sh
- images/kube-bench/tests/02-run.sh
- images/kube-downscaler/tests/02-deploy.sh
- images/kubernetes-csi-external-provisioner/tests/02-deploy.sh
- images/kubernetes-dashboard/tests/02-deploy.sh
- images/prometheus-redis-exporter/tests/02-install.sh
- images/weaviate/tests/02-install.sh
`$IMAGE_NAME` will be populated with the just-built image reference by digest, which we should use wherever possible so we don't have to tag it first.
Unfortunately a lot of tests still require `$IMAGE_TAG` to be compatible with Helm charts 😭
> tests: standardize on using IMAGE_NAME, where possible

- .github/actions/build-image-terraform/action.yml
- .github/actions/release-image-terraform/action.yml
- images/bazel/main.tf
- images/bazel/tests/main.tf
- images/clang/main.tf
- images/clang/tests/main.tf
- images/consul/main.tf
- images/consul/tests/main.tf
- images/crane/main.tf
- images/crane/tests/main.tf
- images/ko/configs/latest.apko.yaml
- images/ko/main.tf
- images/ko/tests/main.tf
- images/terraform/main.tf
- images/terraform/tests/main.tf
- monopod/pkg/images/images.go
This breaks off a significant chunk of https://github.com/chainguard-images/images/pull/758
This iteration will let us do more interesting things with dedicated test modules (e.g. @imjasonh helm testing) but the dedicated modules are more verbose than I'd like and we don't shed any of the `image.yaml` configuration since these are still invoked individually per variant.
> Move towards dedicated TF modules per image

- images/bazel/main.tf
- images/clang/main.tf
- images/consul/main.tf
- images/crane/main.tf
- images/ko/main.tf
- images/terraform/main.tf
We should have dependabot do this, and probably have a script we can run manually to upgrade everything in the repo.
Matt says:
> I think I want a shim for the module in the repo to let us centrally manage that version
> use apko publisher module 0.0.4

- .github/actions/release-image/action.yml
gcsfuse can only mount a whole bucket, but we only need `os/`, so we'll mount the bucket to `/gcsfuse` and symlink `/gcsfuse/os/` -> `./packages/`
> mount the bucket to /gcsfuse and symlink os/

- .github/actions/release-image/action.yml
`/tmp/gcsfuse/os/` should symlink to `./packages/`, not `./packages`, where it then contains a `./packages/os/` directory where the good stuff is.
Please let me know if I got this wrong again again.
> fix gcsfuse again again again

- images/bazel/configs/latest.apko.yaml
Official bazel distribution assumes presence of 2 tools in the underlying environment: 
- zip (https://github.com/bazelbuild/bazel/blob/85dcafeba92479bee5b2cd2cb3f33f84be7de7f7/tools/test/test-setup.sh#L430)
- file (https://github.com/bazelbuild/bazel/blob/85dcafeba92479bee5b2cd2cb3f33f84be7de7f7/tools/test/test-setup.sh#L396)
Neither of them is provided by `busybox`:
```
[2023-06-05 07:30:49] external/bazel_tools/tools/test/test-setup.sh: line 391: file: command not found
[2023-06-05 07:30:49] Could not create "/home/host_user/out/bazel_out/f8087e59fd95af1ae29e8fcb7ff1a3dc/sandbox/processwrapper-sandbox/26/execroot/{redacted}/bazel-out/k8-fastbuild/testlogs/projects/shared/test_module/test.outputs/outputs.zip": zip not found or failed
```
Fixes:
Address …
> Image: Bazel: Add file & zip binaries

- images/bazel/configs/latest.apko.yaml
- images/clang/configs/latest.apko.yaml
- images/consul/configs/latest.apko.yaml
- images/crane/configs/latest.apko.yaml
- images/ko/configs/latest.apko.yaml
- images/terraform/configs/latest.apko.yaml
- monopod/go.mod
- monopod/pkg/lint/linter.go
- monopod/pkg/lint/rules.go
- monopod/pkg/lint/types.go
Based on https://github.com/chainguard-images/images/pull/836
This checks that TF-based builds don't specify `repositories`, `keyring`, `archs`, or baselayout packages added by the TF layer.
Opening as draft to discuss.
> add lint check that TF builds don't specify unnecessary fields 

- policies/main.tf
I don't know how https://github.com/chainguard-images/images/pull/844 changed this.
https://github.com/chainguard-images/images/pull/844/files#diff-fca177b110cc5fa26d2af01a0af48c27a288f9c24de2ebef21c036dfe3114cf8
> fix: revert unintentional change to image_refs

- .github/workflows/presubmit-build.yaml
Given the high (potential) fanout, I suspect that this could potentially dramatically reduce the contention for runners if folks update their PRs.
> Cancel concurrent PR jobs

- images/ffmpeg/tests/02-convert.sh
- images/ffmpeg/tests/main.tf
Tested with
```
terraform init
terraform apply -var=digest=cgr.dev/chainguard/ffmpeg@sha256:10b2e21bd859b9386779474daab1ad19700ccac006500d41dadda133b80c93c0
```
from `./images/ffmpeg/tests/`
> change ffmpeg test to use working_dir

- images/telegraf/README.md
Telegraf is shown as stable on the [images](https://github.com/chainguard-images/images) page but the `README` still notes it as being EXPERIMENTAL. Removing reference in the `README`
> Remove spurious EXPERIMENTAL reference to telegraf README

- main.tf
When we switched to the mega module, we lost our sensitivity to these things: https://github.com/chainguard-images/images/blob/b9efef911e8e00ec6e20749fa3c77f148a99e8f2/.github/actions/release-image-terraform/action.yml#L69-L79
This brings it back!
> Fix the "extra" overrides.

- .github/actions/build-image/action.yml
- .github/actions/release-image/action.yml
- monopod/pkg/images/images.go
We stopped using these a while ago when we adopted `--packages-append` and removed the `yq` logic that mixed-in the options to the `apko` configuration files, but we never dropped this piece, which should now be superfluous.
This cleans up the remnants of `apkoBuildOptions` in images.
> Drop `apkoBuildOptions`

- images/glibc-dynamic/configs/latest.apko.yaml
- images/glibc-dynamic/tests/01-runs.sh
Following: https://github.com/chainguard-images/images/pull/894, I think this is needed too.
https://github.com/chainguard-images/images/blob/main/images/glibc-dynamic/configs/latest.apko.yaml
vs
https://github.com/chainguard-images/images/blob/main/images/cc-dynamic/configs/latest.apko.yaml
```
charlieegan3 $ docker image inspect cgr.dev/chainguard/glibc-dynamic:latest | grep 'User'
"User": "",
"User": "",
charlieegan3 $ docker image inspect cgr.dev/chainguard/cc-dynamic:latest | grep 'User'
"User": "",
"User": "65532",
```
<details>
<summary> Pre-review Checklist</summary>
Fixes:
Related: 
The general idea is that to the extent possible, the image should be a drop-in replacement to its public …
> Use non root config for glibc-dynamic

- images/bazel/configs/latest.apko.yaml
Bazel supports downloading of rules/artifacts from remote git repositories using natice `git_repository` rule (https://bazel.build/rules/lib/repo/git) .  Sometimes (especially when they are private) these repositories require ssh authentication.  Proposing to add SSH client to bazel.
https://bazel.build/rules/lib/repo/git
Without it bazel fails with:
```
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with ...:
error: cannot run ssh: No such file or directory
fatal: unable to fork
```
The general idea is that to the extent possible, the image should be a drop-in replacement to its public counterpart.
If you have an …
> Add openssh-client to Bazel image

- .github/actions/release-image-terraform/action.yml
I missed copying these over because they had to land first downstream due to `pull_request_target` 🤦
> Add missing pre-reqs for reproducibility test

- images/helm-chartmuseum/tests/01-helm-repo-add.sh
- images/nginx/tests/02-welcome-page.sh
- images/postgres/tests/02-query.sh
- images/postgres/tests/03-locale.sh
- images/prometheus/tests/02-healthy.sh
- images/redis/tests/02-server.sh
- images/zookeeper/tests/02-runs.sh
I keep hitting instances where the `date` pattern we use hits races because two tests run concurrently, so I went through and scrubbed all the occurrences I could find.
> Use `${FREE_PORT}` for unique container naming

- images/bazel/configs/latest.apko.yaml
Without this, to bazel has problems resolving golang toolchain:
```
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
3 | #include <stdlib.h>
|          ^~~~~~~~~~
compilation terminated.
stdlib: error running subcommand external/go_sdk/bin/go: exit status 1
```
The dependency install glibc-devel headers
Fixes:
Related: 
The general idea is that to the extent possible, the image should be a drop-in replacement to its public counterpart.
```
annotations:
"org.opencontainers.image.url": …
```
> Bazel: Add 'build-base' to the image.

- tflib/publisher/check-reproducibility.sh
When we use `${FREE_PORT}` to get a ~random container name, without also running something on that port to "claim" it, we end up getting name conflicts and flaky tests.
Instead of relying on `${FREE_PORT}` when we're not going to ~immediately run on that port, just use `${RANDOM}`.
> don't use FREE_PORT to get unique container name

- tflib/publisher/check-reproducibility.sh
We inject additional repositories and keyrings downstream with absolute paths, so these break in the apko container-based rebuild when the container doesn't have a symmetrical view of the working directory from which TF was invoked.
> Fix downstream invocation of reproducibility check.

- images/thanos-operator/main.tf
- images/thanos-operator/tests/main.tf
- use correct helm chart name
- drop test-latest-dev and random_pet
- use `values` instead of `set`s
> fix thanos-operator build

- images/php/configs/latest-fpm.apko.yaml
- images/php/configs/latest.apko.yaml
Currently, our PHP image has the following extensions built-in:
- php-curl
- php-openssl
- php-zlib
- pdo-mysql
- php-sodium
Total size: 43MB
With the [change in the Wolfi PHP package](https://github.com/wolfi-dev/os/pull/3211) compiling extensions as shared objects, we need to include some PHP extensions by default in order to keep backwards compatibility.
The new version with shared libraries is based on the [php:cli-alpine Dockerfile](https://github.com/docker-library/php/blob/d3fc8d9699726a2f6abbd7c4453bc81cf7fb6a2f/8.2-rc/alpine3.17/fpm/Dockerfile), it includes:
- php-curl
- php-openssl
- php-iconv
- php-mbstring
- php-mysqlnd
- php-pdo
- php-pdo_sqlite
- php-pdo_mysql
- php-sodium
- php-phar
Total size: 36.6MB 🤩
Meanwhile, the php:cli-alpine image is ~96MB 💁🏻‍♀️
The `latest-fpm` …
> Updating PHP Images

- images/guacamole-server/configs/latest.apko.yaml
- images/guacamole-server/tests/01-runs.sh
Fixes:
Adds the missing client libraries for the guacd binary.
* vnc
* telnet
* rdp
* ssh
NOTE:
I don't think `busybox` is required here but for the sake of making incremental changes I'm not removing it right now. Once we do remove it, we should be able to set the guacamole log level through an xml file rather than in the CMD
> add the client libraries for guacamole

- images/guacamole-server/configs/latest.apko.yaml
Fixes: this is need for an RDP support in guacamole-server
Related: 
The general idea is that to the extent possible, the image should be a drop-in replacement to its public counterpart.
```
annotations:
```
> add openssl-provider-legacy for rdp support

- images/stakater-reloader/README.md
- images/stakater-reloader/configs/latest.apko.yaml
Fixes: A typo in the name of the image for the stakater-reloader image.
If a user tries to pull cgr.dev/chainguard/stakader-reloader:latest it will not work.
Related: 
The general idea is that to the extent possible, the image should be a drop-in replacement to its public counterpart.
```
annotations:
"org.opencontainers.image.source": …
```
> fix: typo in the image name for stakater-reloader

- images/calico/configs/latest.csi.apko.yaml
- images/calico/main.tf
- images/calico/tests/install.sh
- images/calico/tests/main.tf
This adds an equivalent image to `calico/csi` and tests that it can be used in the DaemonSet along with the upstream K8s CSI node driver registrar
https://docs.tigera.io/calico/latest/getting-started/kubernetes/hardway/istio-integration
> calico: add calico-csi

- images/k3s/main.tf
this fixes:
```bash
cgr.dev/chainguard/k3s-embedded:latest-embedded
cgr.dev/chainguard/k3s-embedded:latest
```
> ensure k3s-embedded variant is tagged appropriately

- images/calico/tests/install.sh
- images/cluster-proportional-autoscaler/tests/helm.sh
- images/kube-bench/tests/run.sh
- images/kube-downscaler/tests/run.sh
- images/metacontroller/tests/helm.sh
- images/nvidia-device-plugin/tests/helm.sh
- images/prometheus/tests/node-runs.sh
- images/prometheus/tests/redis-installs.sh
- images/pulumi/tests/02-k8s-install-all-languages.sh
These are redundant now that we run the tests during build time in CI, and before tagging in releases.
> remove monopod:tag:k8s tags from tests

- images/hugo/tests/02-quickstart.sh
Once we have a fresh `git:latest-glibc-dev` we should revert this change.
> Fix the Hugo tests until we can rebuild our git images

- tflib/publisher/check-reproducibility.sh
- tflib/publisher/main.tf
I thought I pulled in 0.9.0, but this only happened downstream.  This also picks up another downstream change to the random container naming to make collisions even less likely.
> Pick up apko 0.9.0 and container name improvement

- images/git/alpine.tf
- images/git/tests/main.tf
- images/git/tests/version.sh
- images/git/wolfi.tf
This seems to have been dropped in https://github.com/chainguard-images/images/pull/960, and not tested except via hugo's tests, which check that the -dev image can be used to run `git submodule`.
This PR also adds tests, which only run on the dev images, to check that `git submodule` works.
> readd dev packages to wolfi git image

- tflib/publisher/check-reproducibility.sh
This should improve performance, but it's really a reliability change because we periodically see network flakes downloading APKs, and given the nature of this test we shouldn't ever need to download anything if we have a hot cache (which we should!).
> Mount the host's cache directory into the container's reproducibility check

- images/kubernetes-dashboard/tests/main.tf
v7 of the helm chart, released a few hours ago, uses the `image.tag` value as a k8s label, which has a max length of 63 characters. Our pseudo-tag (so we can test the image without tagging it) is longer than that.
https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard?modal=template&template=deployments/api.yaml
This change pins to the last release before v7.
> fix kubernetes-dashboard helm test

- .github/actions/build-image-terraform/action.yml
- .github/actions/release-image-terraform/action.yml
- tflib/publisher/check-reproducibility.sh
This is so that downstream in tf-apko we can run these builds presubmit and make breaking changes, so long as APKO and tf-apko remain in sync wrt what's produced.
> Have the reproducibility script take the `APKO_IMAGE` via env var.

- images/vault/tests/acceptance.sh
fixes a flake where the test tries to unseal the vault before the pod is running
> add a wait/retry before attempting to unseal vault

- tflib/version-tags/main.tf
This produces the same list of tags as we got from the regexp monster previously, but comes with tests in the tf-apko repo and is written in Go.
> use apko_tags, slay the regexp monster

- images/php/configs/latest-fpm.apko.yaml
- images/php/tests/main.tf
This PR fixes the entrypoint for the `php-fpm` image, which had a slight change in recent updates from `/usr/bin/php-fpm` to `/usr/sbin/php-fpm` to comply with standard path locations.
> Fix: fixing entry point for php-fpm image

- images/prometheus/tests/redis-installs.sh
One of the nightly builds flaked and it looks like the pods weren't created instantly from the Deployment (which is also unrealistic):
```
error: no matching resources found
```
> Add a sleep after apply before wait

- images/calico/main.tf
```
$ crane ls ttl.sh/jason/calico
3.26.1-r8
3.26.1
3.26
3
latest
v3.26.1-r8
v3.26.1
v3.26
v3
```
This is for compatibility with Tigera Operator to install Calico.
> calico: also version-tag with v prefix

- images/configmap-reload/tests/main.tf
- tflib/publisher/main.tf
This release attempts to fix some flakiness we see while fetching APKs.
> Bump terraform-provider-apko to v0.9.2

- images/configmap-reload/tests/main.tf
This helm_release does not appear to test or exercise the package in any way.
Looking here, it appears that it is no longer used by that chart: https://github.com/prometheus-community/helm-charts/blob/cc2c507e4a4b625f561577bba13795b7f8bde40a/charts/prometheus/README.md#to-200
> Remove configmap-reload helm_release test

- images/flux/configs/latest.source-controller.apko.yaml
this surfaces when attempting to use the `cosign.verify` feature of `OCIRepository`:
```
17s         Warning   VerificationError         ocirepository/root-source             failed to verify the signature using provider 'cosign keyless': unable to get Rekor public keys: creating cached local store: mkdir /home/nonroot/.sigstore: read-only file system
```
> ensure flux source controller can write to its home

- .github/actions/build-image-terraform/action.yml
- .github/actions/release-image-terraform/action.yml
`terraform init` output is long, and gets longer with each new module we define. There isn't usually much useful information in there, just lots of identical lines about what versions of what providers are installed. Save our scrolling fingers.
See https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines
> group/collapse 'terraform init' output in CI logs

- images/minio/main.tf
- images/minio/tests/100-namespace.yaml
- images/minio/tests/200-configmap.yaml
- images/minio/tests/200-secret.yaml
- images/minio/tests/300-deploy.yaml
- images/minio/tests/300-service.yaml
- images/minio/tests/400-job.yaml
- images/minio/tests/main.tf
- images/minio/tests/test.sh
We cannot use the official Helm chart because they invoke `minio` with `/bin/sh -ce minio` instead of just running `minio` directly. This is a workaround until we can send one upstream to fix the upstream Helm chart.
> Add a KinD test for minio and minio-client

- images/metrics-server/tests/check-metrics-server.sh
- images/metrics-server/tests/main.tf
> Use kubectl top to test metrics-server

- images/prometheus/tests/check-kube-prometheus-stack.sh
- images/prometheus/tests/main.tf
- images/prometheus/tests/node-runs.sh
This deploys every image I could find referenced from the `kube-prometheus-stack` `values.yaml`, and I confirmed locally that things like `alertmanager` and `prometheus` spin up with this configuration, and that it is using our images.
I also made it use our public KSM image (and we should consider doing the same in the KSM test that spins up this same Helm chart).
However, despite standing up more stuff, this doesn't actually functionally test them still, but it should enable us to follow up and test things.  The one thing that IS tested is the `node-exporter` where I changed the test to hit the DaemonSet Service created by the Helm chart instead of spinning up its own pod.
> Expand the list of images tested with prometheus helm chart

- .github/actions/release-image-terraform/action.yml
As I added the previous slack post, I missed that we already had one buried in our actions workflow.
This strips the old version of the slack post to avoid double-posting here and downstream (where I also added this).
> Drop double slack post

- images/node/configs/18.apko.yaml
Right now, it depends on `nodejs`, which is being turned into a version stream.
> node: explicitly lock the nodejs:18 variant to the nodejs-18 version stream

- tflib/publisher/main.tf
This should help with fulcio and rekor 429s.
> Bump terraform-provider-cosign to 0.0.9

- images/consul/main.tf
This should be equivalent, but we replaced `consul` with slotted versions, so `consul` will become `consul-1.16` due to the `provides:` and we should use that for version tags.
> Fix the consul package name to consul-1.16

- images/bazel/configs/latest.apko.yaml
Added packages are needed to be in the image to make it possible to build anything depended on protobuf from Google:
```
http_archive(
name = "com_google_protobuf",
sha256 = "c56b669e5898100142ff5936221b9c2854ce88379fd473d008607d3537500619",
strip_prefix = "protobuf-3.23.4",
urls = [
"https://github.com/protocolbuffers/protobuf/archive/v3.23.4.tar.gz",
],
)
```
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
- [] The image runs as `nonroot` and GID/UID are set to 65532 or upstream default
> Add jq, patch and python3 to let build google's protobuf

- images/kubernetes-csi-node-driver-registrar/configs/latest.apko.yaml
This fixes incompatibility with a helm chart that hardcode a binary.
https://github.com/wolfi-dev/os/pull/4279
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/charts/secrets-store-csi-driver/templates/secrets-store-csi-driver.yaml#L49C34-L49C43
> Use kubernetes-csi-node-driver-registrar-compat

- images/gradle/tests/02-build.sh
Target image was previously hardcoded instead of using the current `IMAGE_NAME` environment variable. Updated to use the current `IMAGE_NAME` environment variable sent from Terraform.
I removed the checklist as this PR solely updates a test script.
> fix: use IMAGE_NAME for Gradle test script

- images/opentelemetry-collector-contrib/configs/latest.apko.yaml
- images/opentelemetry-collector-contrib/tests/custom-config.yaml
- images/opentelemetry-collector-contrib/tests/main.tf
- main.tf
Expanded the test sweeps we run for `otelc` into 2 groups (deployment and daemonset). Also turn on more receivers/exporters to allow for testing more things.
While many of these settings don't trigger an unhealthy startup, some spew actionable errors that we should be able to catch now with the future e2e tool.
Also adds `busybox` to the image to allow for configurations using certain receivers (like `eks`) to scrape host data, preventing errors like this:
```
2023-08-11T01:26:47.344Z    info    gohai/gohai.go:54    Failed to retrieve platform metadata    {"kind": "exporter", "data_type": "metrics", "name": "datadog", "error": " exec: \"uname\": executable file not found in $PATH"} …
```
> update otelc test cases

- images/go/main.tf
Go 1.21 was released, making it the latest.
This also drops some unnecessary `toset` wrapping for better readability.
As a followup we need to move 1.19 out of the public image set, which I'll do in another PR.
> go: promote 1.21 to latest

- images/openai/configs/latest.apko.yaml
- images/openai/main.tf
https://github.com/wolfi-dev/os/pull/4387 renamed the openai package to py3-openai and added a `provides: ['openai']`, but it reset the epoch, so depending on `openai` in the image config still gets the old version `0.27.8-r2`.
By explicitly depending on `py3-openai` we get `0.27.8-r0` which specifies runtime dependencies on the necessary python packages, avoiding a conflict on `py3-certifi` and others.
> openai: fix dependency on py3-certifi

- images/prometheus/tests/check-cloudwatch-exporter.sh
- images/prometheus/tests/check-kube-prometheus-stack.sh
- images/prometheus/tests/main.tf
Add installation of cloudwatch-exporter to the Terraform template and create new shell script to check it runs successfully with our newly built image.
Notes: No changes to the image itself.
Notes: No changes to the image itself.
Notes: No changes to the image itself.
Notes: No changes to the image itself.
Notes: Added a new Helm chart to the tests for verification of the cloudwatch-exporter component.
Notes: No changes to the image itself.
Notes: No changes to the image itself.
Notes: No changes to the image itself.
Notes: No changes to the image itself.
Notes: No changes to the image itself.
No changes in access control or auth.
No changes for entrypoint.
No changes for CMD.
No changes for environment variables.
No changes to the image itself.
No changes to logging.
No specific changes …
> [cloudwatch-exporter] add new verification test

- images/apko/configs/latest.apko.yaml
- images/melange/configs/latest.apko.yaml
Both `apko` and `melange` no longer shell out to `apk`.
Needs https://github.com/wolfi-dev/os/pull/4479
> Drop vestigial dependency on apk-tools

- .github/workflows/release.yaml
https://github.com/chainguard-images/images/pull/1200 trialed this for `ko`, which was correctly built without version-tagging last night.
This change will disable version tagging for all new image builds.
> disable new version tags

- images/kubectl/configs/latest.apko.yaml
- images/kubectl/main.tf
The version tag module we use to extract the version from the given package doesn't seem to understand when that package is `provide`d by a package with a different name.
This makes the config very explicit about what version of kubectl to use, and what package to use when generating the version tag.
> kubectl: fix image build

- .github/workflows/release.yaml
It's needlessly wasteful to trigger a (no-op) release of every image when we change README.md or withdraw images or repos.
> don't trigger releases on withdrawn images

- withdrawn-images.txt
We're keeping these around a bit longer since they get some non-trivial usage.
My script to generate the list must have missed those.
> Don't withdraw wait-for-it tags

- images/helm/configs/latest.apko.yaml
- images/kubectl/configs/latest.apko.yaml
- images/kyverno/configs/latest.admission.apko.yaml
- images/kyverno/configs/latest.background.apko.yaml
- images/kyverno/configs/latest.cleanup.apko.yaml
- images/kyverno/configs/latest.cli.apko.yaml
- images/kyverno/configs/latest.init.apko.yaml
- images/kyverno/configs/latest.reports.apko.yaml
[kubectl-latest](https://github.com/wolfi-dev/os/blob/main/kubernetes-latest.yaml) introd a new way of tracking the latest kubectl component _and_ adding it as the default kubectl (`/usr/bin/kubectl`)
this changes all our images that rely on a "latest" `kubectl` to track using this new package.
> use the new kubectl latest for tracking default kubectl

- images/argocd/README.md
- images/aspnet-runtime/README.md
- images/dotnet-runtime/README.md
- images/dotnet-sdk/README.md
This PR cleans up some removed tags from image READMEs.
The Java READMEs still need to be cleaned up in another PR and will take a bit more work.
> Fix tags in READMEs

- images/jdk/README.md
- images/jre/README.md
Following tag availability changes we can't use named tags.
> Fix docs in JDK and JRE images

- images/go/README.md
:wave:  Hey gang, first contribution on this repo, LMK if I'm doing anything wrong. All I want to do is update the `go` image README to point to the right location for the example and include the correct command.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> fix for go image README

- images/telegraf/main.tf
This is in preparation for https://github.com/wolfi-dev/os/pull/4625
> Have `telegraf` extract versions from the `telegraf-1.27` package

- images/maven/main.tf
I believe that when we were migrating to TF we dropped this tag, so this brings it back.
This was caught by some checking I'm adding to our downstream syncer that checks signature timestamps on our tagged images.
> Revive this dropped tag from Tf migration.

- images/guacamole-server/tests/01-runs.sh
Use a regex instead of comparing exact versions to prevent test failures when version bumps occur.
> fix: update guacamole test script to use regex

- images/trust-manager/tests/main.tf
This is a bandaid to unblock things, but we should consider eliminating this ~useless test in favor of something more comprehensive.
> Fix the error message this test is expecting.

- images/gatekeeper/tests/main.tf
The webhook pods may be slow to come up and may be rotated especially when running many tests together. Change the failure policy to fail open. This also matches default behavior with other Gatekeeper [webhook](https://github.com/open-policy-agent/gatekeeper/blob/master/charts/gatekeeper/README.md).
Notes:
> Configure gatekeeper check-ignore-label.sh webhook to fail open in tests

- images/nginx/configs/latest.apko.yaml
- images/nginx/main.tf
https://github.com/wolfi-dev/os/pull/4896 renamed the `nginx` package to `nginx-mainline`, which confuses our version-tag module which expects the actual package name, not its provided name.
This updates the YAML config to specify the real package name to avoid confusion, and updates the version-tag module invocation to look for that same package name.
> nginx: fix build using nginx-mainline

- images/calico/tests/install.sh
see inline comments 😮‍💨 
ref: #1284
> add k3d support for calico tests

- images/calico/configs/latest.pod2daemon.apko.yaml
https://github.com/wolfi-dev/os/pull/4933
Calico operators expect the entrypoint to be in `/usr/local/bin`
> calico: use calico-pod2daemon-compat

- images/calico/configs/latest.pod2daemon.apko.yaml
- images/calico/tests/install.sh
- images/calico/tests/main.tf
use the `tigera-operator` method for installing and testing `calico`, which buys us a few things:
- its seemingly the upstream supported way of installing and managing calico
- it allows for "easier" replacement of images at install time
- it properly doesn't default to use bpf mounting with `mount-bpff` container, which means it doesn't need the same docker in docker hacks that the bpf method requires.
> use tigera-operator installation for calico tests

- images/jre/main.tf
With the previous ordering the pinned versions would "win" the merge and we would use those builds for the lesser-scoped version tags (e.g. `openjdk-11`) even where the unpinned versions are more recent.
> Reorder JREs in tagger

- images/cert-manager/tests/main.tf
- images/gatekeeper/tests/main.tf
- images/keda/tests/main.tf
Reusing these test modules downstream from a mega-module we are seeing high contention on the KinD cluster and pods taking longer than the default timeout to get created.  This allows them more time to come up.
> Adjust helm test timeouts

- images/vault/tests/acceptance.sh
Right now the math works out to 30s, but on busy clusters this can take longer.
> Give vault more time to become Running.

- images/nginx/config/main.tf
- images/nginx/config/template.apko.yaml
- images/nginx/main.tf
The digest of the image remains the same before and after this change:
From `main`:
```
module.nginx.module.tagger.oci_tag.this["latest-dev"]: Creation complete after 2s [id=ttl.sh/jason/nginx:latest-dev@sha256:2773091cfad02f528e31c1b9a06f08dbcba57b365de38cfa16726491515ed6fe]
```
From this branch:
```
module.nginx.oci_tag.latest-dev: Creation complete after 1s [id=ttl.sh/jason/nginx:latest-dev@sha256:2773091cfad02f528e31c1b9a06f08dbcba57b365de38cfa16726491515ed6fe]
```
> nginx: refactor to use extra_packages

- images/istio/README.md
- images/istio/configs/pilot/main.tf
- images/istio/configs/pilot/template.apko.yaml
- images/istio/main.tf
- images/istio/pilot.tf
- images/istio/tests/main.tf
Notes:
Notes: CVE-2019-3826 is a false positive because Prometheus versioning (0.44 = 2.44 > bad version 1.17) confusing the scanners.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> istio-pilot image for Istio controller containers

- images/nvidia-device-plugin/tests/helm.sh
I had a test flake with:
```
Test failed for ref registry.local:5000/testing/nvidia-device-plugin@sha256:d50d1bd3d176000f6d8a06786266e1a3f35ce35ba87beb80e8da2b28d02a54c6, got error: exit status 1
+ helm repo add nvdp https://nvidia.github.io/k8s-device-plugin
"nvdp" has been added to your repositories
+ helm upgrade --install nvdp nvdp/nvidia-device-plugin --namespace nvidia-device-plugin --create-namespace --set image.repository=registry.local:5000/testing/nvidia-device-plugin --set image.tag=unused@sha256:d50d1bd3d176000f6d8a06786266e1a3f35ce35ba87beb80e8da2b28d02a54c6
Release "nvdp" does not exist. Installing it now.
NAME: nvdp
LAST DEPLOYED: Fri Sep  8 02:06:12 2023
NAMESPACE: nvidia-device-plugin
STATUS: deployed
REVISION: 1
TEST SUITE: None
+ kubectl wait …
```
> Give nvidia time before wait

- images/prometheus/configs/latest.pushgateway.apko.yaml
- images/prometheus/main.tf
- images/prometheus/tests/main.tf
Notes: 12MB vs 21MB
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes: We don't have these for any of the prometheus images.
> Add prometheus pushgateway image.

- images/prometheus/configs/latest.mongodb-exporter.apko.yaml
- images/prometheus/main.tf
- images/prometheus/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add prometheus mongodb exporter.

- images/kubernetes-csi-node-driver-registrar/config/main.tf
- images/kubernetes-csi-node-driver-registrar/config/template.apko.yaml
- images/kubernetes-csi-node-driver-registrar/main.tf
This adopts the "virtual package" pattern ahead of version streaming this package.
> Refactor `kubernetes-csi-node-driver-registrar`

- images/calico/main.tf
This package was version streamed yesterday and I didn't realize we had two image builds of the same package.
> Switch the package name to version streamed.

- CODEOWNERS
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> fix: update stale user list in CODEOWNERS

- images/argocd/tests/main.tf
The existing chart (`argo`) is using some extremely outdated, non representative deployment of argocd (`argo-cd`).
This also renames things to deloy `argocd` with its `argocd-repo-server` component.
Ref: https://artifacthub.io/packages/helm/argo/argo-cd
> ensure argocd uses the actual helm chart

- images/flux/configs/latest.source-controller.apko.yaml
this only materializes for some ~niche cases such as signature verification, which writes to `/home/nonroot/.sigstore` to cache public rekor keys
https://github.com/fluxcd-community/helm-charts/blob/main/charts/flux2/templates/source-controller.yaml#L116
> change flux-source-controller uid/gid to match upstream charts

- images/kubernetes-csi-external-attacher/config/template.apko.yaml
`kubernetes-csi-external-attacher` is duplicated in template and `extra_packages`.
See https://github.com/chainguard-images/images/blob/main/images/kubernetes-csi-external-attacher/config/template.apko.yaml
> kubernetes-csi-external-attacher: fix template 

- images/calico/README.md
Hoist these out of our test `install.sh` as instructions for how to install calico with cgr.dev variants.
> add docs for installing calico using the tigera-operator

- images/kubernetes-csi-external-attacher/tests/deploy.sh
- images/kubernetes-csi-external-attacher/tests/main.tf
This allows running tests of different versions side-by-side.
> Add namespace to csi-external-attacher tests

- images/cert-manager/configs/latest.acmesolver.apko.yaml
- images/cert-manager/configs/latest.cainjector.apko.yaml
- images/cert-manager/configs/latest.controller.apko.yaml
- images/cert-manager/configs/latest.webhook.apko.yaml
- images/cert-manager/configs/main.tf
- images/cert-manager/main.tf
Unfortunately still needs separate apko files since entrypoint is readonly. :(
This is a refactor - there should be no diff from existing images.
cc @mattmoor - I based this off the thread from early. lmk if I'm holding things wrong.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Refactor cert-manager to allow templatable packages.

- images/fluentd/main.tf
Adding the new packages fluent-plugin-out-http and a latest-splunk-dev variant to solve https://chainguardhelp.zendesk.com/agent/tickets/191
Notes:
- [] The Grype vulnerability scan returned 0 CVE(s).
- [x ] The Grype vulnerability scan returned > 0 CVE(s) (please explain in the notes).
Notes:
webrick  1.8.1                gem   CVE-2008-1145  Medium
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Adding a dev tag with this commit.
> Adding HTTP plugin and -dev variant

- images/prometheus-statsd-exporter/tests/main.tf
This is needed so that we can invoke the test module multiple times without them conflicting.
> prometheus-statsd-exporter: allow non conflicting helm release resources

- images/kubernetes-csi-external-attacher/tests/deploy.sh
Fix cluster level test resource name collision to allow tests to run side-by-side.
> kubernetes-csi-external-attacher: fix cluster-level resource name collision

- images/fluentd/main.tf
Adding a dev image for the splunk variant to allow shell access and testing plugins
Notes:
Notes:
webrick  1.8.1                gem   CVE-2008-1145  Medium
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> fluentd-latest-dev image

- images/istio/configs/operator/main.tf
- images/istio/configs/operator/template.apko.yaml
- images/istio/main.tf
- images/istio/operator.tf
- images/istio/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add istio operator image.

- images/argocd/configs/latest.argocd.apko.yaml
- images/argocd/configs/latest.repo-server.apko.yaml
During running an argoCD image from chainguard there is a problem with running argocd-repo-server successfully.
The following error appears in the logs:
```
time="2023-09-19T10:16:46Z" level=fatal msg="exec: \"gpg\": executable file not found in $PATH"
```
Quick search-through the argo-cd repository, and yeah it uses gpg internally:
```
OUTPUT=$(gpg $ARGS 2>&1)
```
https://github.com/argoproj/argo-cd/blob/df714accc0184fea0f09cfa8a4e1d4ed4a6a7b4b/hack/gpg-wrapper.sh#L4
gpg is not in the packages list in the repo, hence adding it.
> Adding missing GPG package for argoCD

- images/prometheus-adapter/tests/cleanup.sh
- images/prometheus-adapter/tests/main.tf
this helm chart installs cluster level resources. if we're using this module to test different versions, the entire Helm Chart needs to be uninstalled for a new version to be installed.
> prometheus-adapter: fix test

- images/crossplane-aws/tests/install.sh
- images/crossplane-azure/tests/install.sh
These tests pass when pushing to cgr.dev/chainguard, where anybody can pull, but fail when pushed to another non-public repo on cgr.dev (or, I suppose, any private repo anywhere).
The tests fail because the Crossplane control plane running on the cluster doesn't have permission to pull the image, which it needs to do to extract provider metadata from it.
This PR updates the test to check if the cgr cred helper is installed, and if so, populate an ephemeral Docker config, and populate a Kubernetes Secret with those creds, and tell the Crossplane control plane to use the secret to pull.
This passed for me locally with:
```
terraform apply -var=target_repository=cgr.dev/imjasonh.dev -target=module.crossplane-aws -auto-approve
```
> crossplane tests: enable pushing to a private repo

- images/tekton/tests/test.sh
Tekton's releases aren't updating the `latest` release.yaml, and our latest image depends on configuration in the latest release (`config-tracing`, specifically, possibly others).
This updates the test to pin to the latest release v0.52.0 until such a time as the `latest` release.yaml is updated with new releases.
> Fix tekton smoke test by pinning to v0.52.0

- images/aws-efs-csi-driver/configs/latest.apko.yaml
When this boots up, it attempts to delete `/csi/csi.sock` and then listen on it, but does not have permissions to do so.
> aws-efs-csi-driver: Fix /csi permissions

- images/aws-efs-csi-driver/configs/latest.apko.yaml
This had incorrect indentation, so paths was ignored!
> aws-efs-csi-driver: Outdent paths

- images/envoy/tests/main.tf
- images/envoy/tests/static.sh
- images/envoy/tests/static.yaml
This test confirms that Envoy can serve a simple static `direct_response` route from a config file.
> Add a test of Envoy serving static rules

- images/cert-manager/config/main.tf
- images/cert-manager/main.tf
- images/cert-manager/tests/main.tf
We have 1.13, but it looks like it's missing the provides, so we'll need to go back and add that.
https://github.com/wolfi-dev/os/blob/main/cert-manager-1.13.yaml
cc @k4leung4 @wlynch
> Refactor `cert-manager` to virtual/latest pattern

- images/git/alpine.tf
- images/git/main.tf
- images/git/wolfi.tf
- images/maven/11.tf
- images/maven/17.tf
- images/maven/main.tf
- images/tekton/main.tf
Now the only reference to the `dev` module is from the publisher :tada:
> Refactor the remaining dev variants.

- images/cert-manager/tests/main.tf
Previously the non-controller images weren't being overidden due to a missing layer of `image = {...}`.
cc @wlynch FYI
> Fix the `cert-manager` tests to test all images.

- images/fluentd/main.tf
Adding the prometheus plugin to the splunk variant of the fluentd image to make it work with upstream charts.
> Add the prometheus plugin to the splunk variant of fluentd

- images/fluentd/main.tf
Adding another plugin to the fluentd splunk variant. Dependent on https://github.com/wolfi-dev/os/pull/5927
> add rewrite-tag-filter plugin to fluentd splunk variant

- images/fluentd/main.tf
The fluent-plugin-rewrite-tag-filter requires the `hostname` command
https://github.com/fluent/fluent-plugin-rewrite-tag-filter/blob/18b9cf7e5d29e5aec5c0834b9211930b9f967307/README.md?plain=1#L230
> Add net-tools to fluentd splunk variant

- images/dex/main.tf
Previously, https://github.com/chainguard-images/images/pull/1430
The customer installs dex in a similar way to argocd, which expects to have images tagged with versions beginning with `v`.
> dex: add v prefix to version tags

- images/rabbitmq/README.md
It's just about - I guess - a copy/paste mistake
> Fix typo in readme

- images/crane/README.md
- monopod/pkg/commands/matrix.go
- monopod/pkg/commands/readme.go
- monopod/pkg/images/images.go
It seems matrix logic expects the output to be a list of objects, and not a list of strings.
We might be able to clean this up later, but for now, let's just try to unbreak things.
> fix: have monopod matrix emit includes correctly

- .github/actions/build-image-terraform/action.yml
- .github/workflows/presubmit-build.yaml
https://github.com/chainguard-images/images/pull/1467 made inputs explicit, and these inputs are stupid and not needed.
> drop vestigial appends from presubmit-build

- images/redis/configs/latest.apko.yaml
- images/redis/configs/main.tf
- images/redis/main.tf
- images/redis/tests/main.tf
Few small tweaks to the redis image to bring it (closer) in line with our newer images. Namely this will allow us to invoke it from images-private and pass in different redis package versions, as well as fips openssl config module.
Being carried out in prep for: [image-requests/issues/365](https://github.com/chainguard-dev/image-requests/issues/365)
Checked I could build and run the image locally. Note i'm on macOS and the included test failed so i needed to disable it when doing local runs. Expecting its some mac issue and going to check the test passes in the CI run. Regardless I didn't make any changes to the existing test.
> Update redis image so we can invoke it from images-private

- images/aws-efs-csi-driver/configs/latest.apko.yaml
These packages expect to run as root and cannot start up as is.
Currently, it fails with:
> remove /csi/csi.sock: permission denied
> Run aws-efs-csi-driver as root

- images/external-dns/tests/e2e.sh
Reverts chainguard-images/images#1483
Didn't seems to address build issue.
> Revert "external-dns test: use traefik instead of nginx"

- tflib/dev-subvariant/main.tf
- tflib/publisher/main.tf
Now that we have consolidated production of dev variants via the publisher module, this removes the `dev-subvariant` module we used to define the constant because it is used in a single place.
> Remove `tflib/dev-subvariant` module.

- README.md
- images/trillian/README.md
- images/trillian/config/main.tf
- images/trillian/main.tf
- images/trillian/tests/main.tf
- images/trillian/tests/test.sh
- main.tf
41MB vs 72MB (gcr.io/trillian-opensource-ci/log_server:v1.5.2)
```
NAME                              INSTALLED  FIXED-IN  TYPE       VULNERABILITY  SEVERITY 
github.com/prometheus/prometheus  v0.35.0              go-module  CVE-2019-3826  Medium
```
based on https://github.com/anchore/grype/issues/840, it seems like this is a CVE in the prometheus frontend and shouldn't affect this application.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add trillian images

- .github/workflows/presubmit-build.yaml
- README.md
- images/rekor/README.md
- images/rekor/config/main.tf
- images/rekor/main.tf
- images/rekor/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add a Rekor image.

- images/crossplane-aws/config/template.apko.yaml
- images/crossplane-azure/config/template.apko.yaml
This was flagging our linters. The upstream images *do* place the binaries in usr/local, but the entrypoint doesn't contain that path: https://github.com/crossplane-contrib/provider-aws/blob/master/cluster/images/provider-aws/Dockerfile
> Remove usr/local from entrypoint path.

- images/cert-manager/tests/main.tf
- images/prometheus-adapter/tests/cleanup.sh
- images/prometheus-adapter/tests/main.tf
- tflib/helm-cleanup/main.tf
This allows us to clean up resources provisioned via Helm, which will help with resource utilization and avoiding test conflicts across versions.
> Add a `helm-cleanup` module.

- README.md
- images/sigstore-scaffolding/README.md
- images/sigstore-scaffolding/config/main.tf
- images/sigstore-scaffolding/main.tf
- images/sigstore-scaffolding/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
These are supporting images for standing up Sigstore components, there isn't really a Helm chart that can be used for these in a meaningful way, but once these land we will use these to test the other main application images and replace our reliance on the upstream images 🤞 
Notes:
Notes:
Notes:
Notes:
Notes:
> Build the sigstore scaffolding images.

- README.md
- images/gitness/README.md
- images/gitness/config/main.tf
- images/gitness/config/template.apko.yaml
- images/gitness/main.tf
- images/gitness/tests/01-test.sh
- images/gitness/tests/main.tf
- main.tf
Notes: 99 vs. 137 MB
Notes: Two FPs. The upstream one has ~20 real ones.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add gitness server image.

- images/pulumi/configs/latest.apko.yaml
This image references python 3.11 specifically, which is currently python3, but which will this week become 3.12.
This unpins the image to let it be built with 3.12 when it becomes the latest.
> unpin pulumi from py3.11

- images/istio/configs/install-cni/main.tf
- images/istio/configs/install-cni/template.apko.yaml
- images/istio/install-cni.tf
- images/istio/main.tf
- images/istio/tests/main.tf
Notes: 
```
❯ docker images | grep cni
ttl.sh/tcnghia/images/new/istio-install-cni                           latest                                                             930e3539cf17   2 days ago      141MB
gcr.io/istio-release/install-cni                                      1.19.0-distroless                                                  dafe1cd98bcf   3 weeks ago     117MB
```
Looks like this is because of the compiled binaries being larger
```
☸ kind-kind in images on  istio-cni [?] via 🐹 v1.21.0 via 💠 default 
❯ tar tvf cni.upstream.tar | grep cni | grep bin              
drwxr-xr-x  0 0      0           0 Sep  1 08:08 opt/cni/bin/
-rwxr-xr-x  0 0      0    55115776 Sep  1 08:08 opt/cni/bin/istio-cni
-rwxr-xr-x  0 0      0    59572224 Sep  1 08:08 usr/local/bin/install-cni
☸ …
```
> Add istio-install-cni images

- images/jdk-lts/README.md
- images/jdk-lts/main.tf
- images/jre-lts/README.md
- images/jre-lts/main.tf
- main.tf
This is a precursor to switching `{jre,ldk}:latest` to track non-LTS after Java 21 (which is both!).
> Add `{jre,jdk}-lts` repos.

- .github/workflows/presubmit-build.yaml
- images/ctlog/README.md
- images/ctlog/config/main.tf
- images/ctlog/main.tf
- images/ctlog/tests/main.tf
- images/sigstore-scaffolding/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Create a `ctlog` image.

- images/sigstore-scaffolding/main.tf
- images/sigstore-scaffolding/tests/main.tf
This enables TUF in the Helm chart and swaps in a TUF image we build.
This also swaps in our build ctlog server image as the default.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Enable TUF, build `tuf-server`

- images/kubernetes-csi-livenessprobe/config/main.tf
- images/kubernetes-csi-livenessprobe/config/template.apko.yaml
- images/kubernetes-csi-livenessprobe/main.tf
Signed-off-by: Batuhan Apaydin <batuhan.apaydin@chainguard.dev>## Chainguard Images Pull Request Template
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> remove the package from config kubernetes-csi-livenessprobe

- images/aws-ebs-csi-driver/config/main.tf
> fix: add mount package to aws-ebs-csi-driver

- images/prometheus-node-exporter/tests/main.tf
- images/prometheus-node-exporter/tests/node-runs.sh
Correct settings in #1525, also update the script to use the random port.
Confirmed locally 
```
❯ k get daemonsets.apps -n prometheus-3dbf92fd prometheus-3dbf92fd-prometheus-node-exporter -o yaml | grep -i port             
app.kubernetes.io/name: prometheus-node-exporter
app.kubernetes.io/part-of: prometheus-node-exporter
helm.sh/chart: prometheus-node-exporter-4.23.1
jobLabel: node-exporter
name: prometheus-3dbf92fd-prometheus-node-exporter
app.kubernetes.io/name: prometheus-node-exporter
app.kubernetes.io/name: prometheus-node-exporter
app.kubernetes.io/part-of: prometheus-node-exporter
helm.sh/chart: prometheus-node-exporter-4.23.1
jobLabel: node-exporter
image: ttl.sh/tcnghia/images/prometheus-node-exporter:v1.6.1@sha256:65ddf4fc9b3b6466e928b429879b2a6b94d3a8efe37f5fd036adca954794c6a …
```
> prometheus-node-exporter test: correct settings in #1525 

- images/calico/main.tf
In the absence of digests, the default behavior is to reference `calico-node-driver-registrar` by the calico version, not the version we publish based on `kubernetes-csi-node-driver-registrar-2.9`).
This adds additional tags to calico's copy:
```
➜ crane ls k3d-k3d.localhost:5005/cgg/calico-node-driver-registrar
3.26.1-r15
latest
2.9.0-r2
2.9.0
3
3.26
3.26.1
2.9
2
v2
v2.9.0
v2.9.0-r2
v2.9
```
> add additional tags for calico's copy of node-driver-registrar

- images/istio/tests/main.tf
The current splitting logic assumes the last part of the repository is named `istio-proxy` or `istio-install-cni`. This removes such assumption so this test can be reused better.
> istio images tests: use more robust splitting logic

- images/dask-gateway/main.tf
This has been publishing to `cgr.dev/chainguard/dask-gateway-dask-gateway` and `cgr.dev/chainguard/dask-gateway-dask-gateway-server`, because the `target_repository` input is usually `cgr.dev/chainguard/dask-gateway`.
This accounts for the existing `dask-gateway` and appends either `""` or `"-server"`, so we'll get repo names like `cgr.dev/chainguard/dask-gateway` and `cgr.dev/chainguard/dask-gateway-server`.
After this we can withdraw the existing repos.
Request logs indicate the vast majority of traffic to these repos has been our own image building/moving infrastructure, and that no authenticated users have pulled it. There have been a total of 270 unauthenticated pulls from the two repos combined in the last 90 days.
> fix dask-gateway repo names

- tflib/publisher/main.tf
Bump version of `terraform-oci-provider` to `v0.0.10` to pick up latest fixes.
> feat: bump terraform-oci-provider to v0.0.10

- .github/workflows/release.yaml
we're seeing:
```
Warning  Evicted    3m28s  kubelet            The node had condition: [DiskPressure].
```
now on some legs of the build.
this bumps us up (slightly) to 4c runners, which also have _significantly_ larger disks
ref: https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners#machine-sizes-for-larger-runners
> bump release runner fanout to 4c runners

- images/prometheus-mongodb-exporter/README.md
- images/prometheus-mongodb-exporter/config/latest.apko.yaml
- images/prometheus-mongodb-exporter/config/main.tf
- images/prometheus-mongodb-exporter/main.tf
- images/prometheus-mongodb-exporter/tests/main.tf
- images/prometheus/main.tf
- images/prometheus/tests/main.tf
- main.tf
Moves `prometheus-mongodb-exporter` from the `prometheus` folder to its own folder, following the pattern in [this PR](https://github.com/chainguard-images/images/pull/1413). Added Helm chart test and README.
This is a refactoring change.
> Move prometheus-mongodb-exporter to its own folder

- images/node-lts/README.md
- images/node-lts/main.tf
- main.tf
This tracks what was done previously for JRE/JDK
> Add a `node-lts` repository.

- images/ctlog/config/main.tf
- images/rekor/config/main.tf
- images/rekor/main.tf
- images/sigstore-scaffolding/config/main.tf
- images/trillian/config/main.tf
We use the pattern `${{package.name}}-foo` so the suffix comes after the parent package name, but prior to the subcomponent.
> This corrects the suffix placement for several images.

- images/crossplane-aws/main.tf
- images/crossplane-azure/main.tf
This enables version-tagging crossplane provider images, in addition to tagging `:latest`.
> enable version-tagging crossplane-{aws,azure} images

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
ref: https://github.com/chainguard-images/images/pull/1570
> This was applied downstream but not here.

- images/istio/tests/main.tf
- images/istio/tests/test-gateway.sh
- images/istio/tests/virtualservice.yaml
Using a Job to curl on un under-provisioned test cluster may result in little retries. 
Also avoid cleaning up istiod before the gateway test.
> istio test: shell to curl & fix cleanup order

- .gitignore
- images/keycloak/README.md
- images/keycloak/config/latest.apko.yaml
- images/keycloak/config/main.tf
- images/keycloak/main.tf
- images/keycloak/tests/main.tf
- main.tf
Creation of a new image for Keycloak, including some tests.
Notes:
Notes:
Trivy scans returning zero vulns. Grype unlike trivy, doesn't currently filter out the false positives from our vuln feed, but once these are filtered out there are zero returned. 
Note, one additional vuln was found when doing package vuln scans (CVE-2023-4586), but wasn't glagged by trivy or grype. We're working to publish an advisory for this. It looks to be an issue in a transitive dependency of Keycloak which doesn't yet have a published fix.
Notes:
Notes:
Notes:
Notes:
Notes:
Helm test added - spins up container image in a local kind cluster, and will fail the test if the pod does not come up successfully in a ready state, and passing probes. Additional test added to spin up the container via docker and invoke …
> New image: Keycloak

- images/tekton/tests/test.sh
There was an upstream release bug where `latest` wasn't being updated correctly, so we pinned to a release (https://github.com/chainguard-images/images/pull/1426). This undoes the pin.
> tekton: test with latest release.yaml

- tflib/publisher/main.tf
- Related commits here https://github.com/chainguard-dev/terraform-provider-cosign/pull/83
- https://github.com/chainguard-dev/terraform-provider-cosign/pull/82
> use chainguard-dev/cosign:0.0.14 as it fixes duplicate attestation

- images/jdk/config/main.tf
- images/jre/config/main.tf
This happens to match the latest LTS once: wolfi-dev/os#6557 lands, which makes the transition easier.
> Have `cgr.dev/chainguard/{jre,jdk}` track latest non-LTS

- images/keycloak/README.md
Updating link to referenced bitnami helm chart used in the docs example. Previous link was from another chart that was originally used.
> Fix Keycloak README link

- images/istio/tests/test-injection.sh
Default is 30s, which is too short when test cluster has a lot of contention.
> istio test: increase pod wait time + clean up

- images/keda/tests/smoke-test.sh
This is copied from another instance just below in the file, but we missed this one.
> Avoid a race to create pods to wait on.

- images/keycloak/tests/main.tf
Minor update to test - which allows us to invoke it from other terraform image builds and pass in different arguments. Allows for better re-usability for future custom image builds.
> Parameterize args passed to helm test

- images/dynamic-localpv-provisioner/README.md
- images/dynamic-localpv-provisioner/config/main.tf
- images/dynamic-localpv-provisioner/main.tf
- images/dynamic-localpv-provisioner/tests/main.tf
- main.tf
Notes: We added bunch of runtime packages this is why the image end up having a little bit bigger size.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> dynamic-localpv-provisioner

- images/nfs-subdir-external-provisioner/README.md
- images/nfs-subdir-external-provisioner/config/main.tf
- images/nfs-subdir-external-provisioner/main.tf
- images/nfs-subdir-external-provisioner/tests/main.tf
- main.tf
Notes: I couldn't find the `4.0.18` version of the image in upstream because we built `4.0.18` but upstream only has `4.0.2`. So I compared our version with `4.0.2`, size is a little bit bigger. 
```shell
$ crane ls registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
v4.0.0
v4.0.1
v4.0.2
```
Notes:
- [] The container image was successfully loaded into a kind cluster.
Notes: I couldn't find an NFS Server implementation running on Kubernetes cluster.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> nfs-subdir-external-provisioner

- images/stunnel/main.tf
Elastic is asking to try out the stunnel image, but they want us to add `curl`.  Matt suggested we add curl to the dev variant in https://github.com/chainguard-dev/image-requests/issues/449#issuecomment-1752178605.
He also suggested that we add some tests, but I haven't been able to do that for the following reasons.
(1) stunnel requires a configuration file to start but only a sample is provided by default.  Starting stunnel involves: `stunnel /etc/stunnel/stunnel.conf`.  
(2) We could add a `stunnel.conf` file by including it as a sub-package but it requires a valid configuration as well.  We might be able to come up with a harmless use case to include in the `stunnel.conf` file but....
(3) stunnel is a TLS/SSL tunneling service, and it requires key/cert to work.  We could generate a …
> Adding curl to stunnel dev image variant

- monopod/pkg/commands/scaffold.go
Following the anatomy of the images detailed [here](https://docs.google.com/document/d/14devrKiCxFs3Eqrl9QH2jBgsCONGnXCOC9CxZUudbr8/edit#heading=h.od18w6wsqlib), we decided to rename the `configs` folder to `config` for all the new images created via scaffold command.
> chore: rename images folder from configs to config

- images/redis-bitnami/README.md
- images/redis-bitnami/config/main.tf
- images/redis-bitnami/main.tf
- images/redis-bitnami/tests/main.tf
- main.tf
Adds `redis-bitnami`, `redis-bitnami-sentinel`, and `redis-bitnami-cluster`.
Noteworthy:
- `redis-bitnami-cluster` appears unused in the helm chart, but I'm including it for completeness
- our existing `redis-sentinel` remains untouched. I'm chalking this up to "legacy" and leaving it as is to avoid affecting any existing customers using it. moving forward, we want to replace that with these images.
- `redis-sentinel` is a simple symlink to `redis-server` that the official `redis` distribution doesn't isolate, but bitnami chooses to use different startup scripts for this, hence the additional image
depends on: https://github.com/wolfi-dev/os/pull/6593
> add redis-bitnami-compat latest images

- images/grype/README.md
- images/grype/config/main.tf
- images/grype/main.tf
- images/grype/tests/main.tf
- main.tf
Notes: The delta looks to be that we add busybox
Notes: 228 packages found, 0 CVEs
Notes:
Notes:
<!--
You are confident that a customer can run this image in production. Functional tests are a requirement -- no exceptions.
Notes: Run through grype documentation examples
Notes:
Notes:
Notes:
- [] The image responds to SIGTERM (e.g., `docker kill $(docker run -d --rm cgr.dev/chainguard/nginx)`)
> adding grype image config

- images/kubernetes-csi-external-attacher/tests/deploy.sh
Seeing a lot of these leftover in downstream mega-module builds:
```
csi-attacher-relaxing-gorilla  csi-attacher-5689f748b7-d8j5g                          0 (0%)        0 (0%)      0 (0%)           0 (0%)         15m
csi-attacher-relaxing-gorilla  csi-attacher-5689f748b7-fvfzr                          0 (0%)        0 (0%)      0 (0%)           0 (0%)         15m
csi-attacher-glorious-cod      csi-attacher-5b5d67c6f8-4tr99                          0 (0%)        0 (0%)      0 (0%)           0 (0%)         15m
csi-attacher-glorious-cod      csi-attacher-5b5d67c6f8-j29fh                          0 (0%)        0 (0%)      0 (0%)           0 (0%)         15m
csi-attacher-relaxing-gorilla  csi-attacher-5689f748b7-hzpmb                          0 (0%)        0 (0%)      0 (0%)           0 (0%) …
```
> Cleanup `csi-attacher-*` when tests complete.

- go.mod
- go.sum
- monopod/pkg/commands/matrix.go
- monopod/pkg/commands/matrix_test.go
- monopod/pkg/constants/constants.go
This change to `monopod` should prevent the CI matrix builder from invoking a build for every image in the repo when the `withdrawn-images.txt` and `withdrawn-repos.txt` files are updated.
> Allow `withdrawn-*.txt` files to presubmit build CI

- withdrawn-repos.txt
More documentation in this [Chainguard internal document](https://docs.google.com/document/d/1iXnsaw2mrTa5mc1DxbBZtbrbVNMfpxmJwl7PU9m5DA8/edit).
Withdrawn image | Replacement
-- | --
cgr.dev/chainguard/calico | cgr.dev/chainguard/calicoctl
cgr.dev/chainguard/calico-pod2daemon | cgr.dev/chainguard/calico-pod2daemon-flexvol
cgr.dev/chainguard/dask-gateway-dask-gateway | cgr.dev/chainguard/dask-gateway
cgr.dev/chainguard/dask-gateway-dask-gateway-server | cgr.dev/chainguard/dask-gateway-server
cgr.dev/chainguard/external-attacher | cgr.dev/chainguard/kubernetes-csi-external-attacher
cgr.dev/chainguard/external-resizer | cgr.dev/chainguard/kubernetes-csi-external-resizer
cgr.dev/chainguard/helm-controller | cgr.dev/chainguard/flux-helm-controller
cgr.dev/chainguard/kustomize-controller | …
> Withdraw stale repos

- images/fluentd/config/template.apko.yaml
Remove the s6 dependency for fluentd so it respects command line arguments passed through k8s manifests. Also allows fluentd to run with a read-only filesystem.
> Make fluentd respect arguments

- images/cilium/README.md
- images/cilium/configs/operator/main.tf
- images/cilium/configs/operator/template.apko.yaml
- images/cilium/main.tf
- images/cilium/operator-generic.tf
- images/cilium/tests/main.tf
- main.tf
Notes:
```
❯ docker images | grep operator                                      
tcnghia/cilium-operator-generic                       latest              5d17548f4a16   4 hours ago    78MB
quay.io/cilium/operator-generic                       v1.14.2             bbfe2f667bb8   4 weeks ago    76MB
```
Notes:
Notes:
Notes:
Notes: Helm chart was used to test, but the current k3s cluster on CI won't be able to use this Helm chart. Test was done locally, and instruction included in PR.
Notes:
Notes:
Notes:
Notes:
Notes:
> cilium-operator: new image

- images/prometheus-mongodb-exporter/tests/main.tf
Instead of trying to be clever and waiting 10s then polling for another 20s, just wait 30s to see if the container is ready.
If no containers are ready after the initial 10s (like when the cluster is overloaded) then the kubectl invocation fails, causing a test flake.
> deflake prom-mongodb-exporter test

- images/prometheus-pushgateway-bitnami/README.md
- images/prometheus-pushgateway-bitnami/config/main.tf
- images/prometheus-pushgateway-bitnami/main.tf
- images/prometheus-pushgateway-bitnami/tests/02-healthy.sh
- images/prometheus-pushgateway-bitnami/tests/main.tf
- main.tf
- add prometheus-pushgateway-bitnami image
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> add prometheus-pushgateway-bitnami image

- images/gitlab/config/main.tf
- images/gitlab/main.tf
- images/gitlab/tests/main.tf
Notes:
- [] The Grype vulnerability scan returned 0 CVE(s).
Notes:
Found the following CVEs after scanning the image:
```
✔ Scanned for vulnerabilities     [3 vulnerabilities]
├── 0 critical, 0 high, 3 medium, 0 low, 0 negligible
└── 3 fixed
[0001]  WARN some package(s) are missing CPEs. This may result in missing vulnerabilities. You may autogenerate these using: --add-cpes-if-none
NAME              INSTALLED  FIXED-IN  TYPE       VULNERABILITY        SEVERITY
golang.org/x/net  v0.10.0    0.17.0    go-module  GHSA-qppj-fm5r-hxr3  Medium
golang.org/x/net  v0.10.0    0.17.0    go-module  GHSA-4374-p667-p6c8  Medium
golang.org/x/net  v0.10.0    0.13.0    go-module  GHSA-2wrh-6pvc-2jm9  Medium
0.71.0
```
Notes:
Notes:
Notes:
Notes:
Notes:
> add gitlab-pages image

- images/tigera-operator/tests/main.tf
When testing multiple tigera-operator installations, the names conflict. This attempts to resolve that conflict.
> tigera-operator deconflict helm chart name

- images/caddy/README.md
- images/caddy/config/main.tf
- images/caddy/config/template.apko.yaml
- images/caddy/main.tf
- images/caddy/tests/Caddyfile
- images/caddy/tests/index.html
- images/caddy/tests/main.tf
- images/caddy/tests/run_test.sh
- main.tf
@amouat and myself worked on getting support for Caddy 🎉 
Adding caddy image.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add caddy image

- images/gitlab/config/main.tf
- images/gitlab/main.tf
- images/gitlab/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> gitlab: add gitlab-shell image

- images/jre/tests/02-hello-world.sh
- images/jre/tests/HelloWorld.java
Refactor the JRE tests to make sure that files created for the test are cleaned up after it finishes and source control the `HelloWorld` class.
> refactor: improve JRE tests to clean up files/folders

- images/vault/tests/acceptance.sh
- images/vault/tests/main.tf
To allow deploying both `vault` and `vault-k8s` in the same time using the Helm chart without `still in use` error.
> Add ns randomizer for vault

- images/cilium/configs/hubble-relay/main.tf
- images/cilium/configs/hubble-relay/template.apko.yaml
- images/cilium/hubble-relay.tf
- images/cilium/main.tf
- images/cilium/tests/cilium-install.sh
- images/cilium/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> cilium: add hubble-relay image

- images/argocd/configs/main.tf
- images/argocd/configs/template.repo-server.apko.yaml
- images/argocd/configs/template.server.apko.yaml
- images/argocd/main.tf
- images/argocd/tests/main.tf
convert argocd module to support version streams.
notable is that this ends up removing `gpg` from `argocd` (not `argocd-repo-server`), which was included erroneously.
> convert argocd to version streamable config

- .github/workflows/release.yaml
Take advantage of: https://github.com/chainguard-dev/actions/pull/343
> Include error output in slack notifications

- images/argocd/main.tf
This had been pointing `:latest-dev` to the non-dev image.
> Fix argocd -dev tags

- images/bash/config/main.tf
- images/bash/configs/latest.apko.yaml
- images/bash/main.tf
- images/bash/tests/main.tf
- images/bash/tests/runs.sh
The config module was defined in https://github.com/chainguard-images/images/pull/1445 (seemingly by accident) but not yet used. This uses the module and deletes the config yaml.
Notably, the current live image runs as root and doesn't even define a nonroot user. With this change, it'll include a nonroot user as well.
I've also added a test to demonstrate that the user runs as root.
> fix up bash image

- images/crossplane-aws/main.tf
- images/crossplane-aws/tests/install.sh
- images/crossplane-aws/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add the remaining AWS crossplane components as images.

- images/jre/tests/02-hello-world.sh
Add the ability to specify sources/targets other than 8 in the JRE and JDK tests.
Removing the checklist as this does not impact the final image, only the tests of the image.
> feat: allow specifying source/target in JRE tests

- images/haproxy/configs/latest.apko.yaml
match the upstream image for the cases where k8s is running it without any `cmd`
```
➜ crane config haproxy:2.6.14-alpine | jq
...
"Cmd": [
"/bin/sh",
"-c",
"#(nop) ",
"CMD [\"haproxy\" \"-f\" \"/usr/local/etc/haproxy/haproxy.cfg\"]"
],
"Image": "sha256:e6ad97047b8546a6d81d7e99ea2363ca36f219323869f6b4e87105f6942ab7be",
"Volumes": null,
"WorkingDir": "",
"Entrypoint": [
"docker-entrypoint.sh"
],
```
> add default cmd to haproxy

- images/atlantis/README.md
- images/atlantis/config/main.tf
- images/atlantis/main.tf
- images/atlantis/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes: No functional tests at this moment
Notes:
Notes:
Notes:
> Add `atlantis` image

- images/jre/tests/main.tf
Expose the source and target environment variables in Terraform so the test can have source and target levels specified other than the original 8.
> feat: expose javac source/target vars in Terraform

- images/cilium/configs/hubble-ui-backend/main.tf
- images/cilium/configs/hubble-ui-backend/template.apko.yaml
- images/cilium/configs/hubble-ui/main.tf
- images/cilium/configs/hubble-ui/template.apko.yaml
- images/cilium/hubble-ui-backend.tf
- images/cilium/hubble-ui.tf
- images/cilium/main.tf
- images/cilium/tests/cilium-install.sh
- images/cilium/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add cilium-hubble-ui and cilium-hubble-ui images

- images/tomcat/README.md
- images/tomcat/config/main.tf
- images/tomcat/config/template.apko.yaml
- images/tomcat/main.tf
- images/tomcat/tests/main.tf
- images/tomcat/tests/run.sh
- images/tomcat/tests/smoke.sh
- main.tf
Notes:
```
imgsize ttl.sh/jason/tomcat@sha256:a4c3e5e95f4e289d24211fd1c2a4978748763d41cd3d78c865fc02951c418b8f 
89M
imgsize tomcat
210M
```
Notes:
```
NAME         INSTALLED  FIXED-IN  TYPE          VULNERABILITY  SEVERITY 
tomcat-jdbc  10.1.15              java-archive  CVE-2016-6325  High      
tomcat-jdbc  10.1.15              java-archive  CVE-2016-5425  High
```
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> new image: tomcat

- images/istio/tests/main.tf
This is a cluster resource with non-customizable name. It interferes with running multiple Istio tests in parallel in the same cluster.
See https://github.com/istio/istio/blob/master/manifests/charts/base/templates/default.yaml
> istio test: don't install CRD validation webhook

- images/gradle/config/template.apko.yaml
This was dropped in https://github.com/chainguard-images/images/pull/1749
> re-add JAVA_HOME for gradle image

- images/trino/README.md
- images/trino/config/main.tf
- images/trino/main.tf
- images/trino/tests/container-test.sh
- images/trino/tests/main.tf
- main.tf
- tflib/accts/main.tf
Notes:
Notes: The CVEs left cannot be fixed due to shaded JARs (JARs that embed their transitive deps)
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Create trino:latest image

- images/argocd/main.tf
Previously we'd been building updates to both argocd and argocd-repo-server into the same repository (argocd-repo-server).
> fix argocd:latest(-dev) tagging

- images/node/config/main.tf
This happens to match the latest LTS once: https://github.com/wolfi-dev/os/pull/6556 lands, which makes the transition easier.
> Have `cgr.dev/chainguard/node` track latest non-LTS

- images/prometheus-elasticsearch-exporter/tests/main.tf
Isolate tests in a namespace to prevent collision during the build process.
> Fix `prometheus-elasticsearch-exporter`

- images/pulumi/examples/smoketest-python/requirements.txt
The versions in the test are very outdated.
> pulumi: unpin the versions used in python sdk test

- images/external-dns/tests/e2e.sh
I noticed we were trying to cleanup the same PID in a test that ended up hanging:
```
+ kill -9 454251
+ [[ 42.42.42.42 == \4\2\.\4\2\.\4\2\.\4\2 ]]
+ cleanup_pid
+ kill -9 454251
```
> Rely on the trap to kill port-forward

- images/rabbitmq-cluster-operator/README.md
- images/rabbitmq-cluster-operator/config/main.tf
- images/rabbitmq-cluster-operator/main.tf
- images/rabbitmq-cluster-operator/tests/main.tf
- images/rabbitmq-cluster-operator/tests/test.sh
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> rabbitmq-cluster-operator: new image

- images/crossplane/README.md
- images/crossplane/config/main.tf
- images/crossplane/main.tf
- images/crossplane/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add crossplane images

- images/argo/README.md
- images/argo/cli.tf
- images/argo/configs/cli/main.tf
- images/argo/configs/cli/template.apko.yaml
- images/argo/configs/exec/main.tf
- images/argo/configs/exec/template.apko.yaml
- images/argo/configs/workflowcontroller/main.tf
- images/argo/configs/workflowcontroller/template.apko.yaml
- images/argo/exec.tf
- images/argo/main.tf
- images/argo/tests/check-argo-workflow.sh
- images/argo/tests/main.tf
- images/argo/workflowcontroller.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> : add argo-workflows

- images/rabbitmq-messaging-topology-operator/README.md
- images/rabbitmq-messaging-topology-operator/config/main.tf
- images/rabbitmq-messaging-topology-operator/main.tf
- images/rabbitmq-messaging-topology-operator/tests/main.tf
- images/rabbitmq-messaging-topology-operator/tests/test.sh
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> rabbitmq-messaging-topology-operator: new image

- images/cilium/tests/cilium-install.sh
Also check for any leftover quay.io reference.
> cilium: fix command line option for test to use right image

- images/cilium/tests/cilium-install.sh
- images/cilium/tests/cypress.yaml
- images/cilium/tests/cypress/cypress.config.js
- images/cilium/tests/cypress/spec.cy.js
Since everything is rendered by Javascript, we can't just `curl` for a smoke test but have to use something more serious.
> cilium: use `cypress` to test the Hubble (react) Ui

- images/ingress-nginx-controller/config/latest.apko.yaml
Attempt to fix failing test
```
F1027 02:33:19.950616       1 nginx.go:197] Error creating file watchers: lstat /etc/nginx/geoip/: no such file or directory
```
> ingress-nginx-controller: attempt to fix missing directory

- .github/workflows/release.yaml
Rather than putting a random person's face next to the messages
> Send release failure Slack messages as chainguardian

- images/cilium/tests/k3d.yaml
- images/cilium/tests/main.tf
Use at least 2 nodes to exercise cross-node connectivity.
> cilium: bump the test cluster nodes

- images/trust-manager/tests/main.tf
Update trust-manager tests so they pass with the new version of the package. The output of the new version is different from before, which means this test might need to be updated to make it more resilient to output changes.
> fix: update trust-manager tests

- Makefile
- TERRAFORM.md
Add new `make` targets to run Terraform. This uses the recommended `terraform apply` command that was previously documented in `TERRAFORM.md`. It also updates the `TERRAFORM.md` to suggest the use of `make` now and specifies how variables should be passed in to make.
> feat: add new make targets and documentation

- tflib/publisher/main.tf
This fixes the ever-growing .sig manifests for images that don't change very often.
> Replace signatures instead of appending them

- images/cilium/tests/cilium-install.sh
The default values 1.1.1.1 and 1.0.0.1 are blocked in many networks.
> cilium-test: use 8.8.8.8 & 8.8.4.4 for external ips

- .github/workflows/release.yaml
We'd been producing version tags for these images for some compatibility reasons.
We've since stopped version tagging some of them just by migrating to `oci_tag` from the `version-tags` module. This disables new public version tag creation for everything else left straggling.
> disable version tags for all stragglers

- images/keycloak/tests/01-keycloak-production-mode.sh
- images/keycloak/tests/keycloak-production-mode.sh
- images/keycloak/tests/main.tf
We already have a helm test which runs keycloak in dev mode. This introduces a new shell test which runs Keycloak in production mode. This requires a keystore to be created and volume mounted.
> Adding additional test to validate keycloak startup in production mode

- images/node/tests/01-dockerfile.sh
This was leaving a smoke-test image behind.
> Add cleanup for node smoke-test

- images/atlantis/tests/main.tf
This allows us to reuse the test without conflicts.
> Add random suffix to atlantis helm test

- images/aws-load-balancer-controller/tests/main.tf
The helm-cleanup doesn't seem to cleanly remove the webhook, which means other installations running in the same cluster get blocked on webhook errors.
> disable aws-lb tests until they're good

- images/zookeeper/config/template.apko.yaml
The bitnami zookeeper charts use nc -q in their probes, which breaks our tests: https://github.com/bitnami/charts/pull/20572
> Add netcat-openbsd to zookeeper image

- images/aws-load-balancer-controller/tests/main.tf
This doesn't do anything yet because tests are disabled, but when we re-enable them we'll want to control the chart version.
> aws-lb: add chart_version for test

- images/prometheus-pushgateway-bitnami/config/main.tf
- images/prometheus-pushgateway-bitnami/main.tf
This dependency had been brought in by a runtime dep in the compat package, which was removed in https://github.com/wolfi-dev/os/commit/321780e52434e1dc0f5734c50d48405fc9e30503 to avoid conflicts with other users of this config module.
> include prometheus-pushgateway in its image by default

- images/sigstore-scaffolding/main.tf
- images/sigstore-scaffolding/tests/main.tf
- images/sigstore-scaffolding/tests/values.tf
- images/timestamp-authority/README.md
- images/timestamp-authority/config/main.tf
- images/timestamp-authority/main.tf
- main.tf
20MB vs 45MB
Notes:
- [] The Grype vulnerability scan returned 0 CVE(s).
Notes:
opened https://github.com/wolfi-dev/os/pull/8234 to address them
Notes:
Notes:
- [ x The application is accessible to the user/cluster/etc. after start-up.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Sigstore timestamp authority images

- images/pulumi/examples/smoketest-python/requirements.txt
Pin the version of the Pulumi Python package to the same version that's currently being used in the image to avoid issues with divergent configurations.
This intends to fix the test that's currently failing on CI for us.
> fix: pin Pulumi to the image version

- Makefile
Improve the way make targets check for mandatory variables and ensure the `apko-build` and `apko-build-alpine` targets do not require the Terraform variables to be set to run.
Also remove the re-assignment of Terraform variables, as those are unneeded.
> feat: improve Makefile checks

- images/kubeflow-pipelines/configs/main.tf
- images/kubeflow-pipelines/configs/template.api-server.apko.yaml
- images/kubeflow-pipelines/configs/template.cache-deployer.apko.yaml
- images/kubeflow-pipelines/configs/template.cache-server.apko.yaml
- images/kubeflow-pipelines/configs/template.frontend.apko.yaml
- images/kubeflow-pipelines/configs/template.metadata-writer.apko.yaml
- images/kubeflow-pipelines/configs/template.persistenceagent.apko.yaml
- images/kubeflow-pipelines/configs/template.scheduledworkflow.apko.yaml
- images/kubeflow-pipelines/configs/template.viewer-crd-controller.apko.yaml
- images/kubeflow-pipelines/main.tf
- images/kubeflow-pipelines/tests/main.tf
- images/kubeflow-pipelines/tests/smoke-test.sh
Notes:
Notes: due to some npm packages
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> kubeflow pipelines frontend

- images/kyverno-policy-reporter/config/main.tf
- images/kyverno-policy-reporter/main.tf
- images/kyverno-policy-reporter/tests/main.tf
- images/kyverno/tests/main.tf
Take the packages as an input, so other instantiations can install other versions.
Also deconflict the helm test, and remove unnecessary test for regular Kyverno.
> make kyverno-policy-controller config reusable

- images/ko/config/latest.apko.yaml
Sometimes, when building projects that depend on private modules, go will attempt to invoke git to download those modules.  This causes Predictably Bad Things to happen:
2023/10/19 21:45:46 Using base cgr.dev/chainguard/static:latest@sha256:ef5add7fd46cf1ce7d33d6de517833ac5c7e749db9b15249f9c472a772f3af27 for ..redacted...
2023/10/19 21:45:47 Building ..redacted... for linux/s390x
2023/10/19 21:45:47 Building ..redacted... for linux/386
2023/10/19 21:45:47 Building ..redacted... for linux/arm/v7
2023/10/19 21:45:47 Building ..redacted... for linux/amd64
2023/10/19 21:46:17 Building ..redacted... for linux/arm64
2023/10/19 21:46:17 Building ..redacted... for linux/arm/v6
Error: failed to publish images: error building "ko://..redacted...": build: go build: exit status 1: go: downloading …
> Add git to the ko image

- images/temporal-ui-server/README.md
- images/temporal-ui-server/config/main.tf
- images/temporal-ui-server/config/template.apko.yaml
- images/temporal-ui-server/main.tf
- images/temporal-ui-server/tests/main.tf
- images/temporal-ui-server/tests/run.sh
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add temporal-ui-server

- images/hugo/README.md
This PR is to update the Hugo README to bring it inline with template README.  It addresses issue https://github.com/chainguard-images/images/issues/1546.  As such the only relevant item from the checklist is below.
> [Docs] README update: hugo #1546

- images/cert-manager/tests/helm.sh
- images/cert-manager/tests/main.tf
- main.tf
Using the same technique introduced in #1858 
This now passes for me locally:
```
terraform apply -target=module.spire-again-for-testing -target=module.spire -auto-approve
```
> cert-manager: deconflict helm tests

- images/memcached-exporter-bitnami/README.md
- images/memcached-exporter-bitnami/config/main.tf
- images/memcached-exporter-bitnami/main.tf
- images/memcached-exporter-bitnami/tests/main.tf
- main.tf
- _from 86.5 MB to 16.3 MB_ 
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> memcached-exporter bitnami variant

- images/cert-manager/tests/helm.sh
- images/cert-manager/tests/main.tf
Running multiple of these on a crowded cluster makes this take longer.
> give cert-manager tests more time to happen and teardown

- images/ntia-conformance-checker/README.md
- images/ntia-conformance-checker/config/main.tf
- images/ntia-conformance-checker/main.tf
- images/ntia-conformance-checker/tests/main.tf
- images/ntia-conformance-checker/tests/sbom.json
- main.tf
> Add `ntia-conformance-checker` image

- images/sigstore-policy-controller/README.md
- images/sigstore-policy-controller/config/main.tf
- images/sigstore-policy-controller/main.tf
- images/sigstore-policy-controller/tests/chainguard-images.yaml
- images/sigstore-policy-controller/tests/e2e_test.sh
- images/sigstore-policy-controller/tests/main.tf
- images/sigstore-policy-controller/tests/signed-image.yaml
- images/sigstore-policy-controller/tests/unsigned-image.yaml
- main.tf
Notes:
Notes:
A single low CVE from the package:
```
NAME                           INSTALLED  FIXED-IN  TYPE       VULNERABILITY        SEVERITY 
github.com/sigstore/cosign/v2  v2.2.0     2.2.1     go-module  GHSA-vfp6-jrw2-99g9  Low
```
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add an image for `sigstore/policy-controller`

- images/memcached/configs/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> add entrypoint and environment variables memcached

- images/qdrant/README.md
- images/qdrant/config/main.tf
- images/qdrant/config/template.apko.yaml
- images/qdrant/main.tf
- images/qdrant/tests/main.tf
- main.tf
71MB vs. 163MB
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add qdrant image.

- images/kubernetes-event-exporter/README.md
- images/kubernetes-event-exporter/configs/main.tf
- images/kubernetes-event-exporter/main.tf
- images/kubernetes-event-exporter/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Adding kubernetes-event-exporter

- images/hugo/README.md
This PR is just to update the README for the Hugo image. This update provides some more context around the application setup, corrects a few broken commands, and removes the unnecessary **Image Variants** section (now in a new tab).
I haven't made a PR here in a while so let me know if I did anything incorrectly.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> updating Hugo image README

- images/solr/README.md
- images/solr/config/main.tf
- images/solr/config/template.apko.yaml
- images/solr/main.tf
- images/solr/tests/main.tf
- images/solr/tests/runs.sh
- main.tf
328MB vs. 350MB
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add Apache Solr image.

- images/dependency-track/README.md
- images/dependency-track/config/main.tf
- images/dependency-track/config/template.apko.yaml
- images/dependency-track/main.tf
- images/dependency-track/tests/main.tf
- images/dependency-track/tests/runs.sh
- main.tf
293MB vs. 310MB
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add a Dependency Track image.

- images/minio/main.tf
Tagging was removed in https://github.com/chainguard-images/images/pull/1840 after disabling version tags for everything in #1819 
However, https://github.com/chainguard-images/images/pull/1906 re-enabled them for minio, so we need to re-apply those tags again in the TF.
> re-add version tags for minio

- images/newrelic-k8s-events-forwarder/tests/main.tf
Newrelic k8s-events-forwarder was hitting port conflicts. I added a random integer for the port to help alleviate the conflicts. Ideally this would make use of FREE_PORT but there's no way to get at it from terraform yet.
> Fix newrelic k8s events forwarder test

- images/erlang/README.md
- images/erlang/config/main.tf
- images/erlang/config/template.apko.yaml
- images/erlang/main.tf
- images/erlang/tests/hello-world.sh
- images/erlang/tests/main.tf
- main.tf
Notes:
115 MB vs 1.39GB (erlang:latest)
Notes:
Notes:
I didn't test in a cluster, but I did test in docker.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Create latest erlang image

- images/memcached/config/main.tf
- images/memcached/main.tf
This is mostly just renaming `configs` to `config`, since it already had a `main.tf` in it.
> migrate memcached to config module

- images/calico/README.md
- images/haproxy-ingress/README.md
- images/helm/README.md
Another PR with some README updates. These are mostly small formatting improvements to the READMEs for the `calico`, `helm`, and `haproxy-ingress` images. 
As with previous updates, I'd like approval from someone from Dev Enablement before this gets merged. Thanks!
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> minor updates to a few READMEs

- images/zookeeper/config/template.apko.yaml
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> add coreutils to zookeeper

- images/k8ssandra-operator/README.md
- images/k8ssandra-operator/config/main.tf
- images/k8ssandra-operator/config/template.apko.yaml
- images/k8ssandra-operator/main.tf
- images/k8ssandra-operator/tests/main.tf
- main.tf
Part of https://github.com/chainguard-dev/image-requests/issues/517
Notes:
```sh
$ imgsize k8ssandra/k8ssandra-operator
26M
$ imgsize ttl.sh/wlynch/k8ssandra-operator:latest@sha256:3c6ba79a1c2b39a2cbae529fe99c1f4d43cc277f21e27efdf1bc8e2d4d55e8aa
17M
```
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add k8ssandra-operator

- images/ml-metadata-store-server/README.md
- images/ml-metadata-store-server/config/main.tf
- images/ml-metadata-store-server/main.tf
- images/ml-metadata-store-server/tests/main.tf
- images/ml-metadata-store-server/tests/ml-metadata-test.py
- images/ml-metadata-store-server/tests/ml-metadata-test.sh
- main.tf
Needs https://github.com/wolfi-dev/os/pull/9703
Notes:
12M vs 68M
Notes:
Notes:
N/A
Notes:
Notes:
Notes:
Notes:
See python test
Notes:
Notes:
Notes:
> New image: ml-metadata-store-server

- images/sqlpad/README.md
- images/sqlpad/config/main.tf
- images/sqlpad/config/template.apko.yaml
- images/sqlpad/main.tf
- images/sqlpad/patches/helm.patch
- images/sqlpad/tests/02-curl-test.sh
- images/sqlpad/tests/03-helm-test.sh
- images/sqlpad/tests/EXAMPLE_TEST.sh
- images/sqlpad/tests/main.tf
- main.tf
Notes:
Notes: **Reduced from 110 CVEs to 0 CVEs**
Notes:
Notes: 
Notes: N/A
Notes: The upstream helm chart has an outdated version of `postgresql` chart as dep. Will work only when we use updated version `postgresql 13.2.23` in upstream charts https://github.com/sqlpad/sqlpad/blob/f42ce1a84e1327e69178f38e7b3a2462dcaeeb7c/sqlpad-charts/requirements.yaml#L313.2.23
Notes:
Notes:
Notes:
Notes:
Notes:
> adds sqlpad image

- images/k8ssandra-operator/config/main.tf
Fix the extra packages after the change to the `k8ssandra-operator-compat` package to remove the runtime dependency on `k8ssandra-operator`.
> fix: add dependency on k8ssandra-operator to image

- images/temporal-admin-tools/config/main.tf
- images/temporal-admin-tools/config/template.apko.yaml
- images/temporal-admin-tools/tests/run.sh
I feel there's missing compat packages which are needed for symlink and apko.yaml is needed to modify to use correct entry point and permissions, the original PR is here https://github.com/chainguard-images/images/pull/1917 
The Dockerfile is here https://github.com/temporalio/docker-builds/blob/main/admin-tools.Dockerfile#L30-L36
> fix image and use compat packages

- images/keycloak/config/main.tf
Removing packages which are already defined as runtime dependencies in the [keycloak wolfi package](https://github.com/wolfi-dev/os/blob/56be435602874b7aa055a5d16d04d8ba57cad927/keycloak.yaml#L11). Also the JDK was defined here but is not required, so this should reduce the size of the image.
> Remove packages which are defined in the package as runtime dependencies

- images/postgres/tests/tls.sh
If we run multiple tests concurrently they conflict on the network name.
```
Cleaning up...
+ docker rm -f postgres_server postgres_client
Error response from daemon: No such container: postgres_server
Error response from daemon: No such container: postgres_client
+ docker network rm postgres_network
Error response from daemon: network postgres_network is ambiguous (2 matches found based on name)
```
> deconflict postgres_network

- images/cilium/tests/cilium-install.sh
Newest stable version of Cilium CLI includes a packet drop calculation logic that needs `jq` in the image, which we don't bundle.
Temporarily pin this back to v0.15.17 to make the test pass again.
> Use older cilium cli to test

- images/cilium/tests/cilium-install.sh
This test uses `jq` which we didn't bundle.
> cilium: skips the no-unexpected-packet-drops test

- images/busybox/wolfi.tf
- images/static/wolfi.tf
This blocks some downstream checks where the SBOMs we're producing aren't fully valid yet.
> temporarily disable check-sbom where it's enabled

- images/postgres/config/main.tf
Point to new entrypoint location in /usr/bin
Context: https://github.com/wolfi-dev/os/issues/9903
Blocked on: https://github.com/wolfi-dev/os/pull/9905 (or another fix)
> postgres: set entrypoint to /usr/bin

- images/tigera-operator/tests/helm.sh
The latest helm chart seems to rely on a flag that isn't defined in the latest release to uninstall, which causes the test to fail.
> tigera: pin helm chart version

- images/ingress-nginx-controller/config/latest.apko.yaml
- images/ingress-nginx-controller/image.yaml
The latest release of ingress-nginx-controller seems to add a dependency on the directory `/etc/ingress-controller/telemetry` existing and being writeable (seemingly https://github.com/kubernetes/ingress-nginx/pull/10470)
This was released last week and picked up in Wolfi here: https://github.com/wolfi-dev/os/pull/10240
This path wasn't defined in our image, so the pod never got ready and the Helm test failed.
> ingress-nginx-controller: fix for latest release

- images/cassandra/config/template.apko.yaml
This reverts commit 98a1b2ce273e08e8c9989860cf0f215c7c9b4799.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Revert "cassandra: fix path (#1987)"

- images/busybox/alpine.tf
- images/busybox/main.tf
- images/busybox/wolfi.tf
We don't version-tag these in public anymore, so just remove the cruft and simplify.
> busybox: remove version tags

- images/k8s-sidecar/tests/02-smoke.sh
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> free-port for port-forward k8s-sidecar

- images/kubernetes-event-exporter/tests/main.tf
This is a small tweak to the terraform for an existing image, to ensure that it cleans up the previous terraform test after completion.
> Add helm cleanup module for kubernetes-event-exporter

- images/vector/tests/main.tf
Tweaks to the vector terraform tests - to allow them to be invoked from other modules and be re-used. This includes support for specifying an alternative git tag for the helm tests.
> Update vector tests to allow them to be invoked from another module

- images/consul/config/main.tf
- images/consul/config/template.apko.yaml
- images/consul/main.tf
- images/terraform/config/main.tf
- images/terraform/config/template.apko.yaml
- images/terraform/main.tf
- images/vault/configs/vault/main.tf
- images/vault/configs/vault/template.apko.yaml
- images/vault/vault.tf
This ensures that even if these images are built in the presence of BUSL-licensed versions of these packages, they will choose the latest MPL versions.
Vault < 1.15
Consul < 1.17
Terraform < 1.6
> ensure Hashi images are built from MPL packages

- images/consul/config/template.apko.yaml
- images/consul/main.tf
Follow up to #2025 pinning the entrypoint subpackages below 1.17 as well.
> pin the consul entrypoint packages as well

- images/powershell/root.tf
This was unused, since we only tagged `:latest` and `:latest-dev`.
> powershell: remove unused version-tags module invocation

- .github/workflows/release.yaml
Similar to #1958 
Today we run the scheduled release with each image sharded onto its own hosted runner. We're approaching the shard limit of 256 (currently 241), so instead we'll randomly shard the builds into 4 shards (~60 images per shard) that run on the 64-core GH runner instance.
Randomly sharding helps prevent noisy neighbors that tend to be near each other alphabetically (`crossplane` and `crossplane-aws` and `crossplane-azure`).
Smaller shards would lower the impact of noisy neighbors, and could let us run on smaller hosted runners. Larger shards lower build times, since subsequent builds can share the same APK cache, and k3s cluster spin-up time can be amortized.
This also removes the last use of `generate-matrix` -- after this lands, we can drop that action and `monopod matrix` …
> shard release workflow

- images/go/README.md
- images/node/README.md
This PR contains updates to the READMEs for the `node` and `go` images. Fingers crossed that the new workflow doesn't cause issues with these updates.
Looking for DevEn approval before this should be merged, thank you!
> Improvements to Go + Node Image READMEs

- images/coredns/tests/main.tf
When deploying CoreDNS via Helm chart, it seems the chart isn't adding the suffix `-coredns` any longer to the deployments and services. Remove the references that had that from our tests too so they can successfully pass.
> fix: remove -coredns suffix from CoreDNS tests

- images/nginx/README.md
- images/nginx/metadata.hcl
This PR cleans up the Nginx Image README a bit. It uses the same example as the current README, but reframes it so it doesn't assume the reader is looking at the README from within the images repository. I also cleaned up the note on breaking changes to make it into the compatibility notes section.
> Updating Nginx README

- images/jdk/README.md
- images/jre/README.md
Quick update to improve the content of the JDK and JRE READMEs. Both READMEs follow the same example, so other than one sentenace calling out the specific Image these two READMEs should be identical.
> updating JDK + JRE READMEs

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
- .github/workflows/withdraw-images.yaml
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> pin SHAs for cosign and crane in our release workflow

- images/google-cloud-sdk/config/template.apko.yaml
The package builds with Python 3.12 now, and expresses its own dependency on 3.12, so the image build doesn't need to pin a version.
> google-cloud-sdk: fix image build

- images/prometheus-config-reloader/tests/cleanup.sh
- images/prometheus-config-reloader/tests/main.tf
Helm was leaving behind CRDs created as part of a test. Adding cleanup script to ensure no data is left behind when the test concludes
> Add script to cleanup CRDs

- monopod/pkg/lint/rules.go
This check is not as necessary now that we're setting archs in TF
If a YAML specifies an unknown arch, the build will fail loudly.
Specifying `archs` at all is weird enough reviewers should catch it (🤞).
In some cases we _want_ to specify `archs` to limit the image to one arch (e.g., #2094)
So let's just remove the lint check.
> remove lint check for archs in YAMLs

- main.tf
We believe there are no users of these platforms. If you're finding this PR because you use them, please reach out to tell us how!
> alpine: drop 386 and arm/v6 archs

- images/qdrant/tests/main.tf
upstream changed the chart to use a `semVer` check for the readiness probe: https://github.com/qdrant/qdrant-helm/blob/main/charts/qdrant/templates/statefulset.yaml#L122
rather than fork the chart to change this to support our psuedo_tag, just leverage the existing `startupProbe` as a ~similar check. while they're not identical, the pod will still block on `Running` until the `startupProbe` succeeds, which is enough of a signal for `helm`
> use startupProbe since readinessProbe value is locked behind semVer

- images/cassandra-reaper/config/main.tf
- images/cassandra-reaper/config/template.apko.yaml
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> fix the extra_packages for from private image reference

- TERRAFORM.md
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add example of single arch.

- images/cassandra-reaper/tests/smoke-test.sh
We are creating a FIPS variant of an image, due to public reference, we hit an issue due to OOM Kill, so, I have to increase the resources in public image: 
https://github.com/chainguard-images/images-private/actions/runs/7661822108/job/20881934558?pr=1837#step:16:31639
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> increase resources due to OOM Kill

- images/cassandra-reaper/tests/smoke-test.sh
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> remove stargate from CRD to prevent its being deployed

- images/prometheus-cloudwatch-exporter/config/latest.apko.yaml
- images/prometheus-cloudwatch-exporter/config/main.tf
This is a small terraform tweak to allow the DK packages to be overridden when module is invoked
> Allow JDK packages to be overridden when module is invoked

- images/kubernetes-event-exporter/tests/logs.sh
- images/kubernetes-event-exporter/tests/main.tf
remove the second helm release that `logs.sh` was creating in favor of the one spun up by the helm provider.
also simplify the log checking by plumbing some values through
> dedupe tests

- images/redis-bitnami/tests/main.tf
workaround no longer needed: https://github.com/bitnami/charts/pull/22223
> remove the workaround

- .github/workflows/presubmit-build.yaml
- images/cert-manager/tests/main.tf
- main.tf
moving this out of `main.tf` to avoid the complicated terraform conditionals needed to support the presubmit unique local registry (`registry.local:5000`) vs the postsubmit remote (`cgr.dev`) registry.
This also makes it more flexible for local users to configure things based on their own local registry setup.
> scope presubmit imagetest overrides to presubmit ci

- images/kafka/config/main.tf
- images/kafka/config/template.apko.yaml
This fixes an issue where the kafka user couldn't create a bitnami config as it didn't have access to /bitnami. This also moves Kafka and the JVM to extra packages so that other variants may be used
> fix(kafka): Use extra packages, grant access to /bitnami

- images/kubernetes-event-exporter/tests/logs.sh
the previous terms are too specific to introspecting the same container. in a concurrent environment (like CI) where the checks happen after the event for `event-exporter` has passed, the test will fail.
this changes the test to use a much more broad yet still representative set of matching terms
> change the match terms

- images/cassandra/config/main.tf
- images/cassandra/config/template.apko.yaml
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> use jdk 11 and cassandra packages as extra

- images/cass-config-builder/config/main.tf
We removed the `openjdk-8-default-jvm` runtime dependency from the package itself, so, we have to add it here:
- https://github.com/wolfi-dev/os/pull/12184
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> add openjdk-8-default-jvm to the extra_packages

- images/management-api-for-apache-cassandra/config/main.tf
We created this [PR](https://github.com/wolfi-dev/os/commit/e0984a5a4af16bf75fcf5fc98075d056a9f8ebc5) to remove the runtime dependency from cassandra itself since this was the package where installs openjdk-8 to the management-api image so as we removed this runtime dependency we should add openjdk-11 to extra_images of the image. 
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> add openjdk-11 to management-api-for-apache-cassandra

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
temporarily removing the shard randomizer since its making it very difficult to debug test flakes.
there's a chance this is forever removed now that `imagetest` exists to properly fix the issues the randomizer was meant to "fix".
> temporarily remove sharding randomization

- .github/workflows/release.yaml
uses a [gha job summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) to aggregate the test results
this is a primitive table to start, but we can flush this out further with links and details once the initial GHA madness is confirmed to work.
I tested this on a private repo, and kept this small, so I'm hopeful 🤞. either way, this doesn't touch the actual release process so the side effects are negligible, ci is always red nowadays anyways 😮‍💨
> create a build job summary

- .github/workflows/release.yaml
prevents the summary job from getting skipped if/when there are errors in the build
> always build the summary

- images/prometheus-logstash-exporter/README.md
- images/prometheus-logstash-exporter/config/main.tf
- images/prometheus-logstash-exporter/config/template.apko.yaml
- images/prometheus-logstash-exporter/main.tf
- images/prometheus-logstash-exporter/metadata.yaml
- images/prometheus-logstash-exporter/tests/main.tf
- images/prometheus-logstash-exporter/tests/values/logstash.values.yaml
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add prometheus-logstash-exporter image

- images/prometheus-logstash-exporter/tests/main.tf
- tflib/imagetest/helm/main.tf
An empty `values_file` parameter would generate a bad helm command. This change just ignores the `--values` line corresponding to values files if the `values_file` parameter is omitted.
Converted the prometheus-logstash-exporter image tests over to use the helm module as a test
> Tflib imagetest/helm values file fix

- images/management-api-for-apache-cassandra/config/template.apko.yaml
We pull in cassandra which needs python-3.11 specifically.
> Drop explicit python3 dep

- images/zig/README.md
Fixes an external link in zig's README.
> Fix: Wasmer link in zig README

- images/cilium/configs/agent/main.tf
We just need loopback, which cilium already depends on.
> Drop cni-plugins-main from cilium

- tflib/publisher/main.tf
This in preparation for removing the `wget` applet from `busybox`, into `busybox-full`: https://github.com/wolfi-dev/os/pull/12631
> add wget to -dev variants

- images/cluster-autoscaler/tests/main.tf
our existing `cluster-autoscaler` tests have never actually worked, we just happened to be sneaking them in because the startup readiness checks flap, this is to the point where its consistently broken ([ref](https://github.com/chainguard-images/images/actions/runs/7822870362))
in order to actually deploy the cluster-autoscaler chart in a way that works, it needs some provider to lock on to.
this changes the test to use `imagetest`, and uses `capi` as that "mock" provider for `cluster-autoscaler` to manage. we don't actually trigger a scale event, but just having `capi` on the cluster is enough for `cluster-autoscaler` to go through its regular readiness _and_ liveness sequence.
given that this is a static go app, I'm confident _enough_ that this should be sufficient without needing to …
> migrate cluster-autoscaler to imagetests that actually do something

- images/filebeat/README.md
- images/filebeat/config/main.tf
- images/filebeat/config/template.apko.yaml
- images/filebeat/main.tf
- images/filebeat/metadata.yaml
- images/filebeat/tests/check-filebeat.sh
- images/filebeat/tests/filebeat.yml
- images/filebeat/tests/main.tf
- images/filebeat/tests/test.sh
- images/filebeat/tests/values.yaml
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> filebeat: initial configuration

- images/kyverno-policy-reporter/tests/main.tf
- images/kyverno/tests/helm/main.tf
- images/kyverno/tests/main.tf
deconflicts kyverno and kyverno-policy-reporter by isolating them on separate test harnesses. follows the similar model of #2174
> deconflict kyverno{-policy-reporter} using imagetest

- tflib/imagetest/helm/main.tf
- tflib/imagetest/helm/outputs.tf
- tflib/imagetest/helm/variables.tf
standard helm emits some pretty useless logs when it errors out:
https://github.com/chainguard-images/images-private/actions/runs/7845026704/job/21411213191#step:15:89
```
INSTALLATION FAILED: client rate limiter Wait returned an error: context deadline exceeded
```
This wraps the install in a block and captures the error, and prints a whole bunch more diagnostics similar to the `k8s-diag` error we use.
these will get captured by the provider and emitted as `diagnostics.details`, which in turn will show up in the CI logs as the `<detail></detail>`
> emit more useful logs from failed imagetest helm installs

- images/opentelemetry-collector-contrib/tests/custom-deploy-config.yaml
- images/opentelemetry-collector-contrib/tests/custom-ds-config.yaml
- images/opentelemetry-collector-contrib/tests/custom_config.sh
- images/opentelemetry-collector-contrib/tests/main.tf
* Tests are failing since the release of v0.94.0. Add configuration that works with the new release.
* Migrate tests to the imagetest provider.
> fix: opentelemetry-collector-contrib tests after 0.94.0 release

- images/kubeflow-pipelines/main.tf
- images/kubeflow-pipelines/tests/main.tf
Simplify the configuration of `kubeflow-pipelines`. Have a smaller amount of locals to configure the separate images.
> chore(kubeflow-pipelines): simplify configuration

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
anecdotally I've noticed later versions of terraform run faster, but I don't have any proof. regardless, this seems like a thing we should do
> bump terraform to latest pre-busl

- images/temporal-server/tests/main.tf
Use the envs block to pass environment variables in instead of hardcoding them in the script block.
> chore(temporal-server): use envs block

- images/terraform/config/main.tf
- images/terraform/main.tf
Ran locally
```
module.terraform.oci_tag.latest-busl: Creation complete after 1s [id=ttl.sh/jason/terraform:latest@sha256:2964ce66f290c759abda053b343d297df39555bfc6fcf8cc09de32d2e5c03acb]
module.terraform.oci_tag.latest-busl-dev: Creation complete after 1s [id=ttl.sh/jason/terraform:latest-dev@sha256:f5e69646e91c6db07a1976435faa0f66e8351749aabcd4266b6dde712a69bd75]
module.terraform.oci_tag.pre-busl-dev["1.5"]: Creation complete after 2s [id=ttl.sh/jason/terraform:1.5-dev@sha256:f5e69646e91c6db07a1976435faa0f66e8351749aabcd4266b6dde712a69bd75]
module.terraform.oci_tag.pre-busl["1.5.7"]: Creation complete after 2s [id=ttl.sh/jason/terraform:1.5.7@sha256:2964ce66f290c759abda053b343d297df39555bfc6fcf8cc09de32d2e5c03acb]
module.terraform.oci_tag.pre-busl-dev["1.5.7"]: Creation complete after …
```
> terraform: move latest to BUSL version, add :1.5.7 for last pre-BUSL version

- images/clickhouse/README.md
- images/clickhouse/config/latest.apko.yaml
- images/clickhouse/config/main.tf
- images/clickhouse/main.tf
- images/clickhouse/metadata.yaml
- images/clickhouse/tests/02-runs.sh
- images/clickhouse/tests/main.tf
- main.tf
Notes:
```
$ docker images
REPOSITORY                     TAG       IMAGE ID       CREATED       SIZE
ttl.sh/steve/clickhouse        <none>    5b54ae7f4a63   2 days ago    904MB
clickhouse/clickhouse-server   latest    1d846b541abd   4 days ago    938MB
```
Notes:
```
$ grype clickhouse/clickhouse-server:latest
✔ Vulnerability DB                [no update available]
✔ Parsed image                                                                                                                                                                       sha256:1d846b541abd6acaf1230d2d0a42e8f6ebe1c479bd73fcafa8a4e312365c1dd9
✔ Cataloged contents …
```
> Create Clickhouse Image

- Makefile
`make init` as per documentation fails due to incorrect and invalid flag.
> make: fix init target

- images/ingress-nginx-controller/config/latest.apko.yaml
This is a directory to container the GeoIP2 database which needs to be writable. This directory was updated in 1.9.5 (similar to https://github.com/chainguard-images/images/pull/1986).
See also https://github.com/kubernetes/ingress-nginx/pull/10470
Will follow up with an e2e test for GeoIP2 features to prevent future regression.
> Update mode for ingress-nginx geoip directory

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
Uses ublue-os/remove-unwanted-software to free up additional disk space on runners
Additionally, this has been added to the CI for presubmit
> chore(ci): Aggressively free up runner disk space

- .terraform.lock.hcl
- images/pytorch/README.md
- images/pytorch/TESTING.md
- images/pytorch/config/main.tf
- images/pytorch/main.tf
- images/pytorch/metadata.yaml
- images/pytorch/tests/main.tf
- images/pytorch/tests/pytorch-helm-install.sh
- images/pytorch/tests/quickstart.py
- images/pytorch/tests/torch_optim.py
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> chore: Move pytorch to images

- images/pytorch-cuda12/tests/main.tf
On release, the timeout was exceeded causing this test to fail. Increase the timeout from the default 5m to 10m.
> fix(pytorch-cuda12): Increase helm timeout from 5m to 10m

- images/docker-selenium/README.md
- images/docker-selenium/TESTING.md
- images/docker-selenium/config/main.tf
- images/docker-selenium/main.tf
- images/docker-selenium/metadata.yaml
- images/docker-selenium/tests/main.tf
- images/docker-selenium/tests/smoke.sh
- main.tf
Adds image for Docker Selenium
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> feat(images): Add Docker Selenium

- images/sigstore-policy-controller/tests/main.tf
When building locally the CRDs, and mutating/validating webhooks from the helm tests get left lying around. Aligning the namespace arguments for the helm resources gets the tests to pass, even if the actual objects don't live in a namespace.
> Add random pet name namespace for sigstore-policy-controller helm tests

- images/aws-ebs-csi-driver/tests/01-runs.sh
The upstream binary regressed and the default mode (`all`) no longer works as it did previously. Specifying the mode on the command-line works around that. I proposed a fix upstream.
Ideally we move tests like these into the package itself and use the imagetest provider to deploy tests on AWS, but we aren't quite there yet so we'll have to do this for now.
> Specify subcommands for aws-ebs-csi-driver test

- images/node/config/template.apko.yaml
- images/node/example/Dockerfile
- images/node/example/package.json
This moves our Dockerfile test to use a multi-stage build as described in [docker-node's best practices](https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#smaller-images-without-npmyarn).
This proves the image doesn't _need_ a shell (or `npm`) to run basic apps in a best-practice way.
In the future we can use this test to ensure the image works as expected when/if we remove `sh` and `npm` from the image.
cc @bretfisher
> node: improve Dockerfile test, include dumb-init

- images/argo/tests/check-argo-workflow.sh
- images/argo/tests/main.tf
- images/atlantis/tests/main.tf
- images/aws-for-fluent-bit/tests/main.tf
- images/bank-vaults/tests/main.tf
Batch of test migrations to the new imagetest provider:
* `argo`: https://github.com/chainguard-images/images/pull/2318/commits/20a524b5a8e196c6da204c7be04069c4e303c7ed
* `atlantis`: https://github.com/chainguard-images/images/pull/2318/commits/58a6e397b673bf0cdb262943fce2d49f267d07a8
* `aws-for-fluent-bit`: https://github.com/chainguard-images/images/pull/2318/commits/13db0472ea87ecffb121d1172727e613eab81334
* `bank-vaults`: https://github.com/chainguard-images/images/pull/2318/commits/e2670b0ec30d0babec89a6d90ada28e10105d607
> chore: migrate tests to imagetest

- images/gptscript/README.md
- images/gptscript/config/main.tf
- images/gptscript/main.tf
- images/gptscript/metadata.yaml
- images/gptscript/tests/main.tf
- images/gptscript/tests/smoke.sh
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> feat(images): Add gptscript image

- images/cadvisor/config/template.apko.yaml
This PR resolves a build issue with the cadvisor FIPS image by removing the _'cadvisor'_ value from the _packages_ field in the _template.apko.yaml_ file. 
The cadvisor package is already included in the **_extra_packages_** field, which means that the build process should automatically select the correct package (FIPS or non-FIPS). However, the explicit inclusion of 'cadvisor' in the packages field was causing a conflict, leading to the incorrect package selection.
> remove packages value from cadvisor apko

- images/caddy/config/template.apko.yaml
Fixed a build issue for the caddy FIPS image by removing the 'caddy' value from the packages field in `template.apko.yaml`. This resolves the issue where the build process incorrectly selected the **caddy** package over the required **caddy-fips** package.
> remove packages value from caddy apko

- images/management-api-for-apache-cassandra/config/main.tf
If extra_paths var is set, will append to the paths in this image's apko.yaml
Fulfills customer need for specific data and logs paths.
> feat: make paths extensible via an extra-paths var

- images/maven/main.tf
Match the latest tag of Maven with the version that works with Java 21.
> chore(maven): bump latest tag to match the `openjdk-21` version

- images/php/README.md
- images/php/config/laravel/main.tf
- images/php/config/laravel/template.apko.yaml
- images/php/laravel.tf
- images/php/tests/main.tf
This image is part of an initiative to provide users with images that are plug-and-play for their framework of choice. [Laravel](https://laravel.com) is a popular PHP framework currently in high demand within the PHP ecosystem.
Notes:
Notes:
The CVE detected was not introduced by this image version, it is in the php-fpm package.
```
php-8.2-fpm  8.2.16-r2            apk   CVE-2015-3211  Medium
```
Notes:
Notes:
I am unable to run this test at the moment
Notes:
I am unable to run this test at the moment
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add new PHP image variant for Laravel

- images/chromium/README.md
- images/chromium/config/main.tf
- images/chromium/main.tf
- images/chromium/metadata.yaml
- images/chromium/tests/main.tf
- images/chromium/tests/smoke.sh
- main.tf
Adds Chromium image that runs headless with GPU access disabled and sandboxing turned off
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> feat(images): Add Chromium

- images/jellyfin/README.md
- images/jellyfin/config/main.tf
- images/jellyfin/main.tf
- images/jellyfin/metadata.yaml
- images/jellyfin/tests/main.tf
- images/jellyfin/tests/smoke.sh
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> feat(images): Add Jellyfin

- images/sigstore-policy-controller/config/main.tf
- images/sigstore-policy-controller/tests/main.tf
Migrate the tests of `sigstore-policy-controller` to the imagetest provider so we can deconflict them.
> chore(sigstore-policy-controller): migrate to imagetest

- images/argocd/tests/main.tf
also perform a test that actually checks some functionality
depends on https://github.com/wolfi-dev/os/pull/15456
> migrate argocd to imagetest

- images/trino/config/main.tf
- images/trino/tests/main.tf
The upstream container image contains the `CATALOG_MANAGEMENT` variable set to `static` by default. Ours was failing tests because of this missing variable.
Extra: migrate Helm tests to imagetest.
> fix(trino): add `CATALOG_MANAGEMENT` variable to match upstream

- images/aspnet-runtime/README.md
This PR only includes a minor change to the `aspnet-runtime` Image README.
The reason behind this change was some customer feedback. See [this slack thread](https://chainguard-dev.slack.com/archives/C046AF0NCQY/p1710958553719919) for more info.
> Minor change to aspnet-runtime README

- images/management-api-for-apache-cassandra/config/template.apko.yaml
- images/management-api-for-apache-cassandra/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> accept cassandra_version from outside

- images/nfs-subdir-external-provisioner/TESTING.md
Notes:
Notes:
Notes:
Notes:
Notes:
- This image requires a kubernetes cluster as well as a nfs share setup. I have included more input on the values I have used on the nfs share in the README.md. Note that variables nfs_server and nfs_path will have to be updated depending on the actual values for the nfs server.
- This checks the logs for certain phrases (i.e: "successfully acquired lease", "Starting provisioner controller", "Started provisioner controller")
> Added TESTING.md to nfs-subdir-ext-provisioner

- images/opensearch/tests/main.tf
Use a configuration specific for test so the service doesn't expect certificates to be in-place.
> fix(opensearch): add configuration for test

- images/metallb/README.md
- images/metallb/config/main.tf
- images/metallb/main.tf
- images/metallb/metadata.yaml
- images/metallb/tests/install/main.tf
- images/metallb/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes: the speaker image seems to only work when running as root. I think it is to do with how it manipulates network interfaces. I'd like to investigate this some more in the future.
> Add metallb controller and speaker images

- images/prometheus-blackbox-exporter/README.md
- images/prometheus-blackbox-exporter/config/main.tf
- images/prometheus-blackbox-exporter/main.tf
- images/prometheus-blackbox-exporter/metadata.yaml
- images/prometheus-blackbox-exporter/tests/main.tf
- images/prometheus-blackbox-exporter/tests/smoke-test.sh
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> prometheus-blackbox-exporter

- images/dragonfly/README.md
- images/dragonfly/config/main.tf
- images/dragonfly/main.tf
- images/dragonfly/metadata.yaml
- images/dragonfly/tests/main.tf
- main.tf
This is built from extra-packages because it's BUSL.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add dragonfly image.

- images/metallb/config/main.tf
- images/metallb/main.tf
This PR updates the metallb image modules to support `suffix` and `entrypoint` arguments.
> Update metallb module to work with private and fips images

- images/trust-manager/config/template.apko.yaml
_trust-manager_ is listed under both [packages](https://github.com/chainguard-images/images/blob/main/images/trust-manager/config/template.apko.yaml#L3) in template.apko.yaml and [extra_packages](https://github.com/chainguard-images/images/blob/main/images/trust-manager/config/main.tf#L9) in config/main.tf, causing a conflict and leading to the incorrect package selection.
To fix this, the pull request removes the redundant _trust-manager_ entry from the _packages_ field. This allows the build process to correctly select the appropriate package based on the extra_packages field.
> remove packages value from trust-manager

- images/velero-restore-helper/README.md
- images/velero-restore-helper/config/latest.apko.yaml
- images/velero-restore-helper/config/main.tf
- images/velero-restore-helper/main.tf
- images/velero-restore-helper/metadata.yaml
- images/velero-restore-helper/tests/docker-test.sh
- images/velero-restore-helper/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Image for velero-restore-helper

- images/rstudio/README.md
- images/rstudio/config/main.tf
- images/rstudio/main.tf
- images/rstudio/metadata.yaml
- images/rstudio/tests/main.tf
- images/rstudio/tests/smoke.sh
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> feat(images): Add RStudio

- images/shadowsocks-rust/README.md
- images/shadowsocks-rust/configs/main.tf
- images/shadowsocks-rust/configs/template.sslocal.apko.yaml
- images/shadowsocks-rust/configs/template.ssserver.apko.yaml
- images/shadowsocks-rust/main.tf
- images/shadowsocks-rust/metadata.yaml
- images/shadowsocks-rust/tests/01-smoke.sh
- images/shadowsocks-rust/tests/main.tf
- main.tf
* shadowsocks-rust-sslocal
> **Note**
> **Before:** `14.2MB, 15 packages, 0-CVE`
> **After:** `31.6MB, 10 packages, 0-CVE`
* shadowsocks-rust-ssserver
> **Note**
> **Before:** `12.5MB, 15 packages, 0-CVE`
> **After:** `29.9MB, 10 packages, 0-CVE`
Notes: On both images, `/usr/lib/locale` is sized `18MB`.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes: ssserver requires root
> add shadowsocks-rust

- images/velero-plugin-for-aws/README.md
- images/velero-plugin-for-aws/config/main.tf
- images/velero-plugin-for-aws/main.tf
- images/velero-plugin-for-aws/metadata.yaml
- images/velero-plugin-for-aws/tests/docker-test.sh
- images/velero-plugin-for-aws/tests/main.tf
- main.tf
Notes: we include the binary twice in different locations this is why we have bigger images because we use -compat here to make sure that we have that binary in the location where Dockerfile expects to be
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> velero plugin for aws

- images/aws-cli-v2/README.md
- images/aws-cli-v2/config/latest.apko.yaml
- images/aws-cli-v2/config/main.tf
- images/aws-cli-v2/main.tf
- images/aws-cli-v2/metadata.yaml
- images/aws-cli-v2/tests/01-help.sh
- images/aws-cli-v2/tests/main.tf
- main.tf
Pretty much a copy of aws-cli image
Fixes: https://github.com/chainguard-images/images/issues/2404
basic test
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> new image: aws-cli-v2

- images/velero-plugin-for-aws/tests/docker-test.sh
- images/velero-plugin-for-aws/tests/main.tf
This is required to tests pass if repo/image name is different than `velero-plugin-for-aws`.
> ability to override init container name for velero-plugin-for-aws

- images/go/config/template.apko.yaml
I noticed while doing some image analysis that we're including `openssh-server` in the Go image. I don't see why this is needed, so following what the git image is doing and only include the client.
> [go] Only include openssh-client

- images/bincapz/README.md
- images/bincapz/config/main.tf
- images/bincapz/config/template.apko.yaml
- images/bincapz/main.tf
- images/bincapz/metadata.yaml
- images/bincapz/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add a `bincapz` image

- images/yara/README.md
- images/yara/config/main.tf
- images/yara/config/template.apko.yaml
- images/yara/main.tf
- images/yara/metadata.yaml
- images/yara/tests/main.tf
- images/yara/tests/test-yar.sh
- images/yara/tests/test.yar
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add a `yara` image.

- images/velero-plugin-for-aws/tests/docker-test.sh
Removing colon from image name for test, resolves:
```bash
The Deployment "velero" is invalid: spec.template.spec.initContainers[0].name: Invalid value: "chainguard-velero-plugin-for-aws:unused": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
```
> Fix test issue where invalid container name was used

- images/metallb/config/main.tf
This tidies unused frrrouting dependencies from the metallb-speaker image.
> remove unused metallb-speaker frrouting image dependencies

- images/harbor/main.tf
Done to simplify package names in version streams
> chore(harbor): Rename package for harbor core to harbor

- images/postgres-operator/config/main.tf
- images/postgres-operator/config/template.apko.yaml
A minor addition to #2420, I missed adding the compat package that softlinks the binary as helm charts usually expects and this fixes it
> adds compat package for postgres-operator image

- images/cert-manager-webhook-pdns/README.md
- images/cert-manager-webhook-pdns/config/main.tf
- images/cert-manager-webhook-pdns/config/template.apko.yaml
- images/cert-manager-webhook-pdns/main.tf
- images/cert-manager-webhook-pdns/metadata.yaml
- images/cert-manager-webhook-pdns/tests/01-smoke.sh
- images/cert-manager-webhook-pdns/tests/main.tf
- main.tf
> **Note**
> **Before:** `71.5MB, 113 packages, 13 CVEs`
> **After:** `57.4MB, 101 packages, 0-CVE`
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes: Their Deployment uses Readiness probes so additional functional tests might not need to.
Notes:
Notes:
Notes:
> add cert-manager-webhook-pdns

- images/velero-plugin-for-csi/README.md
- images/velero-plugin-for-csi/config/main.tf
- images/velero-plugin-for-csi/main.tf
- images/velero-plugin-for-csi/metadata.yaml
- images/velero-plugin-for-csi/tests/docker-test.sh
- images/velero-plugin-for-csi/tests/main.tf
- main.tf
Notes: we included the binary twice but for two different locations
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
- [] Functional tests have been included and the tests are passing.  All tests have been documnted in the notes section.
Notes:
Notes:
Notes:
Notes:
> velero plugin for csi

- images/velero-plugin-for-aws/main.tf
- images/velero-plugin-for-aws/tests/docker-test.sh
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> refactor velero-plugin-for-aws tests

- images/python/README.md
Per [this slack convo](https://chainguard-dev.slack.com/archives/C04PYHWPE1F/p1711726846991599) it was determined that we should document how to access the shell in the `python:latest-dev` image. This PR adds a line explaining how to do so and an example command one can run to open up the shell.
> minor update to Python Image README

- images/wasmer/tests/02-use.sh
Go 1.21 introduced an experimental mode for building WebAssembly System Interface applications. This change switches back to using our Chainguard Go Image with the experimental flags.
Ref: https://tip.golang.org/doc/go1.21#wasip1
> chore(wasm): use regular Go with experimental flags

- images/istio/configs/install-cni/main.tf
The istio-install-cni image needs `iptables` to function correctly: 
https://github.com/istio/istio/blob/master/cni/deployments/kubernetes/Dockerfile.install-cni#L16
https://github.com/istio/istio/blob/master/tools/istio-iptables/pkg/README.md
> Add iptables to istio-install-cni image

- images/harbor/README.md
- images/harbor/config/main.tf
- images/harbor/main.tf
- images/harbor/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> feat(harbor): Add trivy adapter image

- images/conda/config/template.apko.yaml
Adds the base environment as well as a wrapper for initialization out of the box
Also runs image as root so that conda recognizes the base env exists
> fix(conda): Initialize and enter base environment at startup

- .gitignore
- images/spark-operator/config/main.tf
This switches our image to use the newer/version streamed `spark-3.5` package, and includes the JVM.
> spark-operator: Fix broken image test

- images/argocd-extension-installer/README.md
- images/argocd-extension-installer/config/main.tf
- images/argocd-extension-installer/main.tf
- images/argocd-extension-installer/metadata.yaml
- images/argocd-extension-installer/tests/main.tf
- images/argocd-extension-installer/tests/smoke.sh
- main.tf
Notes: 5MB only
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> argocd-extension-installer

- images/neuvector-prometheus-exporter/README.md
- images/neuvector-prometheus-exporter/config/main.tf
- images/neuvector-prometheus-exporter/config/template.apko.yaml
- images/neuvector-prometheus-exporter/main.tf
- images/neuvector-prometheus-exporter/metadata.yaml
- images/neuvector-prometheus-exporter/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> add neuvector-prometheus-exporter

- images/temporal-admin-tools/config/template.apko.yaml
curl is required by the upstream Helm chart: https://github.com/temporalio/helm-charts/blob/b2d81e53499de77b10428a64a6cfc7c87f86bb70/charts/temporal/templates/server-job.yaml#L385-L397
> temporal-admin-tools: Include curl

- images/temporal-server/tests/helm.sh
- Upgrade Helm chart to match temporal v1.23.0
- Adds elasticsearch since cassandra is no longer an option for the visibility backend (https://github.com/temporalio/helm-charts/pull/459)
- Use our version of `temporal-admin-tools` since we have v1.23.0 (upstream doesn't have it yet)
> temporal-server: Fix test

- images/newrelic-nri-statsd/README.md
- images/newrelic-nri-statsd/config/main.tf
- images/newrelic-nri-statsd/main.tf
- images/newrelic-nri-statsd/metadata.yaml
- images/newrelic-nri-statsd/tests/main.tf
- images/newrelic-nri-statsd/tests/smoke.sh
- main.tf
waiting for this: 
- ~https://github.com/wolfi-dev/os/pull/16451~
- thanks to @EyeCantCU, we set entrypoint as `/home/nonroot/nri-statsd.sh` and it worked! 
Notes:
Notes:
Notes:
Notes: needs newrelic account
Notes: needs newrelic account
Notes:
Notes:
Notes: needs newrelic account
Notes:
Notes:
Notes:
> newrelic-nri-statsd

- images/step-ca/README.md
- images/step-ca/config/main.tf
- images/step-ca/config/template.apko.yaml
- images/step-ca/main.tf
- images/step-ca/metadata.yaml
- images/step-ca/tests/k8s-test.sh
- images/step-ca/tests/main.tf
- images/step-cli/README.md
- images/step-cli/config/main.tf
- images/step-cli/config/template.apko.yaml
- images/step-cli/main.tf
- images/step-cli/metadata.yaml
- images/step-cli/tests/main.tf
- main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add step cli and step-ca

- .terraform.lock.hcl
- images/filebeat/tests/check-filebeat.sh
- images/filebeat/tests/main.tf
- images/filebeat/tests/test.sh
filebeat sometimes fails its test with a conflicting CRD. imagetest runs in a sandbox which eliminates the conflicting CRD problem
> migrate filebeat to imagetest

- images/rabbitmq/tests/02-perf.sh
- images/rabbitmq/tests/main.tf
Whenever we run rabbit test modules in parallel they conflict on the network name
> Deflake rabbitmq test

- images/spark-operator/config/main.tf
Move JRE to extra_packages, so we can invoke the terraform module with a different JRE version
> Move JRE to extra_packages

- withdrawn-repos.txt
The `kubeflows-pipelines` image has been decomposed into [multiple separate images](https://github.com/chainguard-images/images/blob/main/images/kubeflow-pipelines/main.tf#L8) and is no longer being released as a standalone entity. Therefore, withdrawing it from our registry.
> withdraw kubeflow-pipelines

- images/envoy-ratelimit/tests/main.tf
- images/envoy-ratelimit/tests/runs.sh
Migrate the basic container test to use the new Docker harness in imagetest.
> chore(envoy-ratelimit): move script tests to imagetest

- images/powershell/configs/latest-root.apko.yaml
- images/powershell/configs/latest.apko.yaml
Powershell uses `less -P` when paging, which is not supported by BusyBox less.
> powershell: add less package as dependency

- images/tesseract/README.md
Using remotely hosted image for OCR ensures anybody can run the image and verify it works without having to provide any input files.
> tesseract-doc: Update doc with remote usage

- .terraform.lock.hcl
As per [documentation](https://developer.hashicorp.com/terraform/language/files/dependency-lock#new-provider-package-checksums) terraform init will silently add extra h1 hashes, if upon calculation they match one of the existing trusted zh hashes. My suspicion is that my hash is for x86_64 install, whilst the other h1 hashes are for aarch64 machines.
> Add second h1 hashes for helm, imagetest, cosign, apko

- .terraform.lock.hcl
- images/envoy-ratelimit/tests/main.tf
- images/envoy-ratelimit/tests/runs.sh
- images/external-secrets/tests/main.tf
- images/jre/tests/02-hello-world.sh
- images/jre/tests/main.tf
Revert Docker harness tests while we figure out what's wrong.
> chore: revert docker harness tests

- images/kubernetes-autoscaler-addon-resizer/README.md
- images/kubernetes-autoscaler-addon-resizer/config/main.tf
- images/kubernetes-autoscaler-addon-resizer/main.tf
- images/kubernetes-autoscaler-addon-resizer/metadata.yaml
- images/kubernetes-autoscaler-addon-resizer/tests/main.tf
- main.tf
> **Note**
> **Before:** `35.9MB, 38 packages, 9 vulnerabilities`
> **After:** `29.9MB, 4 packages, 0-CVE`
---
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add kubernetes-autoscaler-addon-resizer

- images/pytorch-cuda12/tests/main.tf
More time is needed to pull the containers
> fix(pytorch-cuda12): Increase timeout for installing Helm chart

- images/pytorch-cuda12/README.md
Updated the pytorch-cuda12 image with  more specific instructions on how to run test scripts, including a curl command. Also added commands for checking GPU devices,, more section headers, and some clarifications.
> Added curl to test script, GPU test commands, some clarifications

- .terraform.lock.hcl
Bump the following providers to latest:
* `imagetest`: v0.0.17
* `hashicorp/random`: v3.6.1
> chore(terraform): bump provider versions

- .terraform.lock.hcl
- Makefile
Generate hashes for darwin_arm64 & linux_amd64 platforms, such that local `make init` is clean for everybody.
> Generate hashes for linux amd64

- images/conda/config/main.tf
- images/conda/config/template.apko.yaml
Allows this module to be re-used and permits passing in different conda packages
> Allow all conda packages to be passed in

- Makefile
Change `make init` to use existing lock file in read-only mode. Add a new target `make init-upgrade` to upgrade dependencies manually if desired.
Separately Dependabot pull requests can upgrade lock file correctly - see https://github.com/chainguard-images/images/pull/2509/files for an example of lifecycle management.
This ensures reproducibility across all developers, in presubmit/production builds, and also across time. As older checkouts from now on, will use matching terraform providers.
> terraform: actually use VCS committed lock file

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
For consistency with other chainguard image building repositories upgrade to terraform 1.6.* too.
> terraform: upgrade to 1.6.*

- images/gha-runner-scale-set-controller/README.md
I'm fixing the README because the private image CI is failing due to this:
```
module.gha-runner-scale-set-controller.module.versioned["actions-runner-controller"].chainguard_image_repo.repo[0]: failed string validation
readme is invalid: readme contained unsafe html content. diff:   (
"""
... // 103 identical lines
<blockquote>
<p>🤖 You can see the self-hosted runner that you registered within the project's runners tab:
- 	<a href="https://github.com/">https://github.com/</a><your_enterprise/org/repo>/actions/runners?tab=self-hosted</p>
+ 	<a href="https://github.com/">https://github.com/</a>/actions/runners?tab=self-hosted</p>
</blockquote>
... // 16 identical lines
"""
)
```
This PR aims to fix this issue.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> fix readme for gha-runner-scale-set-controller

- images/keycloak/README.md
- images/keycloak/config/main.tf
Attempt to resolve: `java.lang.IllegalStateException: java.nio.file.FileSystemException: /usr/share/java/keycloak/lib/quarkus/generated-bytecode.jar: Read-only file system` error.
> keycloak: fix helm command on doc and missing permission path

- images/pytorch-cuda12/tests/main.tf
This is still timing out while pulling the image down because of how large it is. Increases the timeout from 10 minutes to 15 minutes
> fix(pytorch-cuda12): Further increase Helm timeout

- images/cassandra-medusa/tests/medusa-install.sh
There are lots of moving parts in this test. Resources and dependencies take a while to get created, and become ready.
Also switching some of the dependencies to pull in chainguard images
> Add waits and retries

- images/cassandra-reaper/config/template.apko.yaml
Looks like we do need the environment variables mentioned in https://github.com/chainguard-images/images/pull/2567
I fired up the container and checked the process and it's running with
```
1 nonroot   0:56 java -Xms2147483648 -Xmx2147483648 -Djava.io.tmpdir= -cp /usr/local/lib/* io.cassandrareaper.ReaperApplication server /etc/cassandra-reaper/cassandra-reaper.yml
```
Which is setting the tmpdir to an empty string since the env is missing and the entrypoint tries to use it.
> Fix reaper tmpdir envrionment variables

- images/cassandra-medusa/tests/medusa-install.sh
Stargate is problematic and does not always come up cleanly depending on the arch. This test is not validating stargate and it's not needed, so disabling
> disable stargate check, which is problematic

- images/postgres/main.tf
Drops version pinning in favor of always building with the latest version of PostgreSQL in Wolfi
> fix(postgresql): Build with latest version

- images/postgres/config/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> fix(postgres): Update entrypoint to reflect upstream

- images/node-lts/generated.tf
- images/node-lts/main.tf
- images/node/config/main.tf
- images/node/config/template.apko.yaml
- images/node/generated.tf
- images/node/main.tf
This will result in no net changes to 'node:latest' and 'node:latest-dev', but will create a 'node:next' and 'node:next-dev'. The next tag will not have npm or busybox inside.
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> Add 'node:next' without npm and busybox.

- images/bincapz/tests/main.tf
Fixes broken test: https://github.com/chainguard-images/images/actions/runs/8878974775/job/24375737285?pr=2587#step:12:177
The previous test assumed a particular output format and criticality. That criticality will likely change, so this now tests for output headers. I'm still not convinced this is doing the right thing though.
> bincapz: search for header values rather than assuming criticality

- images/harbor/README.md
- images/harbor/config/main.tf
- images/harbor/main.tf
- images/harbor/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> feat(harbor): Add Harbor DB

- images/newrelic-nri-statsd/config/main.tf
Versioned builds of this image were missing the busybox dependency so move it into the config so we don't accidentally override it
> Move busybox to config in newrelic-nri-statsd

- images/kyverno/tests/helm/main.tf
- images/kyverno/tests/main.tf
Previously we were only testing the public images vs the images we just built, so the tests were failing when the helm chart upgraded and we weren't testing our newly built images
> Test built kyverno images

- images/pytorch-cuda12/tests/main.tf
CI still doens't have sufficient time to retrieve the image. Increase this by 5 minutes again
> fix(pytorch-cuda12): Increase Helm timeout again

- .terraform.lock.hcl
Bump the imagetest dependency to latest (v0.0.18)
> chore(deps): bump imagetest to v0.0.18

- images/rust/README.md
The docs referred to a CC image that no longer exists.
Closes #2314
> Docs Fix: Change references from cc to glibc-dynamic in Rust docs

- images/datadog-agent/config/agent/latest.apko.yaml
- images/datadog-agent/config/agent/main.tf
fixes the entrypoints dependencies on `s6-overlay` v2.x
depends on https://github.com/wolfi-dev/os/pull/18194/files
> fixes for datadog agent

- images/rabbitmq/generated.tf
- images/rabbitmq/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> rabbitmq version streams.

- images/haproxy/config/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> use haproxy-2.9

- generated.tf
- images/tomcat/config/main.tf
- images/tomcat/config/template.apko.yaml
- images/tomcat/tests/main.tf
- images/tomcat/tests/run.sh
This adds the `tomcat-webapps` package to our Tomcat images. It includes the `host-manager` and `manager` applications. They are disabled by default, but users expect them to be available to deploy into the webapps directory.
> Add tomcat-webapps to tomcat images

- images/cassandra-medusa/tests/main.tf
- images/cassandra-medusa/tests/medusa-install.sh
I've noticed that there was a failure due to long naming, so this PR aims to fix this:
```
bash-5.2# kubectl get k8ssandraclusters.k8ssandra.io -A
NAMESPACE                 NAME                    ERROR
k8s-medusa-comic-magpie   cassandra-medusa-fips   CronJob.batch "cassandra-medusa-fips-cassandra-medusa-fips-medusa-purge" is invalid: metadata.name
: Invalid value: "cassandra-medusa-fips-cassandra-medusa-fips-medusa-purge": must be no more than 52 characters
```
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> fix the naming of the k8ssandracluster resource

- images/bincapz/tests/main.tf
bincapz ignores itself now, which means the test erroneously passed, which failed. 🫠
> bincapz: fix test

- images/pytorch-cuda12/tests/main.tf
Bump the outer (`imagetest_feature`) and inner (`helm`) timeouts.
> bump test timeouts

- withdrawn-repos.txt
These tags were withdrawn in withdrawn-images.txt, but the repos still exist, and shouldn't.
> withdraw jitsucom-bulker-* repos

- images/kube-vip/tests/check-kube-vip.sh
- images/kube-vip/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> migrate to imagetest_harness

- images/kube-vip/tests/check-kube-vip.sh
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> retry until you get nodes

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
- .gitignore
- images/cert-manager/main.tf
- main.tf
uses the new file based logging for `imagetest` to output and upload `imagetest` based logs.
this bypasses the strict logging required by terraform providers by dumping them to a file, which we'll postprocess with various downstream tooling
> upload imagetest-logs directory

- images/nginx/main.tf
Seems it was selecting the later "stable" package config
> Fix the nginx config package

- images/vault/tests/acceptance.sh
When building multiple streams, these file names may overlap.
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>
> vault: store cluster-keys in unique file names

- images/datadog-agent/config/agent/latest.apko.yaml
the `/bin/entrypoint.sh` makes all sorts of assumptions that expect the entrypoint to be a `CMD` and not an `ENTRYPOINT`
> change this to a cmd to match how upstream expects things

- .github/workflows/release.yaml
This `echo` was echoing the bare json which was something like `echo [{"index":"0","blah":"foo bar "},{"index":"1","bleh": "baz jon"}]`. The curly braces stacked next to each other computes the permutation of all the values inside the curly brackets. We just want it to print the json string
> Fix the shard output echo

- images/git/alpine.tf
- images/git/main.tf
The Alpine-based `git` image variant is currently broken
```
resolving apk packages: solving "git-lfs" constraint: could not find package that provides git-lfs in indexes
```
https://github.com/chainguard-images/images/actions/runs/9098882464/job/25010161552#step:13:43
This fails at planning time, which means all images that share its release shard (e.g., go) are also not being rebuilt.
This temporarily stops the Alpine-based `git` image build, so that the rest of the shard can get updates.
> temporarily disable alpine git image builds to unblock

- .terraform.lock.hcl
- images/git/alpine.tf
- images/git/main.tf
- tflib/publisher/main.tf
The latest tf-apko build should be able to build images without hitting the git-lfs issue that was blocking Alpine-based `git` image builds before.
This undoes #2687 with the fix.
> upgrade tf-apko, re-enable git alpine build

- images/keycloak/config/main.tf
Will probably fix this https://github.com/chainguard-images/images/issues/451 as the `keycloak-compat` package handles the hardcoded stuff in `/opt/keycloak/bin`
> adds keycloak-compat in keycloak image

- images/zig/tests/build-image.sh
init-exe now fails with command does not exist, seems to have been renamed to just init.
> zig: new zig changed project bootstrap command

- images/jenkins/main.tf
Jenkins does not have a version streamed compat package. Change the `extra_packages` directive to stop trying to translate the package name into a version-streamed version of it.
> fix(jenkins): use correct compat package

- images/keycloak-operator/tests/keycloak-test.sh
- images/keycloak-operator/tests/main.tf
- images/keycloak/README.md
- images/keycloak/tests/keycloak-production-mode.sh
- images/keycloak/tests/main.tf
Expand Keycloak test coverage. Update README to refer to our keycloak-operator instead of previous helm chart - which was not fully compatible.
> Expand test coverage, README update

- images/rstudio/tests/main.tf
- images/rstudio/tests/smoke.sh
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> chore(rstudio): Move to Docker imagetest harness

- images/pytorch-cuda12/tests/main.tf
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> disabling pytorch test

- .github/workflows/withdraw-images.yaml
Add a "best effort" withdrawal of the specified image's `*-dev` variant in addition to withdrawing the specified image itself.
cc: @imjasonh
> withdraw -dev variants too

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
- .github/workflows/withdraw-images.yaml
- .github/workflows/withdraw-repos.yaml
This brings in the following changes:
ba1a9c9 (HEAD -> main, upstream/main, upstream/HEAD) update action to use new c>
77965ce Bump tj-actions/changed-files from 44.3.0 to 44.4.0 (#429)
25a26c8 upgrade arifact actions to v4 (#432)
b71790d update ci tests (#431)
4a4a027 bump kind to v0.23.0 add 1.30 k8s / remove 1.23/24 and updates kindest/>
3d3cb8d Bump step-security/harden-runner from 2.7.0 to 2.7.1 (#425)
73d51cb Bump actions/setup-go from 5.0.0 to 5.0.1 in /boilerplate (#426)
1105f78 Bump actions/setup-go from 5.0.0 to 5.0.1 (#427)
67c8811 Bump actions/checkout from 4.1.3 to 4.1.5 (#428)
97bd985 deprecate setup-chainctl in favor of the other repo (#399)
8799517 Bump actions/upload-artifact from 4.3.2 to 4.3.3 in /kind-diag (#422)
4995b58 Update README.md (#423)
bcf69bc Bump …
> github: upgrade chainguard-dev actions commit

- images/busybox/README.md
- images/git/README.md
- images/static/README.md
Adds a warning to the git, busybox and static images about upcoming changes.
Fixes https://github.com/chainguard-dev/internal/issues/3821
> Add warning of upcoming changes to images.

- images/cassandra/config/main.tf
- images/cassandra/config/template.apko.yaml
nodetool doesn't work on our Cassandra image.
```
Upstream :
CONTAINER_ID=$(docker run -d cassandra:latest)
docker exec -it $CONTAINER_ID nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load        Tokens  Owns (effective)  Host ID                               Rack
UN  172.17.0.3  104.34 KiB  16      100.0%            d1e04976-9d2b-4854-96e0-cad35cf3bde2  rack1
```
```
Chainguard 'cassandra' image :
docker exec -it 106306b84660 nodetool status
grep: /usr/bin/../conf/jvm-clients.options: No such file or directory
grep: /usr/bin/../conf/jvm11-clients.options: No such file or directory
Error opening zip file or JAR manifest missing : /usr/bin/../lib/jamm-0.3.2.jar
Error occurred during initialization of VM …
```
> fixes in cassandra image

- images/calico/configs/latest.apiserver.apko.yaml
- images/calico/configs/latest.calicoctl.apko.yaml
- images/calico/configs/latest.cni.apko.yaml
- images/calico/configs/latest.csi.apko.yaml
- images/calico/configs/latest.kube-controllers.apko.yaml
- images/calico/configs/latest.node-driver-registrar.apko.yaml
- images/calico/configs/latest.node.apko.yaml
- images/calico/configs/latest.pod2daemon.apko.yaml
- images/calico/configs/latest.typha.apko.yaml
- images/calico/configs/main.tf
- images/calico/main.tf
This lets other invokers of this module specify their own extra_packages on a per-component basis.
For the public image, this should have no effect on behavior.
> calico: allow customizing images with extra_packages

- .github/workflows/release.yaml
- .github/workflows/withdraw-images.yaml
- .github/workflows/withdraw-repos.yaml
As per warnings this will break in August 2024.
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>
> github: switch setup-chainctl to non-deprecated location

- .github/workflows/release.yaml
when this was introduced we'd see typical savings of ~25G, nowadays this is more like ~3G ([ref](https://github.com/chainguard-images/images/actions/runs/9209338848/job/25333708323#step:5:1449)).
More problematic, this takes much longer (~7m!) on the larger 64c runners postsubmit uses due to all the additional cruft not present on the presubmit runners.
While we probably still need this for presubmit, where space is at a premium on the smaller runners, in postsubmit where the 64c machines have [~2Tb](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#specifications-for-general-larger-runners) disks I'm arguing this isn't worth it anymore.
> don't cleanup disk space on release

- .terraform.lock.hcl
somehow i hoped this would be automated, but it is not.
> make init-upgrade to get linux-amd64 hashes

- images/docker-selenium/main.tf
- images/eck-operator/main.tf
- images/local-volume-provisioner/main.tf
- images/nvidia-container-toolkit/main.tf
- images/opensearch-dashboards/main.tf
- tflib/publisher/main.tf
Spot-checking failed tests, they seem to be pre-existing test flakes/failures, and not related to this new check.
If there are any images with invalid SBOMs for any reason, we can unblock with `check-sbom = false` for that image, and address it later.
> default check-sbom: true

- images/tigera-operator/tests/helm/main.tf
The latest tigera-operator seems to need the latest calico version
> Bump calico version for tigera-operator test

- images/pytorch-cuda12/main.tf
Turning off per #2727 due to proprietary license to be fixed 
>  Unrecognized license reference: PROPRIETARY. license_expression must only use IDs from the license list or extracted licensing info, but is: PROPRIETARY
> pytorch-cuda12: disable check-sbom for now

- images/nvidia-container-toolkit/README.md
Fixes a relative `TESTING.md` link when presented in the directory overview.
> Fix nvidia-container-toolkit testing.md link

- images/kafka/config/main.tf
Set as a package runtime dependency instead
> chore(kafka): Don't include JVM in extra packages

- images/kube-logging-operator-fluentd/config/main.tf
Move the default plugins to the config vs extra_packages.
> Update the default packages for kube-logging-operator-fluentd

- images/loki/config/template.apko.yaml
- images/loki/tests/main.tf
also changes the uid to match upstream to avoid the various "permission errors" that were popping up
> deconflict multiple lokis

- .github/workflows/presubmit-build.yaml
- .github/workflows/release.yaml
Our `k8s-diag` step has been failing for two weeks now and nobody has yelled about it. We started collecting logs from `imagetest` and the ultimate goal is to get all k8s tests on `imagetest`. I'm proposing we remove the `k8s-diag` step as a way of investing even more in `imagetest`
> Deprecate the k8s-diag step to push usage of imagetest

- tflib/publisher/main.tf
Undoes #2727 
Image builds seem to fail to install `spdx-tools-java`, and don't notify Slack as expected.
> check-sbom: default to false again :(

- images/loki/tests/main.tf
loki v2.x is still a supported stream, but the latest chart supporting v2.x configuration is pinned to 5.48.0. this supports that by accepting a `loki_version` and conditionally using the appropriate values
> support multiple version streams of loki helm charts

- images/cassandra-medusa/config/main.tf
This makes grpc-health-probe an image build option
> cassandra-medusa: make grpc-health-probe configurable

- images/jenkins/config/main.tf
- images/jenkins/config/template.apko.yaml
- images/jenkins/main.tf
- images/jenkins/tests/controller/main.tf
- images/jenkins/tests/hello-world.sh
- images/jenkins/tests/main.tf
I'm about the furthest thing from a jenkins knower, but apparently plugins are important.
This is ensure the scripts/dependencies needed for initializing, supporting, and downloading plugins are available in the image.
Most importantly, it ensures we're compatible with the upstream default helm chart installation. Previously, if you tried to install a vanilla jenkins installation we would bomb out for various plugin reasons.
> ensure jenkins works with plugins

- .github/workflows/presubmit-build.yaml
- images/crane/main.tf
The way we `terraform apply -json` means the otherwise useful plan output is suppressed, which loses helpful debugging information. For each module we build, we'll first do a `tf plan` in a collapsed section.
Example: https://github.com/chainguard-images/images/actions/runs/9339594424/job/25704189217?pr=2784#step:11:3310
> show plan for each module before building

- .terraform.lock.hcl
Bump the imagetest provider to the latest v0.0.20.
> chore(imagetest): bump provider to v0.0.20

- images/harbor/main.tf
harbor-scanner-trivy binary execs trivy binary, thus dependency was
added on the apk level. Thus one doesn't need to specify trivy
dependency anymore.
Related:
- https://github.com/wolfi-dev/os/pull/21243
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@chainguard.dev>
> harbor: drop trivy package dep (included in apk)

- images/cassandra-medusa/tests/main.tf
- images/cassandra-medusa/tests/medusa-install.sh
Use shortnames in imagetest (using random_id not random_pet) to prevent names longer the k8s limits
The cassandra operator expects medusa  images to consist of registry, repository, image, tag 
Update test pod/statefulset wait/timeouts due to upstream removal of standalone pod
> cassandra-medusa use shorter names

- images/dex/config/main.tf
Ensure that the `gomplate` package is always included in the image even when a value is specified for the `extra_packages` variable.
> fix(dex): ensure gomplate is included even when extra_packages is specified

- .github/workflows/presubmit-readme.yaml
According to https://github.com/tj-actions/changed-files?tab=readme-ov-file#outputs-
any_modified	string	Returns true when any of
the filenames provided using the
files* or files_ignore* inputs have been modified. This defaults to true when
no patterns are specified. i.e.
includes a combination of all added, copied, modified, renamed, and deleted files (ACMRD).
The check should have failed in #2818 but it didnt, that is bad
> Fix up presubmit-readme.yaml

- .github/workflows/release.yaml
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
Notes:
> update chainctl to 0.2.1

- withdrawn-repos.txt
removed in https://github.com/chainguard-images/images/pull/2597
> withdraw harbor-db repo

- withdrawn-repos.txt
See https://www.chainguard.dev/unchained/updates-to-lts-images-in-chainguard-images-developer-tier
> DNM (until 2024-08-12): LTS Turn Down

- withdrawn-images.txt
> Withdraw kaniko:test

- images/postgres/main.tf
Defines variables id and run-as used in `config/main.tf` and builds default postgres image with the latest tag.
> Defines id and run-as variables for postgres-image

- withdrawn-repos.txt
withdraw `pytorch-cuda12` image, as it is superseded by `pytorch`
> withdraw pytorch-cuda12

- .github/workflows/release.yaml
https://github.com/chainguard-images/images/pull/2937 dropped us to 2 shards, but that means when one of them fails to plan (like one does now) it takes down ~half of our images.
Instead, let's just give each image its own shard.
> use more shards

- .github/workflows/release.yaml
#2938 except without 32c runners per.
this should put us at 4c per shard: https://github.com/joshrwolf/images/pull/new/smaller-runners
> use smaller runners

- .github/dependabot.yml
This Action has been compromised and we should avoid any updates.
> Ignore tj-actions/changed-files updates

- .github/workflows/release.yaml
Previously, on X-Men:
https://github.com/chainguard-images/images/pull/2938
https://github.com/chainguard-images/images/pull/2940
> release: bump shards to 60 so each module lives alone

- .github/workflows/release.yaml
test a theory in the shard "logic" causing everything to go into 1 shard.
I think n_shards needs to be n_imagemodules otherwise everything is packed into 1 shard
> reduce shards to 50

- .github/workflows/release.yaml
removes the "logic" behind the packing and just places each image into its own shard.
> shard per image

- .github/workflows/release.yaml
we no longer use workflow provisioned k3d clusters. cluster creation is delegated to the test harnesses
> remove k3d setup
